<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>plugins</artifactId>
        <groupId>io.jans.jans-config-api.plugins</groupId>
        <version>0.0.0-nightly</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>shibboleth-plugin</artifactId>
    <name>Janssen Shibboleth Plugin</name>
    <description>Config API plugin for the management of Shibboleth IDP Trust Relationships,
		their orchestration via an M2M set of endpoints and OOB file upload via a file staging API
	</description>

	<properties>
		<httpcore.version>4.4.14</httpcore.version>
		<httpclient.version>4.5.13</httpclient.version>
		<openapi-generator.version>7.24.0</openapi-generator.version>
		<jans.version>${project.version}</jans.version>
	</properties>

    <dependencies>
        <dependency>
            <groupId>io.jans</groupId>
            <artifactId>jans-config-api-shared</artifactId>
            <version>${jans.version}</version>
        </dependency>
        <dependency>
            <groupId>io.jans</groupId>
            <artifactId>jans-config-api-server</artifactId>
            <version>${jans.version}</version>
        </dependency>
        <dependency>
            <groupId>io.jans</groupId>
            <artifactId>jans-orm-annotation</artifactId>
            <version>${jans.version}</version>
        </dependency>
        <dependency>
            <groupId>io.jans</groupId>
            <artifactId>jans-core-model</artifactId>
            <version>${jans.version}</version>
        </dependency>

		<dependency>
			<groupId>io.jans</groupId>
			<artifactId>jans-core-document-store</artifactId>
			<version>${jans.version}</version>
		</dependency>
		
		<!-- Jans Shibboleth API dependency -->
		<dependency>
            <groupId>io.jans</groupId>
            <artifactId>jans-kernel</artifactId>
            <version>${project.version}</version>
        </dependency>
		<dependency>
			<groupId>io.jans</groupId>
			<artifactId>jans-shibboleth-trust-adapters</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>io.jans</groupId>
			<artifactId>jans-shibboleth-trust-domain</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>io.jans</groupId>
			<artifactId>jans-file-staging-domain</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>io.jans</groupId>
			<artifactId>jans-file-staging-adapters</artifactId>
			<version>${project.version}</version>
		</dependency>
		
		<!-- Others -->        
        <dependency>
            <groupId>commons-collections</groupId>
            <artifactId>commons-collections</artifactId>
        </dependency>
        
        <!-- Swagger -->
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-core-jakarta</artifactId>
		</dependency>
		
        <!-- Test dependencies -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

<build>
		<filters>
			<filter>../../profiles/${cfg}/config-build.properties</filter>
			<filter>../../profiles/${cfg}/config-api-test.properties</filter>
		</filters>

		<testResources>
			<testResource>
				<directory>src/test/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>karate.properties</include>
					<include>karate_jenkins.properties</include>
					<include>test.properties</include>
					<include>*.*</include>
				</includes>
			</testResource>
		</testResources>

		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>**/*.xml</include>
					<include>**/*.properties</include>
					<include>**/*.json</include>
					<include>META-INF/services/*.*</include>
				</includes>
			</resource>
		</resources>


		<plugins>

			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>${openapi-generator.version}</version>
				<executions>
					<!-- == TRUST CONFIGURATION API ==-->
					<execution>
						<id>generate-trust-configuration-api</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>../../../jans-shibboleth-idp/openapi/trust-config/trust-config-api.yaml</inputSpec>
							<generatorName>jaxrs-spec</generatorName>
							<apiPackage>io.jans.shibboleth.trust.api.config.rs</apiPackage>
							<generateModels>false</generateModels>
							<generateApiTests>false</generateApiTests>
							<generateModelTests>false</generateModelTests>
							<generateModelDocumentation>false</generateModelDocumentation>
							<generateSupportingFiles>false</generateSupportingFiles>
							<configOptions>
								<interfaceOnly>true</interfaceOnly>
								<returnResponse>true</returnResponse>
								<useJakartaEe>true</useJakartaEe>
								<sourceFolder>src/gen/java</sourceFolder>
								<useSwaggerAnnotations>false</useSwaggerAnnotations>
								<openApiNullable>false</openApiNullable>
								<useTags>true</useTags>
							</configOptions>
							<importMappings>
								<importMapping>CreateTrustRelationshipRequest=io.jans.shibboleth.trust.dto.config.CreateTrustRelationshipRequest</importMapping>
								<importMapping>UpdateBasicInfoRequest=io.jans.shibboleth.trust.dto.config.UpdateBasicInfoRequest</importMapping>
								<importMapping>MetadataSourceRequest=io.jans.shibboleth.trust.dto.config.MetadataSourceRequest</importMapping>
								<importMapping>NoneMetadataSourceRequest=io.jans.shibboleth.trust.dto.config.NoneMetadataSourceRequest</importMapping>
								<importMapping>UriMetadataSourceRequest=io.jans.shibboleth.trust.dto.config.UriMetadataSourceRequest</importMapping>
								<importMapping>UpstreamMetadataSourceRequest=io.jans.shibboleth.trust.dto.config.UpstreamMetadataSourceRequest</importMapping>
								<importMapping>MdqMetadataSourceRequest=io.jans.shibboleth.trust.dto.config.MdqMetadataSourceRequest</importMapping>
								<importMapping>FileMetadataSourceRequest=io.jans.shibboleth.trust.dto.config.FileMetadataSourceRequest</importMapping>
								<importMapping>ManualMetadataSourceRequest=io.jans.shibboleth.trust.dto.config.ManualMetadataSourceRequest</importMapping>
								<importMapping>AssertionConsumerServiceRequest=io.jans.shibboleth.trust.dto.config.AssertionConsumerServiceRequest</importMapping>
								<importMapping>SamlBinding=io.jans.shibboleth.trust.config.metadata.manual.SamlBinding</importMapping>
								<importMapping>MetadataSourceView=io.jans.shibboleth.trust.dto.config.MetadataSourceView</importMapping>
								<importMapping>NoneMetadataSourceView=io.jans.shibboleth.trust.dto.config.NoneMetadataSourceView</importMapping>
								<importMapping>FileMetadataSourceView=io.jans.shibboleth.trust.dto.config.FileMetadataSourceView</importMapping>
								<importMapping>UriMetadataSourceView=io.jans.shibboleth.trust.dto.config.UriMetadataSourceView</importMapping>
								<importMapping>UpstreamMetadataSourceView=io.jans.shibboleth.trust.dto.config.UpstreamMetadataSourceView</importMapping>
								<importMapping>MdqMetadataSourceView=io.jans.shibboleth.trust.dto.config.MdqMetadataSourceView</importMapping>
								<importMapping>ManualMetadataSourceView=io.jans.shibboleth.trust.dto.config.ManualMetadataSourceView</importMapping>
								<importMapping>AssertionConsumerServiceView=io.jans.shibboleth.trust.dto.config.AssertionConsumerServiceView</importMapping>
								<importMapping>ProfilesView=io.jans.shibboleth.trust.dto.config.ProfilesView</importMapping>
								<importMapping>Saml2LogoutProfileConfigurationView=io.jans.shibboleth.trust.dto.config.Saml2LogoutProfileConfigurationView</importMapping>
								<importMapping>Saml2ArtifactResolutionProfileConfigurationView=io.jans.shibboleth.trust.dto.config.Saml2ArtifactResolutionProfileConfigurationView</importMapping>
								<importMapping>Saml2AttributeQueryProfileConfigurationView=io.jans.shibboleth.trust.dto.config.Saml2AttributeQueryProfileConfigurationView</importMapping>
								<importMapping>ShibbolethSsoProfileConfigurationView=io.jans.shibboleth.trust.dto.config.ShibbolethSsoProfileConfigurationView</importMapping>
								<importMapping>Saml2EcpProfileConfigurationView=io.jans.shibboleth.trust.dto.config.Saml2EcpProfileConfigurationView</importMapping>
								<importMapping>Saml2SsoProfileConfigurationView=io.jans.shibboleth.trust.dto.config.Saml2SsoProfileConfigurationView</importMapping>
								<importMapping>TrustRelationshipSummary=io.jans.shibboleth.trust.dto.config.TrustRelationshipSummary</importMapping>
								<importMapping>TrustRelationshipPage=io.jans.shibboleth.trust.dto.config.TrustRelationshipPage</importMapping>
								<importMapping>PageMetadata=io.jans.shibboleth.trust.dto.shared.PageMetadata</importMapping>
								<importMapping>TrustNature=io.jans.shibboleth.trust.config.TrustNature</importMapping>
								<importMapping>TrustStatus=io.jans.shibboleth.trust.config.TrustStatus</importMapping>
								<importMapping>TrustRelationshipDetail=io.jans.shibboleth.trust.dto.config.TrustRelationshipDetail</importMapping>
								<importMapping>MetadataSourceSummary=io.jans.shibboleth.trust.dto.config.MetadataSourceSummary</importMapping>
								<importMapping>MetadataSourceType=io.jans.shibboleth.trust.config.metadata.MetadataSourceType</importMapping>
								<importMapping>ProfileSummary=io.jans.shibboleth.trust.dto.config.ProfileSummary</importMapping>
								<importMapping>ProfileType=io.jans.shibboleth.trust.config.profile.common.ProfileType</importMapping>
								<importMapping>ProfileStatus=io.jans.shibboleth.trust.config.profile.common.ProfileStatus</importMapping>
								<importMapping>Saml2LogoutProfileConfigurationRequest=io.jans.shibboleth.trust.dto.config.Saml2LogoutProfileConfigurationRequest</importMapping>
								<importMapping>MessageSigningPolicy=io.jans.shibboleth.trust.config.profile.common.MessageSigningPolicy</importMapping>
								<importMapping>RequestSignatureValidationPolicy=io.jans.shibboleth.trust.config.profile.common.RequestSignatureValidationPolicy</importMapping>
								<importMapping>EncryptionFallbackPolicy=io.jans.shibboleth.trust.config.profile.common.EncryptionFallbackPolicy</importMapping>
								<importMapping>NameIdEncryptionPolicy=io.jans.shibboleth.trust.config.profile.common.NameIdEncryptionPolicy</importMapping>
								<importMapping>Saml2ArtifactResolutionProfileConfigurationRequest=io.jans.shibboleth.trust.dto.config.Saml2ArtifactResolutionProfileConfigurationRequest</importMapping>
								<importMapping>AssertionSigningPolicy=io.jans.shibboleth.trust.config.profile.common.AssertionSigningPolicy</importMapping>
								<importMapping>AssertionEncryptionPolicy=io.jans.shibboleth.trust.config.profile.common.AssertionEncryptionPolicy</importMapping>
								<importMapping>AttributeEncryptionPolicy=io.jans.shibboleth.trust.config.profile.common.AttributeEncryptionPolicy</importMapping>
								<importMapping>Saml2AttributeQueryProfileConfigurationRequest=io.jans.shibboleth.trust.dto.config.Saml2AttributeQueryProfileConfigurationRequest</importMapping>
								<importMapping>AssertionTimeCondition=io.jans.shibboleth.trust.config.profile.common.AssertionTimeCondition</importMapping>
								<importMapping>FriendlyNameRandomizationPolicy=io.jans.shibboleth.trust.config.profile.common.FriendlyNameRandomizationPolicy</importMapping>
								<importMapping>ShibbolethSsoProfileConfigurationRequest=io.jans.shibboleth.trust.dto.config.ShibbolethSsoProfileConfigurationRequest</importMapping>
                				<importMapping>AuthenticationResultReusePolicy=io.jans.shibboleth.trust.config.profile.common.AuthenticationResultReusePolicy</importMapping>
                				<importMapping>AttributeStatementPolicy=io.jans.shibboleth.trust.config.profile.common.AttributeStatementPolicy</importMapping>
                				<importMapping>Saml2EcpProfileConfigurationRequest=io.jans.shibboleth.trust.dto.config.Saml2EcpProfileConfigurationRequest</importMapping>
                				<importMapping>EndpointValidationPolicy=io.jans.shibboleth.trust.config.profile.common.EndpointValidationPolicy</importMapping>
                				<importMapping>RequestSigningRequirement=io.jans.shibboleth.trust.config.profile.common.RequestSigningRequirement</importMapping>
                				<importMapping>Saml2SsoProfileConfigurationRequest=io.jans.shibboleth.trust.dto.config.Saml2SsoProfileConfigurationRequest</importMapping>
                				<importMapping>UpdateReleasedAttributesRequest=io.jans.shibboleth.trust.dto.config.UpdateReleasedAttributesRequest</importMapping>
                				<importMapping>ReleasedAttributesView=io.jans.shibboleth.trust.dto.config.ReleasedAttributesView</importMapping>
                				<importMapping>ReleasedAttribute=io.jans.shibboleth.trust.dto.config.ReleasedAttributeDto</importMapping>
                				<importMapping>ActivationDiagnostics=io.jans.shibboleth.trust.dto.config.ActivationDiagnosticsDto</importMapping>
                				<importMapping>ActivationStatus=io.jans.shibboleth.trust.shared.diagnostics.ActivationStatus</importMapping>
                				<importMapping>ActivationLogEntry=io.jans.shibboleth.trust.dto.config.ActivationLogEntryDto</importMapping>
                				<importMapping>LogLevel=io.jans.shibboleth.trust.shared.diagnostics.LogLevel</importMapping>
								<!-- problem and violation base classes-->
                				<importMapping>Problem=io.jans.shibboleth.trust.api.problem.Problem</importMapping>
                				<importMapping>Violation=io.jans.shibboleth.trust.api.problem.Violation</importMapping>
							</importMappings>
						</configuration>
					</execution>
					<!-- == END TRUST CONFIGURATION API == -->
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
							<descriptors>
								<descriptor>src/main/assembly/assembly.xml</descriptor>
							</descriptors>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<systemPropertyVariables>
					</systemPropertyVariables>
					<excludedGroups>integration</excludedGroups>
					<systemProperties>
						<karate.options>--tags ~@ignore</karate.options>
					</systemProperties>
				</configuration>
				<executions>
					<execution>
						<id>integration-tests</id>
						<phase>integration-test</phase>
						<goals>
							<goal>test</goal>
						</goals>
						<configuration>
							<failIfNoTests>false</failIfNoTests>
							<excludedGroups>!integration</excludedGroups>
							<groups>integration</groups>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<executions>
					<execution>
						<id>deploy-to-local-folder</id>
						<phase>package</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>../target/plugins</outputDirectory>
							<resources>
								<resource>
									<directory>${project.build.directory}</directory>
									<include>*-distribution.jar</include>
									<filtering>false</filtering>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>
</project>
