<#macro main>

    <h3 class="text-center">Do you find the Club meetings entertained?</h3>
    
    <div>
        <input type="radio" name="option" id="1" value="yes" checked>
        <label for="1">No doubt!</label>
    </div>
    <div>
        <input type="radio" name="option" id="2" value="somewhat">
        <label for="2">Somewhat</label>
    </div>
    <div>
        <input type="radio" name="option" id="3" value="notmuch">
        <label for="3">Not much, frankly</label>
    </div>
    <div>
        <input type="radio" name="option" id="4" value="no">
        <label for="4">Not at all</label>
    </div>

</#macro>
