openapi: 3.0.1
info:
  title: jans-config-api
  description: jans-config-api - Authorization services
  contact:
    email: xxx@gluu.org
  license:
    name: License
    url: 'https://github.com/JanssenProject/blob/master/LICENSE'
  version: '1.0.0'
servers:
  - url: 'https://jans.io/'
tags:
  - name: developers
    description: jans-config-api enables access to the features available via the existing Jans Authorization Server API.
  - name: Attribute
  - name: Default Authentication Method
  - name: Cache Configuration
  - name: Cache Configuration – Memcached
  - name: Cache Configuration – Redis
  - name: Cache Configuration – in-Memory
  - name: Cache Configuration – Native-Persistence
  - name: Configuration – Properties
  - name: Fido2 - Configuration
  - name: Configuration – SMTP
  - name: Configuration – Logging
  - name: Configuration – JWK - JSON Web Key (JWK)
  - name: Custom Scripts
  - name: Database - LDAP configuration
  - name: OAuth - OpenID Connect - Clients
  - name: OAuth - UMA Resources
  - name: OAuth - Scopes
  - name: Configuration – Agama Flow
  - name: Statistics - User
  - name: Health - Check
  - name: Server Stats
  - name: Auth - Session Management
  - name: Configuration – User Management
  - name: SCIM - Config Management
  - name: Organization Configuration
  - name: Auth Server Health - Check
  - name: Admin UI - Role
  - name: Admin UI - Permission
  - name: Admin UI - Role-Permissions Mapping
  - name: Admin UI - License
paths:
  /jans-config-api/api/v1/jans-auth-server/config:
    get:
      summary: Gets all Jans authorization server configuration properties.
      description: Gets all Jans authorization server configuration properties.
      operationId: get-properties
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/properties.readonly]
      tags:
        - Configuration – Properties
    patch:
      summary: Partially modifies Jans authorization server Application configuration properties.
      description: Partially modifies Jans authorization server AppConfiguration properties.
      operationId: patch-properties
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/properties.write]
      tags:
        - Configuration – Properties
  /jans-config-api/api/v1/jans-auth-server/config/persistence:
    get:
      summary: Returns persistence type configured for Jans authorization server.
      description: Returns persistence type configured for Jans authorization server.
      operationId: get-properties-persistence
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/properties.readonly]
      tags:
        - Configuration – Properties
  /jans-config-api/fido2/config:
    get:
      summary: Gets Jans Authorization Server Fido2 configuration properties.
      description: Gets Jans Authorization Server Fido2 configuration properties.
      operationId: get-properties-fido2
      tags:
        - Fido2 - Configuration
      security:
        - oauth2: [https://jans.io/oauth/config/fido2.readonly]
    put:
      summary: Updates Fido2 configuration properties.
      description: Updates Fido2 configuration properties.
      operationId: put-properties-fido2
      tags:
        - Fido2 - Configuration
      security:
        - oauth2: [https://jans.io/oauth/config/fido2.write]
  /jans-config-api/fido2/registration/entries/{username}:
    get:
      summary: Get details of connected FIDO2 devices registered to user.
      description: Get details of connected FIDO2 devices registered to user.
      operationId: get-registration-entries-fido2
      tags:
        - Fido2 - Configuration
      security:
        - oauth2: [ https://jans.io/oauth/config/fido2.readonly ]
		
  /jans-config-api/api/v1/attributes:
    get:
      summary: Gets a list of Gluu attributes.
      description: 'Gets all attributes. Optionally max-size of the result, attribute status and pattern can be provided.'
      operationId: get-all-attribute
      tags:
        - Attribute
      security:
        - oauth2: [https://jans.io/oauth/config/attributes.readonly]
    post:
      summary: Adds a new attribute.
      description: Adds a new attribute.
      operationId: post-attributes
      tags:
        - Attribute
      security:
        - oauth2: [https://jans.io/oauth/config/attributes.write]
    put:
      summary: Updates an existing attribute.
      description: Updates an existing attribute.
      operationId: put-attributes
      tags:
        - Attribute
      security:
        - oauth2: [https://jans.io/oauth/config/attributes.write]
  '/jans-config-api/api/v1/attributes/{inum}':
    get:
      summary: Gets an attribute based on inum.
      description: Gets an attribute based on inum.
      operationId: get-attributes-by-inum
      tags:
        - Attribute
      security:
        - oauth2: [https://jans.io/oauth/config/attributes.readonly]
    delete:
      summary: Deletes an attribute based on inum.
      description: Deletes an attribute based on inum.
      operationId: delete-attributes-by-inum
      tags:
        - Attribute
      security:
        - oauth2: [https://jans.io/oauth/config/attributes.delete]
    patch:
      summary: Partially modify a GluuAttribute.
      description: Partially modify a GluuAttribute.
      operationId: patch-attributes-by-inum
      security:
        - oauth2: [https://jans.io/oauth/config/attributes.write]
      tags:
        - Attribute
  /jans-config-api/api/v1/acrs:
    get:
      summary: Gets default authentication method.
      description: Gets default authentication method.
      operationId: get-acrs
      tags:
        - Default Authentication Method
      security:
        - oauth2: [https://jans.io/oauth/config/acrs.readonly]
    put:
      summary: Updates default authentication method.
      description: Updates default authentication method.
      operationId: put-acrs
      tags:
        - Default Authentication Method
      security:
        - oauth2: [https://jans.io/oauth/config/acrs.write]
  /jans-config-api/api/v1/config/database/ldap:
    get:
      summary: Gets list of existing LDAP configurations.
      description: Gets list of existing LDAP configurations.
      operationId: get-config-database-ldap
      tags:
        - Database - LDAP configuration
      security:
        - oauth2: [https://jans.io/oauth/config/database/ldap.readonly]
    post:
      summary: Adds a new LDAP configuration.
      description: Adds a new LDAP configuration.
      operationId: post-config-database-ldap
      tags:
        - Database - LDAP configuration
      security:
        - oauth2: [https://jans.io/oauth/config/database/ldap.write]
    put:
      summary: Updates LDAP configuration.
      description: Updates LDAP configuration.
      operationId: put-config-database-ldap
      tags:
        - Database - LDAP configuration
      security:
        - oauth2: [https://jans.io/oauth/config/database/ldap.write]
  /jans-config-api/api/v1/config/database/ldap/{name}:
    get:
      summary: Gets an LDAP configuration by name.
      description: Gets an LDAP configuration by name.
      operationId: get-config-database-ldap-by-name
      tags:
        - Database - LDAP configuration
      security:
        - oauth2: [https://jans.io/oauth/config/database/ldap.readonly]
    delete:
      summary: Deletes an LDAP configuration.
      description: Deletes an LDAP configuration.
      operationId: delete-config-database-ldap-by-name
      tags:
        - Database - LDAP configuration
      security:
        - oauth2: [https://jans.io/oauth/config/database/ldap.delete]
    patch:
      summary: Partially modify an LDAP configuration.
      description: Partially modify an LDAP configuration.
      operationId: patch-config-database-ldap-by-name
      security:
        - oauth2: [https://jans.io/oauth/config/database/ldap.write]
      tags:
        - Database - LDAP configuration
  /jans-config-api/api/v1/config/database/ldap/test:
    post:
      summary: Tests an LDAP configuration.
      description: Tests an LDAP configuration.
      operationId: post-config-database-ldap-test
      tags:
        - Database - LDAP configuration
      security:
        - oauth2: [https://jans.io/oauth/config/database/ldap.readonly]


  /jans-config-api/api/v1/config/scripts:
    get:
      summary: Gets a list of custom scripts.
      description: Gets a list of custom scripts.
      operationId: get-config-scripts
      tags:
        - Custom Scripts
      security:
        - oauth2: [https://jans.io/oauth/config/scripts.readonly]
    post:
      summary: Adds a new custom script.
      description: Adds a new custom script.
      operationId: post-config-scripts
      tags:
        - Custom Scripts
      security:
        - oauth2: [https://jans.io/oauth/config/scripts.write]
    put:
      summary: Updates a custom script.
      description: Updates a custom script.
      operationId: put-config-scripts
      x-cli-getdata: get-config-scripts-by-inum
      tags:
        - Custom Scripts
      security:
        - oauth2: [https://jans.io/oauth/config/scripts.write]

  /jans-config-api/api/v1/config/scripts/name/{name}:
    get:
      summary: Fetch custom script by name.
      description: Fetch custom script by name.
      operationId: get-custom-script-by-name
      tags:
        - Custom Scripts
      security:
        - oauth2: [https://jans.io/oauth/config/scripts.readonly]

  /jans-config-api/api/v1/config/scripts/type/{type}:
    get:
      summary: Gets list of scripts by type.
      description: Gets list of scripts by type.
      operationId: get-config-scripts-by-type
      x-cli-ignore: true
      tags:
        - Custom Scripts
      security:
        - oauth2: [https://jans.io/oauth/config/scripts.readonly]
  /jans-config-api/api/v1/config/scripts/inum/{inum}:
    get:
      summary: Gets a script by Inum.
      description: Gets a script by Inum.
      operationId: get-config-scripts-by-inum
      x-cli-ignore: true
      tags:
        - Custom Scripts
      security:
        - oauth2: [https://jans.io/oauth/config/scripts.readonly]
  /jans-config-api/api/v1/config/scripts/{inum}:
    delete:
      summary: Deletes a custom script.
      description: Deletes a custom script.
      operationId: delete-config-scripts-by-inum
      tags:
        - Custom Scripts
      security:
        - oauth2: [https://jans.io/oauth/config/scripts.delete]
    patch:
      summary: Partially update custom script.
      description: Partially update custom script.
      operationId: patch-config-scripts-by-inum
      security:
        - oauth2: [https://jans.io/oauth/config/scripts.write]
      tags:
        - Custom Scripts
  /jans-config-api/api/v1/config/cache:
    get:
      summary: Returns cache configuration.
      description: Returns cache configuration.
      operationId: get-config-cache
      tags:
        - Cache Configuration
      security:
        - oauth2: [https://jans.io/oauth/config/cache.readonly]
    patch:
      summary: Partially modifies cache configuration.
      description: Partially modifies cache configuration.
      operationId: patch-config-cache
      tags:
        - Cache Configuration
      security:
        - oauth2: [https://jans.io/oauth/config/cache.write]
  /jans-config-api/api/v1/config/cache/memcached:
    get:
      summary: Returns Memcached cache configuration.
      description: Returns Memcached cache configuration.
      operationId: get-config-cache-memcached
      tags:
        - Cache Configuration – Memcached
      security:
        - oauth2: [https://jans.io/oauth/config/cache.readonly]
    put:
      summary: Updates Memcached cache configuration.
      description: Updates Memcached cache configuration.
      operationId: put-config-cache-memcached
      tags:
        - Cache Configuration – Memcached
      security:
        - oauth2: [https://jans.io/oauth/config/cache.write]
    patch:
      summary: Partially modifies Memcached cache configuration.
      description: Partially modifies Memcached cache configuration.
      operationId: patch-config-cache-memcached
      tags:
        - Cache Configuration – Memcached
      security:
        - oauth2: [https://jans.io/oauth/config/cache.write]
  /jans-config-api/api/v1/config/cache/redis:
    get:
      summary: Returns Redis cache configuration.
      description: Returns Redis cache configuration.
      operationId: get-config-cache-redis
      tags:
        - Cache Configuration – Redis
      security:
        - oauth2: [https://jans.io/oauth/config/cache.readonly]
    put:
      summary: Updates Redis cache configuration.
      description: Updates Redis cache configuration.
      operationId: put-config-cache-redis
      tags:
        - Cache Configuration – Redis
      security:
        - oauth2: [https://jans.io/oauth/config/cache.write]
    patch:
      summary: Partially modifies Redis cache configuration.
      description: Partially modifies Redis cache configuration.
      operationId: patch-config-cache-redis
      tags:
        - Cache Configuration – Redis
      security:
        - oauth2: [https://jans.io/oauth/config/cache.write]
  /jans-config-api/api/v1/config/cache/in-memory:
    get:
      summary: Returns in-Memory cache configuration.
      description: Returns in-Memory cache configuration.
      operationId: get-config-cache-in-memory
      tags:
        - Cache Configuration – in-Memory
      security:
        - oauth2: [https://jans.io/oauth/config/cache.readonly]
    put:
      summary: Updates in-Memory cache configuration.
      description: Updates in-Memory cache configuration.
      operationId: put-config-cache-in-memory
      tags:
        - Cache Configuration – in-Memory
      security:
        - oauth2: [https://jans.io/oauth/config/cache.write]
    patch:
      summary: Partially modifies In-Memory cache configuration.
      description: Partially modifies In-Memory cache configuration.
      operationId: patch-config-cache-in-memory
      tags:
        - Cache Configuration – in-Memory
      security:
        - oauth2: [https://jans.io/oauth/config/cache.write]
  /jans-config-api/api/v1/config/cache/native-persistence:
    get:
      summary: Returns native persistence cache configuration.
      description: Returns native persistence cache configuration.
      operationId: get-config-cache-native-persistence
      tags:
        - Cache Configuration – Native-Persistence
      security:
        - oauth2: [https://jans.io/oauth/config/cache.readonly]
    put:
      summary: Updates native persistence cache configuration.
      description: Updates native persistence cache configuration.
      operationId: put-config-cache-native-persistence
      tags:
        - Cache Configuration – Native-Persistence
      security:
        - oauth2: [https://jans.io/oauth/config/cache.write]
    patch:
      summary: Partially modifies Native Persistence cache configuration.
      description: Partially modifies Native Persistence cache configuration.
      operationId: patch-config-cache-native-persistence
      tags:
        - Cache Configuration – Native-Persistence
      security:
        - oauth2: [https://jans.io/oauth/config/cache.write]
  /jans-config-api/api/v1/config/smtp:
    get:
      summary: Returns SMTP server configuration.
      description: Returns SMTP server configuration.
      operationId: get-config-smtp
      tags:
        - Configuration – SMTP
      security:
        - oauth2: [https://jans.io/oauth/config/smtp.readonly]
    post:
      summary: Adds SMTP server configuration.
      description: Adds SMTP server configuration.
      operationId: post-config-smtp
      tags:
        - Configuration – SMTP
      security:
        - oauth2: [https://jans.io/oauth/config/smtp.write]
    put:
      summary: Updates SMTP server configuration.
      description: Updates SMTP server configuration.
      operationId: put-config-smtp
      tags:
        - Configuration – SMTP
      security:
        - oauth2: [https://jans.io/oauth/config/smtp.write]
    delete:
      summary: Deletes SMTP server configuration.
      description: Deletes SMTP server configuration.
      operationId: delete-config-smtp
      tags:
        - Configuration – SMTP
      security:
        - oauth2: [https://jans.io/oauth/config/smtp.delete]
  /jans-config-api/api/v1/config/smtp/test:
    post:
      summary: Test SMTP server configuration.
      description: Test SMTP server configuration.
      operationId: test-config-smtp
      tags:
        - Configuration – SMTP
      security:
        - oauth2: [https://jans.io/oauth/config/smtp.readonly]
  /jans-config-api/api/v1/logging:
    get:
      tags:
        - Configuration – Logging
      summary: Returns Jans Authorization Server logging settings.
      description: Returns Jans Authorization Server logging settings.
      operationId: get-config-logging
      security:
        - oauth2: [https://jans.io/oauth/config/logging.readonly]
    put:
      tags:
        - Configuration – Logging
      summary: Updates Jans Authorization Server logging settings.
      description: Updates Jans Authorization Server logging settings.
      operationId: put-config-logging
      security:
        - oauth2: [https://jans.io/oauth/config/logging.write]
  /jans-config-api/api/v1/config/jwks:
    get:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Gets list of JSON Web Key (JWK) used by server.
      description: 'Gets list of JSON Web Key (JWK) used by server. JWK is a JSON data structure that represents a set of public keys as a JSON object [RFC4627].'
      operationId: get-config-jwks
      security:
        - oauth2: [https://jans.io/oauth/config/jwks.readonly]
    put:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Puts/replaces JWKS
      description: Puts/replaces JSON Web Keys (JWKS).
      operationId: put-config-jwks
      security:
        - oauth2: [https://jans.io/oauth/config/jwks.write]
    patch:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Patch JWKS
      description: Patch JSON Web Keys (JWKS).
      operationId: patch-config-jwks
      security:
        - oauth2: [https://jans.io/oauth/config/jwks.write]
  /jans-config-api/api/v1/config/jwks/key:
    post:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Adds a new key to JSON Web Keys (JWKS)
      description: Adds a new key to JSON Web Keys (JWKS).
      operationId: post-config-jwks-key
      security:
        - oauth2: [https://jans.io/oauth/config/jwks.write]
  /jans-config-api/api/v1/config/jwks/{kid}:
    get:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Get a JSON Web Key based on kid
      description: Get a JSON Web Key based on kid
      operationId: put-config-jwk-kid
      security:
        - oauth2: [https://jans.io/oauth/config/jwks.readonly]
    patch:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Patch a specific JSON Web Key based on kid
      description: Patch a specific JSON Web Key based on kid
      operationId: patch-config-jwk-kid
      security:
        - oauth2: [https://jans.io/oauth/config/jwks.write]
    delete:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Delete a JSON Web Key based on kid
      description: Delete a JSON Web Key based on kid
      operationId: delete-config-jwk-kid
      security:
        - oauth2: [https://jans.io/oauth/config/jwks.delete]
  /jans-config-api/api/v1/openid/clients:
    get:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Gets list of OpenID Connect clients
      description: Gets list of OpenID Connect clients
      operationId: get-oauth-openid-clients
      security:
        - oauth2: [https://jans.io/oauth/config/openid/clients.readonly]
    post:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Create new OpenId Connect client
      description: Create new OpenId Connect client
      operationId: post-oauth-openid-clients
      security:
        - oauth2: [https://jans.io/oauth/config/openid/clients.write]
    put:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Update OpenId Connect client.
      description: Update OpenId Connect client.
      operationId: put-oauth-openid-clients
      security:
        - oauth2: [https://jans.io/oauth/config/openid/clients.write]
  /jans-config-api/api/v1/openid/clients/{inum}:
    get:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Get OpenId Connect Client by Inum
      description: Get OpenId Connect Client by Inum.
      operationId: get-oauth-openid-clients-by-inum
      security:
        - oauth2: [https://jans.io/oauth/config/openid/clients.readonly]
    delete:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Delete OpenId Connect client.
      description: Delete OpenId Connect client.
      operationId: delete-oauth-openid-clients-by-inum
      security:
        - oauth2: [https://jans.io/oauth/config/openid/clients.delete]
    patch:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Update modified properties of OpenId Connect client by Inum.
      description: Update modified properties of OpenId Connect client by Inum.
      operationId: patch-oauth-openid-clients-by-inum
      security:
        - oauth2: [https://jans.io/oauth/config/openid/clients.write]

  /jans-config-api/api/v1/uma/resources:
    get:
      tags:
        - OAuth - UMA Resources
      summary: Gets list of UMA resources.
      description: Gets list of UMA resources.
      operationId: get-oauth-uma-resources
      security:
        - oauth2: [https://jans.io/oauth/config/uma/resources.readonly]
    post:
      tags:
        - OAuth - UMA Resources
      summary: Creates an UMA resource.
      description: Creates an UMA resource.
      operationId: post-oauth-uma-resources
      security:
        - oauth2: [https://jans.io/oauth/config/uma/resources.write]
    put:
      tags:
        - OAuth - UMA Resources
      summary: Updates an UMA resource.
      description: Updates an UMA resource.
      operationId: put-oauth-uma-resources
      security:
        - oauth2: [https://jans.io/oauth/config/uma/resources.write]
  /jans-config-api/api/v1/uma/resources/{id}:
    get:
      tags:
        - OAuth - UMA Resources
      summary: Gets an UMA resource by ID.
      description: Gets an UMA resource by ID.
      operationId: get-oauth-uma-resources-by-id
      security:
        - oauth2: [https://jans.io/oauth/config/uma/resources.readonly]

    delete:
      tags:
        - OAuth - UMA Resources
      summary: Deletes an UMA resource.
      description: Deletes an UMA resource.
      operationId: delete-oauth-uma-resources-by-id
      security:
        - oauth2: [https://jans.io/oauth/config/uma/resources.delete]

    patch:
      tags:
        - OAuth - UMA Resources
      summary: Partially updates an UMA resource by Inum.
      description: Partially updates an UMA resource by Inum.
      operationId: patch-oauth-uma-resources-by-id
      security:
        - oauth2: [https://jans.io/oauth/config/uma/resources.write]


  /jans-config-api/api/v1/uma/resources/clientId/{clientId}:
    get:
      tags:
        - OAuth - UMA Resources
      summary: Fetch uma resources by client id.
      description: Fetch uma resources by client id.
      operationId: get-oauth-uma-resources-by-clientid
      security:
        - oauth2: [https://jans.io/oauth/config/uma/resources.readonly]


  /jans-config-api/api/v1/scopes:
    get:
      tags:
        - OAuth - Scopes
      summary: Gets list of Scopes.
      description: Gets list of Scopes. Optionally type to filter the scope, max-size of the result and pattern can be provided.
      operationId: get-oauth-scopes
      security:
        - oauth2: [https://jans.io/oauth/config/scopes.readonly]
    post:
      tags:
        - OAuth - Scopes
      summary: Create Scope.
      description: Create Scope.
      operationId: post-oauth-scopes
      security:
        - oauth2: [https://jans.io/oauth/config/scopes.write]
    put:
      tags:
        - OAuth - Scopes
      summary: Updates existing Scope.
      description: Updates existing Scope.
      operationId: put-oauth-scopes
      security:
        - oauth2: [https://jans.io/oauth/config/scopes.write]
  /jans-config-api/api/v1/scopes/{inum}:
    get:
      tags:
        - OAuth - Scopes
      summary: Get Scope by Inum
      description: Get Scope by Inum
      operationId: get-oauth-scopes-by-inum
      security:
        - oauth2: ['https://jans.io/oauth/config/scopes.readonly']
    delete:
      tags:
        - OAuth - Scopes
      summary: Delete Scope.
      description: Delete Scope.
      operationId: delete-oauth-scopes-by-inum
      security:
        - oauth2: [https://jans.io/oauth/config/scopes.delete]
    patch:
      tags:
        - OAuth - Scopes
      summary: Update modified attributes of existing Scope by Inum.
      description: Update modified attributes of existing Scope by Inum.
      operationId: patch-oauth-scopes-by-id
      security:
        - oauth2: [https://jans.io/oauth/config/scopes.write]

  /jans-config-api/api/v1/scopes/creator/{creatorId}:
    get:
      tags:
        - OAuth - Scopes
      summary: Get Scope by creatorId
      description: Get Scope by creatorId
      operationId: get-scope-by-creator
      security:
        - oauth2: ['https://jans.io/oauth/config/scopes.readonly']

  /jans-config-api/api/v1/scopes/type/{type}:
    get:
      tags:
        - OAuth - Scopes
      summary: Get Scope by Type
      description: Get Scope by type
      operationId: get-scope-by-type
      security:
        - oauth2: ['https://jans.io/oauth/config/scopes.readonly']

  /jans-config-api/api/v1/agama:
    get:
      summary: Fetches all agama flow.
      description: Fetches all agama flow.
      operationId: get-agama-flows
      tags:
        - Configuration – Agama Flow
      security:
        - oauth2: [https://jans.io/oauth/config/agama.readonly]
    post:
      summary: Create a new agama flow.
      description: Create a new agama flow.
      operationId: post-agama-flow
      tags:
        - Configuration – Agama Flow
      security:
        - oauth2: [https://jans.io/oauth/config/agama.write]

  /jans-config-api/api/v1/agama/{qname}:
    get:
      summary: Gets an agama flow based on Qname.
      description: Gets an agama flow based on Qname.
      operationId: get-agama-flow
      tags:
        - Configuration – Agama Flow
      security:
        - oauth2: [https://jans.io/oauth/config/agama.readonly]
    
    post:
      summary: Create a new agama flow from source.
      description: Create a new agama flow from source.
      operationId: post-agama-flow-from-source
      tags:
        - Configuration – Agama Flow
      security:
        - oauth2: [https://jans.io/oauth/config/agama.write]
   
    patch:
      summary: Partially modify a Agama Flow.
      description: Partially modify a Agama Flow.
      operationId: patch-agama-flow
      tags:
        - Configuration – Agama Flow
      security:
        - oauth2: [https://jans.io/oauth/config/agama.write]

    delete:
      summary: Deletes an agama flow based on Qname.
      description: Deletes an agama flow based on Qname.
      operationId: delete-agama-flow
      tags:
        - Configuration – Agama Flow
      security:
        - oauth2: [https://jans.io/oauth/config/agama.delete]

  /jans-config-api/api/v1/agama/source/{qname}:
    put:
      summary: Update agama flow from source file.
      description: Update agama flow from source file.
      operationId: put-agama-flow-from-source
      tags:
        - Configuration – Agama Flow
      security:
        - oauth2: [https://jans.io/oauth/config/agama.write]

  /jans-config-api/api/v1/stat:
    get:
      summary: Provides server with basic statistic.
      description: Provides server with basic statistic.
      operationId: get-stat
      security:
        - oauth2: [https://jans.io/oauth/config/stats.readonly jans_stat]
      tags:
        - Statistics - User
  /jans-config-api/api/v1/health:
    get:
      summary: Returns application health status.
      description: Returns application health status.
      operationId: get-config-health
      tags:
        - Health - Check
  /jans-config-api/api/v1/health/live:
    get:
      summary: Returns application liveness status.
      description: Returns application liveness status.
      operationId: get-config-health-live
      tags:
        - Health - Check
  /jans-config-api/api/v1/health/ready:
    get:
      summary: Returns application readiness status.
      description: Returns application readiness status.
      operationId: get-config-health-ready
      tags:
        - Health - Check
  /jans-config-api/api/v1/health/server-stat:
    get:
      summary: Returns application server status.
      description: Returns application server status.
      operationId: get-server-stat
      tags:
        - Server Stats
  /jans-config-api/api/v1/jans-auth-server/session:
    get:
      summary: Returns current session.
      description: Returns current session.
      operationId: get-sessions
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/session.readonly]
      tags:
        - Auth - Session Management
  /jans-config-api/api/v1/jans-auth-server/session/{userDn}:
    post:
      summary: Revoke all sessions by userDn.
      description: Revoke all sessions by userDn.
      operationId: revoke-user-session
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/session.delete, revoke_session]
      tags:
        - Auth - Session Management
  /jans-config-api/mgt/configuser:
    get:
      tags:
        - Configuration – User Management
      summary: Gets list of users
      description: Gets list of users
      operationId: get-user
      security:
        - oauth2: [https://jans.io/oauth/config/user.readonly]
    post:
      tags:
        - Configuration – User Management
      summary: Create new User
      description: Create new User
      operationId: post-user
      security:
        - oauth2: [https://jans.io/oauth/config/user.write]
    put:
      tags:
        - Configuration – User Management
      summary: Update User.
      description: Update User.
      operationId: put-user
      security:
        - oauth2: [https://jans.io/oauth/config/user.write]
  /jans-config-api/mgt/configuser/{inum}:
    get:
      tags:
        - Configuration – User Management
      summary: Get User by Inum
      description: Get User by Inum.
      operationId: get-user-by-inum
      security:
        - oauth2: [https://jans.io/oauth/config/user.readonly]
    delete:
      tags:
        - Configuration – User Management
      summary: Delete User.
      description: Delete User.
      operationId: delete-user
      security:
        - oauth2: [https://jans.io/oauth/config/user.delete]
    patch:
      tags:
        - Configuration – User Management
      summary: Patch user properties by Inum.
      description: Patch user properties by Inum.
      operationId: patch-user-by-inum
      security:
        - oauth2: [https://jans.io/oauth/config/user.write]

 
  /jans-config-api/scim/scim-config:
    get:
      summary: Retrieves SCIM App configuration.
      description: Retrieves SCIM configuration.
      operationId: get-scim-config
      security:
        - oauth2: [https://jans.io/scim/config.readonly]
      tags:
        - SCIM - Config Management
      x-cli-plugin: scim
    patch:
      summary: Partially modifies SCIM App configuration.
      description: Partially modifies SCIM App configuration.
      operationId: patch-scim-config
      security:
        - oauth2: [https://jans.io/scim/config.write]
      tags:
        - SCIM - Config Management
      x-cli-plugin: scim
  /jans-config-api/api/v1/org:
    get:
      summary: Retrieves organization configuration.
      description: Retrieves organization configuration.
      operationId: get-organization-config
      security:
        - oauth2: [https://jans.io/oauth/config/organization.readonly]
      tags:
        - Organization Configuration
    patch:
      summary: Partially modifies organization configuration.
      description: Partially modifies organization configuration.
      operationId: patch-organization-config
      security:
        - oauth2: [https://jans.io/oauth/config/organization.write]
      tags:
        - Organization Configuration
  /jans-config-api/api/v1/jans-auth-server/health:
    get:
      summary: Returns auth server health status.
      description: Returns auth server health status.
      operationId: get-auth-server-health
      tags:
        - Auth Server Health - Check
  /jans-config-api/admin-ui/adminUIRoles:
    get:
      tags:
        - Admin UI - Role
      x-cli-plugin: admin-ui
      summary: Get all admin ui roles.
      description: Get all admin ui roles.
      operationId: get-adminui-roles
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/user/role.read]
    post:
      tags:
        - Admin UI - Role
      x-cli-plugin: admin-ui
      summary: Add admin ui role.
      description: Add admin ui role.
      operationId: add-adminui-role
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/user/role.write]
    put:
      tags:
        - Admin UI - Role
      x-cli-plugin: admin-ui
      summary: Edit admin ui role.
      description: Edit admin ui role.
      operationId: edit-adminui-role
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/user/role.write]
    delete:
      tags:
        - Admin UI - Role
      x-cli-plugin: admin-ui
      summary: Delete admin ui role.
      description: Delete admin ui role.
      operationId: delete-adminui-role
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/user/role.write]
  /jans-config-api/admin-ui/adminUIPermissions:
    get:
      tags:
        - Admin UI - Permission
      x-cli-plugin: admin-ui
      summary: Get admin ui permissions.
      description: Get admin ui permissions.
      operationId: get-adminui-permissions
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.read]
    post:
      tags:
        - Admin UI - Permission
      x-cli-plugin: admin-ui
      summary: Add admin ui permission.
      description: Add admin ui permission.
      operationId: add-adminui-permission
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.write]
    put:
      tags:
        - Admin UI - Permission
      x-cli-plugin: admin-ui
      summary: Edit admin ui permission.
      description: Edit admin ui permission.
      operationId: edit-adminui-permission
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.write]
    delete:
      tags:
        - Admin UI - Permission
      x-cli-plugin: admin-ui
      summary: Delete admin ui permission.
      description: Delete admin ui permission.
      operationId: delete-adminui-permission
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.write]
  /jans-config-api/admin-ui/adminUIRolePermissionsMapping:
    get:
      tags:
        - Admin UI - Role-Permissions Mapping
      x-cli-plugin: admin-ui
      summary: Get admin ui role-permissions mapping.
      description: Get admin ui role-permissions mapping.
      operationId: get-adminui-role-permissions
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.readonly]
    post:
      tags:
        - Admin UI - Role-Permissions Mapping
      x-cli-plugin: admin-ui
      summary: Add role-permissions mapping.
      description: Add role-permissions mapping.
      operationId: Add role-permissions mapping.
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.write]
    put:
      tags:
        - Admin UI - Role-Permissions Mapping
      x-cli-plugin: admin-ui
      summary: Map permissions to role.
      description: Map permissions to role.
      operationId: map-permissions-to-role
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.write]
    delete:
      tags:
        - Admin UI - Role-Permissions Mapping
      x-cli-plugin: admin-ui
      summary: Remove role-permissions mapping.
      description: Remove role-permissions mapping.
      operationId: remove-role-permissions-permission
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.write]
  /jans-config-api/admin-ui/license/isActive:
    get:
      tags:
        - Admin UI - License
      x-cli-plugin: admin-ui
      summary: Check if admin-ui license is active.
      description: Check if admin-ui license is active.
      operationId: is-license-active
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/license.readonly]
  /jans-config-api/admin-ui/license/activateLicense:
    post:
      tags:
        - Admin UI - License
      x-cli-plugin: admin-ui
      summary: Activate license using license-key.
      description: Activate license using license-key.
      operationId: activate-adminui-license
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/license.write]
  /jans-config-api/admin-ui/license/saveApiCredentials:
    post:
      tags:
        - Admin UI - License
      x-cli-plugin: admin-ui
      summary: Save license api credentials.
      description: Save license api credentials.
      operationId: save-license-api-credentials
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/license.write]
  /jans-config-api/admin-ui/license/licenseDetails:
    get:
      tags:
        - Admin UI - License
      x-cli-plugin: admin-ui
      summary: Get admin ui license details.
      description: Get admin ui license details.
      operationId: get-adminui-license
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/license.readonly]
    put:
      tags:
        - Admin UI - License
      x-cli-plugin: admin-ui
      summary: Edit admin ui license details.
      description: Edit admin ui license details.
      operationId: edit-adminui-license
      security:
        - oauth2: [https://jans.io/oauth/jans-auth-server/config/adminui/license.write]
components:
  securitySchemes:
    oauth2:
      type: oauth2
      description: Authorization
      flows:
        clientCredentials:
          tokenUrl: 'https://{op-hostname}/.../token'
          scopes:
            https://jans.io/oauth/jans-auth-server/config/properties.readonly: View Auth Server properties related information
            https://jans.io/oauth/jans-auth-server/config/properties.write: Manage Auth Server properties related information
            https://jans.io/oauth/config/fido2.readonly: View FIDO2 related information
            https://jans.io/oauth/config/fido2.write: Manage FIDO2 related information
            https://jans.io/oauth/config/attributes.readonly: View attribute related information
            https://jans.io/oauth/config/attributes.write: Manage attribute related information
            https://jans.io/oauth/config/attributes.delete: Delete attribute related information
            https://jans.io/oauth/config/acrs.readonly: View ACRS related information
            https://jans.io/oauth/config/acrs.write: Manage ACRS related information
            https://jans.io/oauth/config/database/ldap.readonly: View LDAP database related information
            https://jans.io/oauth/config/database/ldap.write: Manage LDAP database related information
            https://jans.io/oauth/config/database/ldap.delete: Delete LDAP database related information
            https://jans.io/oauth/config/scripts.readonly: View cache scripts information
            https://jans.io/oauth/config/scripts.write: Manage scripts related information
            https://jans.io/oauth/config/scripts.delete: Delete scripts related information
            https://jans.io/oauth/config/cache.readonly: View cache related information
            https://jans.io/oauth/config/cache.write: Manage cache related information
            https://jans.io/oauth/config/smtp.readonly: View SMTP related information
            https://jans.io/oauth/config/smtp.write: Manage SMTP related information
            https://jans.io/oauth/config/smtp.delete: Delete SMTP related information
            https://jans.io/oauth/config/logging.readonly: View logging related information
            https://jans.io/oauth/config/logging.write: Manage logging related information
            https://jans.io/oauth/config/jwks.readonly: View JWKS related information
            https://jans.io/oauth/config/jwks.write: Manage JWKS related information
            https://jans.io/oauth/config/jwks.delete: Delete JWKS related information
            https://jans.io/oauth/config/openid/clients.readonly: View clients related information
            https://jans.io/oauth/config/openid/clients.write: Manage clients related information
            https://jans.io/oauth/config/openid/clients.delete: Delete clients related information
            https://jans.io/oauth/config/scopes.readonly: View scope related information
            https://jans.io/oauth/config/scopes.write: Manage scope related information
            https://jans.io/oauth/config/scopes.delete: Delete scope related information
            https://jans.io/oauth/config/uma/resources.readonly: View UMA Resource related information
            https://jans.io/oauth/config/uma/resources.write: Manage UMA Resource related information
            https://jans.io/oauth/config/uma/resources.delete: Delete UMA Resource related information
            https://jans.io/oauth/config/stats.readonly: Vew server with basic statistic
            https://jans.io/oauth/config/scim/users.read: Vew scim user related information
            https://jans.io/oauth/config/scim/users.write: Manage scim user related information
            https://jans.io/scim/config.readonly: Vew SCIM App configuration
            https://jans.io/scim/config.write: Manage SCIM App configuration
            https://jans.io/oauth/config/organization.readonly: View organization configuration information
            https://jans.io/oauth/config/organization.write: Manage organization configuration information
            https://jans.io/oauth/config/user.readonly: View user related information
            https://jans.io/oauth/config/user.write: Manage user related information
            https://jans.io/oauth/config/user.delete: Delete user related information
            https://jans.io/oauth/config/agama.readonly: View Agama Flow related information
            https://jans.io/oauth/config/agama.write: Manage Agama Flow related information
            https://jans.io/oauth/config/agama.delete: Delete Agama Flow related information
            https://jans.io/oauth/jans-auth-server/session.readonly: View Session related information
            https://jans.io/oauth/jans-auth-server/session.delete: Delete Session information
