openapi: 3.0.1
info:
  title: Jans Config API
  contact:
    name: Gluu Support
    url: https://support.gluu.org
    email: xxx@gluu.org
  license:
    name: Apache 2.0
    url: https://github.com/JanssenProject/jans/blob/main/LICENSE
  version: 1.0.0
servers:
- url: https://jans.io/
  description: The Jans server
  variables: {}
tags:
- name: Attribute
- name: Default Authentication Method
- name: Cache Configuration
- name: Cache Configuration – Memcached
- name: Cache Configuration – Redis
- name: Cache Configuration – in-Memory
- name: Cache Configuration – Native-Persistence
- name: Configuration – Properties
- name: Configuration – SMTP
- name: Configuration – Logging
- name: Configuration – JWK - JSON Web Key (JWK)
- name: Custom Scripts
- name: Database - LDAP configuration
- name: OAuth - OpenID Connect - Clients
- name: OAuth - UMA Resources
- name: OAuth - Scopes
- name: Agama - Configuration
- name: Agama - Developer Studio
- name: Statistics - User
- name: Health - Check
- name: Server Stats
- name: Auth - Session Management
- name: Organization Configuration
- name: Auth Server Health - Check
- name: Plugins
- name: Configuration – Config API
paths:
  /api/v1/health:
    get:
      tags:
      - Health - Check
      summary: Returns application health status
      description: Returns application health status
      operationId: get-config-health
  /api/v1/health/live:
    get:
      tags:
      - Health - Check
      summary: Returns application liveness status
      description: Returns application liveness status
      operationId: get-config-health-live
  /api/v1/health/ready:
    get:
      tags:
      - Health - Check
      summary: Returns application readiness status
      description: Returns application readiness status
      operationId: get-config-health-ready
  /api/v1/health/server-stat:
    get:
      tags:
      - Health - Check
      summary: Returns application server status
      description: Returns application server status
      operationId: get-server-stat
  /api/v1/ads-deployment:
    get:
      tags:
      - Agama - Developer Studio
      summary: Fetches deployed Agama project based on name.
      description: Fetches deployed Agama project based on name.
      operationId: get-agama-dev-studio-prj-by-name
      security:
      - oauth2:
        - https://jans.io/oauth/config/agama.readonly
        - https://jans.io/oauth/config/agama.write
        - https://jans.io/oauth/config/read-all
    post:
      tags:
      - Agama - Developer Studio
      summary: Deploy an Agama project.
      description: Deploy an Agama project.
      operationId: post-agama-dev-studio-prj
      security:
      - oauth2:
        - https://jans.io/oauth/config/agama.write
        - https://jans.io/oauth/config/write-all
    delete:
      tags:
      - Agama - Developer Studio
      summary: Delete a deployed Agama project.
      description: Delete a deployed Agama project.
      operationId: delete-agama-dev-studio-prj
      security:
      - oauth2:
        - https://jans.io/oauth/config/agama.delete
  /api/v1/ads-deployment/list:
    get:
      tags:
      - Agama - Developer Studio
      summary: Retrieve the list of projects deployed currently.
      description: Retrieve the list of projects deployed currently.
      operationId: get-agama-dev-prj
      security:
      - oauth2:
        - https://jans.io/oauth/config/agama.readonly
        - https://jans.io/oauth/config/agama.write
        - https://jans.io/oauth/config/read-all
  /api/v1/acrs:
    get:
      tags:
      - Default Authentication Method
      summary: Gets default authentication method.
      description: Gets default authentication method.
      operationId: get-acrs
      security:
      - oauth2:
        - https://jans.io/oauth/config/acrs.readonly
        - https://jans.io/oauth/config/acrs.write
        - https://jans.io/oauth/config/read-all
    put:
      tags:
      - Default Authentication Method
      summary: Updates default authentication method.
      description: Updates default authentication method.
      operationId: put-acrs
      security:
      - oauth2:
        - https://jans.io/oauth/config/acrs.write
        - https://jans.io/oauth/config/write-all
  /api/v1/agama:
    get:
      tags:
      - Agama - Configuration
      summary: Fetches all agama flow.
      description: Fetches all agama flow.
      operationId: get-agama-flows
      security:
      - oauth2:
        - https://jans.io/oauth/config/agama.readonly
        - https://jans.io/oauth/config/agama.write
        - https://jans.io/oauth/config/read-all
    post:
      tags:
      - Agama - Configuration
      summary: Create a new agama flow
      description: Create a new agama flow
      operationId: post-agama-flow
      security:
      - oauth2:
        - https://jans.io/oauth/config/agama.write
  /api/v1/agama/{qname}:
    get:
      tags:
      - Agama - Configuration
      summary: Gets an agama flow based on Qname.
      description: Gets an agama flow based on Qname.
      operationId: get-agama-flow
      security:
      - oauth2:
        - https://jans.io/oauth/config/agama.readonly
        - https://jans.io/oauth/config/agama.write
        - https://jans.io/oauth/config/read-all
    post:
      tags:
      - Agama - Configuration
      summary: Create a new agama flow from source
      description: Create a new agama flow from source.
      operationId: post-agama-flow-from-source
      security:
      - oauth2:
        - https://jans.io/oauth/config/agama.write
    delete:
      tags:
      - Agama - Configuration
      summary: Deletes an agama flow based on Qname
      description: Deletes an agama flow based on Qname
      operationId: delete-agama-flow
      security:
      - oauth2:
        - https://jans.io/oauth/config/agama.delete
    patch:
      tags:
      - Agama - Configuration
      summary: Partially modify a Agama Flow
      description: Partially modify a Agama Flow
      operationId: patch-agama-flow
      security:
      - oauth2:
        - https://jans.io/oauth/config/agama.write
  /api/v1/agama/syntax-check/{qname}:
    post:
      tags:
      - Agama - Configuration
      summary: Determine if the text passed is valid Agama code
      description: Determine if the text passed is valid Agama code
      operationId: agama-syntax-check
      security:
      - oauth2:
        - https://jans.io/oauth/config/agama.readonly
        - https://jans.io/oauth/config/agama.write
        - https://jans.io/oauth/config/read-all
  /api/v1/agama/source/{qname}:
    put:
      tags:
      - Agama - Configuration
      summary: Update agama flow from source file
      description: Update agama flow from source file.
      operationId: put-agama-flow-from-source
      security:
      - oauth2:
        - https://jans.io/oauth/config/agama.write
  /api/v1/attributes:
    get:
      tags:
      - Attribute
      summary: Gets a list of Gluu attributes.
      description: Gets a list of Gluu attributes.
      operationId: get-attributes
      security:
      - oauth2:
        - https://jans.io/oauth/config/attributes.readonly
    put:
      tags:
      - Attribute
      summary: Updates an existing attribute
      description: Updates an existing attribute
      operationId: put-attributes
      security:
      - oauth2:
        - https://jans.io/oauth/config/attributes.write
    post:
      tags:
      - Attribute
      summary: Adds a new attribute
      description: Adds a new attribute
      operationId: post-attributes
      security:
      - oauth2:
        - https://jans.io/oauth/config/attributes.write
  /api/v1/attributes/{inum}:
    get:
      tags:
      - Attribute
      summary: Gets an attribute based on inum
      description: Gets an attribute based on inum
      operationId: get-attributes-by-inum
      security:
      - oauth2:
        - https://jans.io/oauth/config/attributes.readonly
    delete:
      tags:
      - Attribute
      summary: Deletes an attribute based on inum
      description: Deletes an attribute based on inum
      operationId: delete-attributes-by-inum
      security:
      - oauth2:
        - https://jans.io/oauth/config/attributes.delete
    patch:
      tags:
      - Attribute
      summary: Partially modify a GluuAttribute
      description: Partially modify a GluuAttribute
      operationId: patch-attributes-by-inum
      security:
      - oauth2:
        - https://jans.io/oauth/config/attributes.write
  /api/v1/jans-auth-server/config:
    get:
      tags:
      - Configuration – Properties
      summary: Gets all Jans authorization server configuration properties.
      description: Gets all Jans authorization server configuration properties.
      operationId: get-properties
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/properties.readonly
    patch:
      tags:
      - Configuration – Properties
      summary: Partially modifies Jans authorization server Application configuration
        properties.
      description: Partially modifies Jans authorization server AppConfiguration properties.
      operationId: patch-properties
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/properties.write
  /api/v1/jans-auth-server/config/persistence:
    get:
      tags:
      - Configuration – Properties
      summary: Returns persistence type configured for Jans authorization server.
      description: Returns persistence type configured for Jans authorization server.
      operationId: get-properties-persistence
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/properties.readonly
  /api/v1/config/cache:
    get:
      tags:
      - Cache Configuration
      summary: Returns cache configuration.
      description: Returns cache configuration.
      operationId: get-config-cache
      security:
      - oauth2:
        - https://jans.io/oauth/config/cache.readonly
    patch:
      tags:
      - Cache Configuration
      summary: Patch cache configuration.
      description: Patch cache configuration
      operationId: patch-config-cache
      security:
      - oauth2:
        - https://jans.io/oauth/config/cache.write
  /api/v1/config/cache/in-memory:
    get:
      tags:
      - Cache Configuration – in-Memory
      summary: Returns in-Memory cache configuration.
      description: Returns in-Memory cache configuration.
      operationId: get-config-cache-in-memory
      security:
      - oauth2:
        - https://jans.io/oauth/config/cache.readonly
    put:
      tags:
      - Cache Configuration – in-Memory
      summary: Updates in-Memory cache configuration.
      description: Updates in-Memory cache configuration
      operationId: put-config-cache-in-memory
      security:
      - oauth2:
        - https://jans.io/oauth/config/cache.write
    patch:
      tags:
      - Cache Configuration – in-Memory
      summary: Patch In-Memory cache configuration.
      description: Patch In-Memory cache configuration
      operationId: patch-config-cache-in-memory
      security:
      - oauth2:
        - https://jans.io/oauth/config/cache.write
  /api/v1/config/cache/memcached:
    get:
      tags:
      - Cache Configuration – Memcached
      summary: Returns memcached cache configuration.
      description: Returns memcached cache configuration.
      operationId: get-config-cache-memcached
      security:
      - oauth2:
        - https://jans.io/oauth/config/cache.readonly
    put:
      tags:
      - Cache Configuration – Memcached
      summary: Updates memcached cache configuration.
      description: Updates memcached cache configuration
      operationId: put-config-cache-memcached
      security:
      - oauth2:
        - https://jans.io/oauth/config/cache.write
    patch:
      tags:
      - Cache Configuration – Memcached
      summary: Patch memcached cache configuration.
      description: Patch memcached cache configuration
      operationId: patch-config-cache-memcached
      security:
      - oauth2:
        - https://jans.io/oauth/config/cache.write
  /api/v1/config/cache/native-persistence:
    get:
      tags:
      - Cache Configuration – Native-Persistence
      summary: Returns native persistence cache configuration.
      description: Returns native persistence cache configuration.
      operationId: get-config-cache-native-persistence
      security:
      - oauth2:
        - https://jans.io/oauth/config/cache.readonly
    put:
      tags:
      - Cache Configuration – Native-Persistence
      summary: Updates native persistence cache configuration.
      description: Updates native persistence cache configuration
      operationId: put-config-cache-native-persistence
      security:
      - oauth2:
        - https://jans.io/oauth/config/cache.write
    patch:
      tags:
      - Cache Configuration – Native-Persistence
      summary: Patch native persistence cache configuration.
      description: Patch native persistence cache configuration
      operationId: patch-config-cache-native-persistence
      security:
      - oauth2:
        - https://jans.io/oauth/config/cache.write
  /api/v1/config/cache/redis:
    get:
      tags:
      - Cache Configuration – Redis
      summary: Returns Redis cache configuration.
      description: Returns Redis cache configuration
      operationId: get-config-cache-redis
      security:
      - oauth2:
        - https://jans.io/oauth/config/cache.readonly
    put:
      tags:
      - Cache Configuration – Redis
      summary: Updates Redis cache configuration.
      description: Updates Redis cache configuration
      operationId: put-config-cache-redis
      security:
      - oauth2:
        - https://jans.io/oauth/config/cache.write
    patch:
      tags:
      - Cache Configuration – Redis
      summary: Patch Redis cache configuration.
      description: Patch Redis cache configuration
      operationId: patch-config-cache-redis
      security:
      - oauth2:
        - https://jans.io/oauth/config/cache.write
  /api/v1/openid/clients:
    get:
      tags:
      - OAuth - OpenID Connect - Clients
      summary: Gets list of OpenID Connect clients
      description: Gets list of OpenID Connect clients
      operationId: get-oauth-openid-clients
      security:
      - oauth2:
        - https://jans.io/oauth/config/openid/clients.readonly
    put:
      tags:
      - OAuth - OpenID Connect - Clients
      summary: Update OpenId Connect client
      description: Update OpenId Connect client
      operationId: put-oauth-openid-client
      security:
      - oauth2:
        - https://jans.io/oauth/config/openid/clients.write
    post:
      tags:
      - OAuth - OpenID Connect - Clients
      summary: Create new OpenId Connect client
      description: Create new OpenId Connect client
      operationId: post-oauth-openid-client
      security:
      - oauth2:
        - https://jans.io/oauth/config/openid/clients.write
  /api/v1/openid/clients/{inum}:
    get:
      tags:
      - OAuth - OpenID Connect - Clients
      summary: Get OpenId Connect Client by Inum
      description: Get OpenId Connect Client by Inum
      operationId: get-oauth-openid-clients-by-inum
      security:
      - oauth2:
        - https://jans.io/oauth/config/openid/clients.readonly
    delete:
      tags:
      - OAuth - OpenID Connect - Clients
      summary: Delete OpenId Connect client
      description: Delete OpenId Connect client
      operationId: delete-oauth-openid-client-by-inum
      security:
      - oauth2:
        - https://jans.io/oauth/config/openid/clients.delete
    patch:
      tags:
      - OAuth - OpenID Connect - Clients
      summary: Patch OpenId Connect client
      description: Patch OpenId Connect client
      operationId: patch-oauth-openid-client-by-inum
      security:
      - oauth2:
        - https://jans.io/oauth/config/openid/clients.write
  /api/v1/api-config:
    get:
      tags:
      - Configuration – Config API
      summary: Gets config-api configuration properties.
      description: Gets config-api configuration properties.
      operationId: get-config-api-properties
      security:
      - oauth2:
        - https://jans.io/oauth/config/properties.readonly
    patch:
      tags:
      - Configuration – Config API
      summary: Partially modifies config-api configuration properties.
      description: Partially modifies config-api Configuration properties.
      operationId: patch-config-api-properties
      security:
      - oauth2:
        - https://jans.io/oauth/config/properties.write
  /api/v1/config/smtp:
    get:
      tags:
      - Configuration – SMTP
      summary: Returns SMTP server configuration
      description: Returns SMTP server configuration
      operationId: get-config-smtp
      security:
      - oauth2:
        - https://jans.io/oauth/config/smtp.readonly
    put:
      tags:
      - Configuration – SMTP
      summary: Updates SMTP server configuration
      description: Updates SMTP server configuration
      operationId: put-config-smtp
      security:
      - oauth2:
        - https://jans.io/oauth/config/smtp.write
    post:
      tags:
      - Configuration – SMTP
      summary: Adds SMTP server configuration
      description: Adds SMTP server configuration
      operationId: post-config-smtp
      security:
      - oauth2:
        - https://jans.io/oauth/config/smtp.write
    delete:
      tags:
      - Configuration – SMTP
      summary: Deletes SMTP server configuration
      description: Deletes SMTP server configuration
      operationId: delete-config-smtp
      security:
      - oauth2:
        - https://jans.io/oauth/config/smtp.delete
  /api/v1/config/smtp/test:
    post:
      tags:
      - Configuration – SMTP
      summary: Test SMTP server configuration
      description: Test SMTP server configuration
      operationId: test-config-smtp
      security:
      - oauth2:
        - https://jans.io/oauth/config/smtp.readonly
  /api/v1/config/scripts:
    get:
      tags:
      - Custom Scripts
      summary: Fetch custom script by name
      description: Gets a list of custom scripts
      operationId: get-config-scripts
      security:
      - oauth2:
        - https://jans.io/oauth/config/scripts.readonly
    put:
      tags:
      - Custom Scripts
      summary: Updates a custom script
      description: Updates a custom script
      operationId: put-config-scripts
      security:
      - oauth2:
        - https://jans.io/oauth/config/scripts.write
    post:
      tags:
      - Custom Scripts
      summary: Adds a new custom script
      description: Adds a new custom script
      operationId: post-config-scripts
      security:
      - oauth2:
        - https://jans.io/oauth/config/scripts.write
  /api/v1/config/scripts/{inum}:
    delete:
      tags:
      - Custom Scripts
      summary: Deletes a custom script
      description: Deletes a custom script
      operationId: delete-config-scripts-by-inum
      security:
      - oauth2:
        - https://jans.io/oauth/config/scripts.delete
    patch:
      tags:
      - Custom Scripts
      summary: Patches a custom script
      description: Patches a custom script
      operationId: patch-config-scripts-by-inum
      security:
      - oauth2:
        - https://jans.io/oauth/config/scripts.write
  /api/v1/config/scripts/inum/{inum}:
    get:
      tags:
      - Custom Scripts
      summary: Gets a script by Inum
      description: Gets a script by Inum
      operationId: get-config-scripts-by-inum
      security:
      - oauth2:
        - https://jans.io/oauth/config/scripts.readonly
  /api/v1/config/scripts/name/{name}:
    get:
      tags:
      - Custom Scripts
      summary: Fetch custom script by name
      description: Fetch custom script by name
      operationId: get-custom-script-by-name
      security:
      - oauth2:
        - https://jans.io/oauth/config/scripts.readonly
  /api/v1/config/scripts/type/{type}:
    get:
      tags:
      - Custom Scripts
      summary: Gets list of scripts by type
      description: Gets list of scripts by type
      operationId: get-config-scripts-by-type
      security:
      - oauth2:
        - https://jans.io/oauth/config/scripts.readonly
  /api/v1/jans-auth-server/health:
    get:
      tags:
      - Auth Server Health - Check
      summary: Returns auth server health status
      description: Returns auth server health status
      operationId: get-auth-server-health
  /api/v1/config/jwks/{kid}:
    get:
      tags:
      - Configuration – JWK - JSON Web Key (JWK)
      summary: Get a JSON Web Key based on kid
      description: Get a JSON Web Key based on kid
      operationId: get-jwk-by-kid
      security:
      - oauth2:
        - https://jans.io/oauth/config/jwks.readonly
    delete:
      tags:
      - Configuration – JWK - JSON Web Key (JWK)
      summary: Delete a JSON Web Key based on kid
      description: Delete a JSON Web Key based on kid
      operationId: delete-config-jwk-kid
      security:
      - oauth2:
        - https://jans.io/oauth/config/jwks.delete
    patch:
      tags:
      - Configuration – JWK - JSON Web Key (JWK)
      summary: Patch a specific JSON Web Key based on kid
      description: Patch a specific JSON Web Key based on kid
      operationId: patch-config-jwk-kid
      security:
      - oauth2:
        - https://jans.io/oauth/config/jwks.write
  /api/v1/config/jwks:
    get:
      tags:
      - Configuration – JWK - JSON Web Key (JWK)
      summary: Gets list of JSON Web Key (JWK) used by server
      description: Gets list of JSON Web Key (JWK) used by server
      operationId: get-config-jwks
      security:
      - oauth2:
        - https://jans.io/oauth/config/jwks.readonly
    put:
      tags:
      - Configuration – JWK - JSON Web Key (JWK)
      summary: Replaces JSON Web Keys
      description: Replaces JSON Web Keys
      operationId: put-config-jwks
      security:
      - oauth2:
        - https://jans.io/oauth/config/jwks.write
    patch:
      tags:
      - Configuration – JWK - JSON Web Key (JWK)
      summary: Patches JSON Web Keys
      description: Patches JSON Web Keys
      operationId: patch-config-jwks
      security:
      - oauth2:
        - https://jans.io/oauth/config/jwks.write
  /api/v1/config/jwks/key:
    post:
      tags:
      - Configuration – JWK - JSON Web Key (JWK)
      summary: Configuration – JWK - JSON Web Key (JWK)
      description: Configuration – JWK - JSON Web Key (JWK)
      operationId: post-config-jwks-key
      security:
      - oauth2:
        - https://jans.io/oauth/config/jwks.write
  /api/v1/config/database/ldap:
    get:
      tags:
      - Database - LDAP configuration
      summary: Gets list of existing LDAP configurations.
      description: Gets list of existing LDAP configurations.
      operationId: get-config-database-ldap
      security:
      - oauth2:
        - https://jans.io/oauth/config/database/ldap.readonly
    put:
      tags:
      - Database - LDAP configuration
      summary: Updates LDAP configuration
      description: Updates LDAP configuration
      operationId: put-config-database-ldap
      security:
      - oauth2:
        - https://jans.io/oauth/config/database/ldap.write
    post:
      tags:
      - Database - LDAP configuration
      summary: Adds a new LDAP configuration
      description: Adds a new LDAP configuration
      operationId: post-config-database-ldap
      security:
      - oauth2:
        - https://jans.io/oauth/config/database/ldap.write
  /api/v1/config/database/ldap/{name}:
    get:
      tags:
      - Database - LDAP configuration
      summary: Gets an LDAP configuration by name.
      description: Gets an LDAP configuration by name.
      operationId: get-config-database-ldap-by-name
      security:
      - oauth2:
        - https://jans.io/oauth/config/database/ldap.readonly
    delete:
      tags:
      - Database - LDAP configuration
      summary: Deletes an LDAP configuration
      description: Deletes an LDAP configuration
      operationId: delete-config-database-ldap-by-name
      security:
      - oauth2:
        - https://jans.io/oauth/config/database/ldap.delete
    patch:
      tags:
      - Database - LDAP configuration
      summary: Patches a LDAP configuration by name
      description: Patches a LDAP configuration by name
      operationId: patch-config-database-ldap-by-name
      security:
      - oauth2:
        - https://jans.io/oauth/config/database/ldap.write
  /api/v1/config/database/ldap/test:
    post:
      tags:
      - Database - LDAP configuration
      summary: Tests an LDAP configuration
      description: Tests an LDAP configuration
      operationId: post-config-database-ldap-test
      security:
      - oauth2:
        - https://jans.io/oauth/config/database/ldap.readonly
  /api/v1/logging:
    get:
      tags:
      - Configuration – Logging
      summary: Returns Jans Authorization Server logging settings
      description: Returns Jans Authorization Server logging settings
      operationId: get-config-logging
      security:
      - oauth2:
        - https://jans.io/oauth/config/logging.readonly
    put:
      tags:
      - Configuration – Logging
      summary: Updates Jans Authorization Server logging settings
      description: Updates Jans Authorization Server logging settings
      operationId: put-config-logging
      security:
      - oauth2:
        - https://jans.io/oauth/config/logging.write
  /api/v1/org:
    get:
      tags:
      - Organization Configuration
      summary: Retrieves organization configuration
      description: Retrieves organization configuration
      operationId: get-organization-config
      security:
      - oauth2:
        - https://jans.io/oauth/config/organization.readonly
    patch:
      tags:
      - Organization Configuration
      summary: Patch organization configuration
      description: Patch organization configuration
      operationId: patch-organization-config
      security:
      - oauth2:
        - https://jans.io/oauth/config/organization.write
  /api/v1/plugin:
    get:
      tags:
      - Plugins
      summary: Gets list of Plugins
      description: Gets list of Plugins
      operationId: get-plugins
      security:
      - oauth2:
        - https://jans.io/oauth/config/plugin.readonly
  /api/v1/plugin/{pluginName}:
    get:
      tags:
      - Plugins
      summary: Get plugin by name
      description: Get plugin by name
      operationId: get-plugin-by-name
      security:
      - oauth2:
        - https://jans.io/oauth/config/plugin.readonly
  /api/v1/scopes:
    get:
      tags:
      - OAuth - Scopes
      summary: Gets list of Scopes
      description: Gets list of Scopes
      operationId: get-oauth-scopes
      security:
      - oauth2:
        - https://jans.io/oauth/config/scopes.readonly
    put:
      tags:
      - OAuth - Scopes
      summary: Update Scope
      description: Update Scope
      operationId: put-oauth-scopes
      security:
      - oauth2:
        - https://jans.io/oauth/config/scopes.write
    post:
      tags:
      - OAuth - Scopes
      summary: Create Scope
      description: Create Scope
      operationId: post-oauth-scopes
      security:
      - oauth2:
        - https://jans.io/oauth/config/scopes.write
  /api/v1/scopes/{inum}:
    get:
      tags:
      - OAuth - Scopes
      summary: Get Scope by Inum
      description: Get Scope by Inum
      operationId: get-oauth-scopes-by-inum
      security:
      - oauth2:
        - https://jans.io/oauth/config/scopes.readonly
    delete:
      tags:
      - OAuth - Scopes
      summary: Delete Scope
      description: Delete Scope
      operationId: delete-oauth-scopes-by-inum
      security:
      - oauth2:
        - https://jans.io/oauth/config/scopes.delete
    patch:
      tags:
      - OAuth - Scopes
      summary: Patch Scope
      description: Patch Scope
      operationId: patch-oauth-scopes-by-id
      security:
      - oauth2:
        - https://jans.io/oauth/config/scopes.write
  /api/v1/scopes/creator/{creatorId}:
    get:
      tags:
      - OAuth - Scopes
      summary: Get Scope by creatorId
      description: Get Scope by creatorId
      operationId: get-scope-by-creator
      security:
      - oauth2:
        - https://jans.io/oauth/config/scopes.readonly
  /api/v1/scopes/type/{type}:
    get:
      tags:
      - OAuth - Scopes
      summary: Get Scope by type
      description: Get Scope by type
      operationId: get-scope-by-type
      security:
      - oauth2:
        - https://jans.io/oauth/config/scopes.readonly
  /api/v1/jans-auth-server/session:
    get:
      tags:
      - Auth - Session Management
      summary: Returns current session
      description: Returns current session
      operationId: get-sessions
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/session.readonly
        - revoke_session
  /api/v1/jans-auth-server/session/{userDn}:
    post:
      tags:
      - Auth - Session Management
      summary: Revoke all sessions by userDn
      description: Revoke all sessions by userDn
      operationId: revoke-user-session
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/session.delete
        - revoke_session
  /api/v1/stat:
    get:
      tags:
      - Statistics - User
      summary: Provides server with basic statistic
      description: Provides server with basic statistic
      operationId: get-stat
      security:
      - oauth2:
        - https://jans.io/oauth/config/stats.readonly
        - jans_stat
  /api/v1/uma/resources:
    get:
      tags:
      - OAuth - UMA Resources
      summary: Gets list of UMA resources
      description: Gets list of UMA resources
      operationId: get-oauth-uma-resources
      security:
      - oauth2:
        - https://jans.io/oauth/config/uma/resources.readonly
    put:
      tags:
      - OAuth - UMA Resources
      summary: Updates an UMA resource
      description: Updates an UMA resource
      operationId: put-oauth-uma-resources
      security:
      - oauth2:
        - https://jans.io/oauth/config/uma/resources.write
    post:
      tags:
      - OAuth - UMA Resources
      summary: Creates an UMA resource
      description: Creates an UMA resource
      operationId: post-oauth-uma-resources
      security:
      - oauth2:
        - https://jans.io/oauth/config/uma/resources.write
  /api/v1/uma/resources/{id}:
    get:
      tags:
      - OAuth - UMA Resources
      summary: Gets an UMA resource by ID
      description: Gets an UMA resource by ID
      operationId: get-oauth-uma-resources-by-id
      security:
      - oauth2:
        - https://jans.io/oauth/config/uma/resources.readonly
    delete:
      tags:
      - OAuth - UMA Resources
      summary: Deletes an UMA resource
      description: Deletes an UMA resource
      operationId: delete-oauth-uma-resources-by-id
      security:
      - oauth2:
        - https://jans.io/oauth/config/uma/resources.delete
    patch:
      tags:
      - OAuth - UMA Resources
      summary: Patch UMA resource
      description: Patch UMA resource
      operationId: patch-oauth-uma-resources-by-id
      security:
      - oauth2:
        - https://jans.io/oauth/config/uma/resources.write
  /api/v1/uma/resources/clientId/{clientId}:
    get:
      tags:
      - OAuth - UMA Resources
      summary: Fetch uma resources by client id
      description: Fetch uma resources by client id
      operationId: get-oauth-uma-resources-by-clientid
      security:
      - oauth2:
        - https://jans.io/oauth/config/uma/resources.readonly
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://{op-hostname}/.../token"
          scopes:
            https://jans.io/oauth/jans-auth-server/config/properties.readonly: View
              Auth Server properties related information
            https://jans.io/oauth/jans-auth-server/config/properties.write: Manage
              Auth Server properties related information
            https://jans.io/oauth/config/attributes.readonly: View attribute related
              information
            https://jans.io/oauth/config/attributes.write: Manage attribute related
              information
            https://jans.io/oauth/config/attributes.delete: Delete attribute related
              information
            https://jans.io/oauth/config/acrs.readonly: View ACRS related information
            https://jans.io/oauth/config/acrs.write: Manage ACRS related information
            https://jans.io/oauth/config/database/ldap.readonly: View LDAP database
              related information
            https://jans.io/oauth/config/database/ldap.write: Manage LDAP database
              related information
            https://jans.io/oauth/config/database/ldap.delete: Delete LDAP database
              related information
            https://jans.io/oauth/config/scripts.readonly: View cache scripts information
            https://jans.io/oauth/config/scripts.write: Manage scripts related information
            https://jans.io/oauth/config/scripts.delete: Delete scripts related information
            https://jans.io/oauth/config/cache.readonly: View cache related information
            https://jans.io/oauth/config/cache.write: Manage cache related information
            https://jans.io/oauth/config/smtp.readonly: View SMTP related information
            https://jans.io/oauth/config/smtp.write: Manage SMTP related information
            https://jans.io/oauth/config/smtp.delete: Delete SMTP related information
            https://jans.io/oauth/config/logging.readonly: View logging related information
            https://jans.io/oauth/config/logging.write: Manage logging related information
            https://jans.io/oauth/config/jwks.readonly: View JWKS related information
            https://jans.io/oauth/config/jwks.write: Manage JWKS related information
            https://jans.io/oauth/config/jwks.delete: Delete JWKS related information
            https://jans.io/oauth/config/openid/clients.readonly: View clients related
              information
            https://jans.io/oauth/config/openid/clients.write: Manage clients related
              information
            https://jans.io/oauth/config/openid/clients.delete: Delete clients related
              information
            https://jans.io/oauth/config/scopes.readonly: View scope related information
            https://jans.io/oauth/config/scopes.write: Manage scope related information
            https://jans.io/oauth/config/scopes.delete: Delete scope related information
            https://jans.io/oauth/config/uma/resources.readonly: View UMA Resource
              related information
            https://jans.io/oauth/config/uma/resources.write: Manage UMA Resource
              related information
            https://jans.io/oauth/config/uma/resources.delete: Delete UMA Resource
              related information
            https://jans.io/oauth/config/stats.readonly: View server with basic statistic
            https://jans.io/oauth/config/organization.readonly: View organization
              configuration information
            https://jans.io/oauth/config/organization.write: Manage organization configuration
              information
            https://jans.io/oauth/config/agama.readonly: View Agama Flow related information
            https://jans.io/oauth/config/agama.write: Manage Agama Flow related information
            https://jans.io/oauth/config/agama.delete: Delete Agama Flow related information
            https://jans.io/oauth/jans-auth-server/session.readonly: View Session
              related information
            https://jans.io/oauth/jans-auth-server/session.delete: Delete Session
              information
            https://jans.io/oauth/config/read-all: Admin read scope
            https://jans.io/oauth/config/write-all: Admin write scope
            https://jans.io/oauth/config/delete-all: Admin delete scope
            https://jans.io/oauth/config/openid-read: View OpenID functionality
            https://jans.io/oauth/config/openid/openid-write: Manage OpenID functionality
            https://jans.io/oauth/config/openid/openid-delete: Delete OpenID functionality
            https://jans.io/oauth/config/uma-read: View UMA functionality
            https://jans.io/oauth/config/uma-write: Manage UMA functionality
            https://jans.io/oauth/config/uma-delete: Delete UMA functionality
            https://jans.io/oauth/config/plugin.readonly: View Plugin information
            https://jans.io/oauth/config/properties.readonly: View Config-API related
              configuration properties
            https://jans.io/oauth/config/properties.write: Manage Config-API related
              configuration properties
