openapi: 3.0.1
info:
  title: Jans Config API - Identity Broker
  contact:
    name: Gluu Support
    url: https://support.gluu.org
    email: xxx@gluu.org
  license:
    name: Apache 2.0
    url: https://github.com/JanssenProject/jans/blob/main/LICENSE
  version: 1.0.0
servers:
- url: https://jans.io/
  description: The Jans server
  variables: {}
tags:
- name: Jans - SAML IDP Configuration
- name: Jans - SAML Identity Broker
- name: Jans - SAML Identity Broker Realm
paths:
  /idp/idp-config:
    get:
      tags:
      - Jans - SAML IDP Configuration
      summary: Gets IDP configuration properties
      description: Gets IDP configuration properties
      operationId: get-idp-config-properties
      security:
      - oauth2:
        - https://jans.io/idp/config.readonly
    put:
      tags:
      - Jans - SAML IDP Configuration
      summary: Update IDP configuration properties
      description: Update IDP configuration properties
      operationId: put-idp-properties
      security:
      - oauth2:
        - https://jans.io/idp/config.write
    patch:
      tags:
      - Jans - SAML IDP Configuration
      summary: Partially modifies IDP configuration properties.
      description: Partially modifies IDP Configuration properties.
      operationId: patch-idp-properties
      security:
      - oauth2:
        - https://jans.io/idp/config.write
  /idp/realm:
    get:
      tags:
      - Jans - SAML Identity Broker Realm
      summary: Get all realm
      description: Get all realm
      operationId: get-realm
      security:
      - oauth2:
        - https://jans.io/idp/realm.readonly
    put:
      tags:
      - Jans - SAML Identity Broker Realm
      summary: Update realm
      description: Update realm
      operationId: put-realm
      security:
      - oauth2:
        - https://jans.io/idp/realm.write
    post:
      tags:
      - Jans - SAML Identity Broker Realm
      summary: Create realm
      description: Create realm
      operationId: post-realm
      security:
      - oauth2:
        - https://jans.io/idp/realm.write
  /idp/realm/{name}:
    delete:
      tags:
      - Jans - SAML Identity Broker Realm
      summary: 'Delete realm '
      description: Delete realm
      operationId: delete-realm
      security:
      - oauth2:
        - https://jans.io/idp/realm.write
  /idp/realm/name/{name}:
    get:
      tags:
      - Jans - SAML Identity Broker Realm
      summary: Get realm by name
      description: Get realm by name
      operationId: get-realm-by-name
      security:
      - oauth2:
        - https://jans.io/idp/realm.readonly
  /idp/kc/saml/upload:
    put:
      tags:
      - Jans - SAML Identity Broker
      summary: Update SAML Identity Provider
      description: Update SAML Identity Provider
      operationId: put-saml-identity-provider
      security:
      - oauth2:
        - https://jans.io/idp/saml.write
    post:
      tags:
      - Jans - SAML Identity Broker
      summary: Create SAML Identity Provider
      description: Create SAML Identity Provider
      operationId: post-saml-identity-provider
      security:
      - oauth2:
        - https://jans.io/idp/saml.write
  /idp/kc/saml/{inum}:
    get:
      tags:
      - Jans - SAML Identity Broker
      summary: Get SAML Identity Provider by Inum
      description: Get SAML Identity Provider by Inum
      operationId: get-saml-identity-provider-by-inum
      security:
      - oauth2:
        - https://jans.io/idp/saml.readonly
    delete:
      tags:
      - Jans - SAML Identity Broker
      summary: Delete SAML Identity Provider
      description: Delete SAML Identity Provider
      operationId: delete-saml-identity-provider
      security:
      - oauth2:
        - https://jans.io/idp/saml.delete
  /idp/kc/saml:
    get:
      tags:
      - Jans - SAML Identity Broker
      summary: Retrieves SAML Identity Provider
      description: Retrieves SAML Identity Provider
      operationId: get-saml-identity-provider
      security:
      - oauth2:
        - https://jans.io/idp/saml.readonly
  /idp/kc/saml/sp-metadata-file/{inum}:
    get:
      tags:
      - Jans - SAML Identity Broker
      summary: Get SAML SP Metadata Endpoint URL
      description: Get SAML SP Metadata Endpoint URL
      operationId: get-saml-sp-metadata-url
      security:
      - oauth2:
        - https://jans.io/idp/saml.readonly
  /idp/kc/saml/sp-metadata/{inum}:
    get:
      tags:
      - Jans - SAML Identity Broker
      summary: Get SAML SP Metadata as Json
      description: Get SAML SP Metadata as Json
      operationId: get-saml-sp-metadata-json
      security:
      - oauth2:
        - https://jans.io/idp/saml.readonly
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://{op-hostname}/.../token"
          scopes:
            https://jans.io/idp/config.readonly: View Jans Identity Broker config
              related information
            https://jans.io/idp/config.write: Manage Jans Identity Broker config related
              information
            https://jans.io/idp/realm.readonly: View Identity Broker realm related
              information
            https://jans.io/idp/realm.write: Manage Identity Broker realm related
              information
            https://jans.io/idp/saml.readonly: View Identity Broker SAML Identity
              Broker related information
            https://jans.io/idp/saml.write: Manage Identity Broker SAML Identity Broker
              related information
