openapi: 3.0.1
info:
  title: Jans Config API - Admin-UI
  contact:
    name: Gluu Support
    url: https://support.gluu.org
    email: xxx@gluu.org
  license:
    name: Apache 2.0
    url: https://github.com/JanssenProject/jans/blob/main/LICENSE
  version: 1.0.0
servers:
- url: https://jans.io/
  description: The Jans server
tags:
- name: Admin UI - Role
- name: Admin UI - Permission
- name: Admin UI - Role-Permissions Mapping
- name: Admin UI - License
- name: Admin UI - Webhooks
paths:
  /admin-ui/adminUIPermissions:
    get:
      tags:
      - Admin UI - Permission
      summary: Get all admin ui permissions
      description: Get all admin ui permissions
      operationId: get-all-adminui-permissions
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.readonly
    put:
      tags:
      - Admin UI - Permission
      summary: Edit admin ui permissions
      description: Edit admin ui permissions
      operationId: edit-adminui-permission
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.write
    post:
      tags:
      - Admin UI - Permission
      summary: Add admin ui permissions
      description: Add admin ui permissions
      operationId: add-adminui-permission
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.write
  /admin-ui/adminUIRolePermissionsMapping:
    get:
      tags:
      - Admin UI - Role-Permissions Mapping
      summary: Get all admin ui role-permissions mapping
      description: Get all admin ui role-permissions mapping
      operationId: get-all-adminui-role-permissions
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.readonly
    put:
      tags:
      - Admin UI - Role-Permissions Mapping
      summary: Map permissions to role
      description: Map permissions to role
      operationId: map-permissions-to-role
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.write
    post:
      tags:
      - Admin UI - Role-Permissions Mapping
      summary: Add role-permissions mapping
      description: Add role-permissions mapping
      operationId: add-role-permissions-mapping
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.write
  /admin-ui/adminUIRoles:
    get:
      tags:
      - Admin UI - Role
      summary: Get all admin ui roles
      description: Get all admin ui roles
      operationId: get-all-adminui-roles
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/role.readonly
    put:
      tags:
      - Admin UI - Role
      summary: Edit admin ui role
      description: Edit admin ui role
      operationId: edit-adminui-role
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/role.write
    post:
      tags:
      - Admin UI - Role
      summary: Add admin ui role
      description: Add admin ui role
      operationId: add-adminui-role
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/role.write
  /admin-ui/adminUIPermissions/{adminUIPermission}:
    get:
      tags:
      - Admin UI - Permission
      summary: Get admin ui permission by permission-name
      description: Get admin ui permission by permission-name
      operationId: get-adminui-permission
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.readonly
    delete:
      tags:
      - Admin UI - Permission
      summary: Delete admin ui permission by permission-name
      description: Delete admin ui permission by permission-name
      operationId: delete-adminui-permission
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.delete
  /admin-ui/adminUIRoles/{adminUIRole}:
    get:
      tags:
      - Admin UI - Role
      summary: Get admin ui role details by role-name
      description: Get admin ui role details by role-name
      operationId: get-adminui-role
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/role.readonly
    delete:
      tags:
      - Admin UI - Role
      summary: Delete admin ui role by role-name
      description: Delete admin ui role by role-name
      operationId: delete-adminui-role
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/role.delete
  /admin-ui/config:
    get:
      tags:
      - Admin UI - Configuration
      summary: Get Admin UI editable configuration
      description: Get Admin UI editable configuration
      operationId: get-adminui-conf
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/role.readonly
    put:
      tags:
      - Admin UI - Configuration
      summary: Edit Admin UI editable configuration
      description: Edit Admin UI editable configuration
      operationId: edit-adminui-conf
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/properties.write
  /admin-ui/adminUIRolePermissionsMapping/{adminUIRole}:
    get:
      tags:
      - Admin UI - Role-Permissions Mapping
      summary: Get admin ui role-permissions mapping by role-name
      description: Get admin ui role-permissions mapping by role-name
      operationId: get-adminui-role-permissions
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.readonly
    delete:
      tags:
      - Admin UI - Role-Permissions Mapping
      summary: Remove role-permissions mapping by role-name
      description: Remove role-permissions mapping by role-name
      operationId: remove-role-permissions-permission
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.delete
  /admin-ui/license/activate:
    post:
      tags:
      - Admin UI - License
      summary: Activate license using license-key
      description: Activate license using license-key
      operationId: activate-adminui-license
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/license.write
  /admin-ui/license/details:
    get:
      tags:
      - Admin UI - License
      summary: Get admin ui license details
      description: Get admin ui license details
      operationId: get-adminui-license
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/license.readonly
  /admin-ui/license/isActive:
    get:
      tags:
      - Admin UI - License
      summary: Check if admin-ui license is active
      description: Check if admin-ui license is active
      operationId: is-license-active
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/license.readonly
  /admin-ui/license/isConfigValid:
    get:
      tags:
      - Admin UI - License
      summary: Is license configuration valid
      description: Is license configuration valid
      operationId: check-adminui-license-config
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/license.readonly
  /admin-ui/license/retrieve:
    get:
      tags:
      - Admin UI - License
      summary: Retrieve license from SCAN
      description: Retrieve license from SCAN
      operationId: retrieve-license
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/license.readonly
  /admin-ui/license/ssa:
    post:
      tags:
      - Admin UI - License
      summary: Save SSA in configuration
      description: Save SSA in configuration
      operationId: adminui-post-ssa
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/license.write
  /admin-ui/license/trial:
    get:
      tags:
      - Admin UI - License
      summary: Generate trial license
      description: Generate trial license
      operationId: get-trial-license
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/license.readonly
  /admin-ui/webhook:
    get:
      tags:
      - Admin UI - Webhooks
      summary: Gets list of webhooks
      description: Gets list of webhooks
      operationId: get-all-webhooks
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedResult'
              examples:
                Response json example:
                  description: Response json example
                  value: |
                    {
                      "start": 0,
                      "totalEntriesCount": 2,
                      "entriesCount": 2,
                      "entries": [{
                        "dn": "inum=aad9e1dd-87f3-357f-a2fa-93ae8eb94998,ou=auiWebhooks,ou=admin-ui,o=jans",
                        "inum": "aad9e1dd-87f3-357f-a2fa-93ae8eb94998",
                        "displayName": "test-5",
                        "description": "test1",
                        "url": "https://jsonplaceholder.typicode.com/posts",
                        "httpRequestBody": "{\"userId\": 11,\"id\": 11,\"title\": \"sunt aut facere repellat provident occaecati excepturi optio reprehenderit\",\"body\": \"quia et suscipitsutem sunt rem eveniet architecto\"}",
                        "httpMethod": "POST",
                        "jansEnabled": true,
                        "httpHeaders": [{
                          "key": "Content-Type",
                          "value": "application/json"
                        }],
                        "baseDn": "inum=aad9e1dd-87f3-357f-a2fa-93ae8eb94998,ou=auiWebhooks,ou=admin-ui,o=jans"
                      }, {
                        "dn": "inum=d23d60e8-0187-3878-94d9-30d594c4c986,ou=auiWebhooks,ou=admin-ui,o=jans",
                        "inum": "d23d60e8-0187-3878-94d9-30d594c4c986",
                        "displayName": "test-6",
                        "description": "test1",
                        "url": "https://jsonplaceholder.typicode.com/posts",
                        "httpRequestBody": "{\"userId\": 11,\"id\": 11,\"title\": \"sunt aut facere repellat provident occaecati excepturi optio reprehenderit\",\"body\": \"quia et suscipitsutem sunt rem eveniet architecto\"}",
                        "httpMethod": "POST",
                        "jansEnabled": true,
                        "httpHeaders": [{
                          "key": "Content-Type",
                          "value": "application/json"
                        }],
                        "baseDn": "inum=d23d60e8-0187-3878-94d9-30d594c4c986,ou=auiWebhooks,ou=admin-ui,o=jans"
                      }]
                    }
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        "401":
          description: Unauthorized
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/webhook.readonly
    put:
      tags:
      - Admin UI - Webhooks
      summary: Update Webhook
      description: Update Webhook
      operationId: put-webhook
      requestBody:
        description: Webhook object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookEntry'
            examples:
              Request json example:
                description: Request json example
                value: |
                  {
                    "dn": "inum=2d3fe60f-db3f-3ab8-a285-e71e935ff282,ou=auiWebhooks,ou=admin-ui,o=jans",
                    "inum": "2d3fe60f-db3f-3ab8-a285-e71e935ff282",
                    "displayName": "posts-webhook-1",
                    "description": "posts-webhook description",
                    "url": "https://jsonplaceholder.typicode.com/posts",
                    "httpRequestBody": "{\"userId\": 11,\"id\": 11,\"title\": \"sunt aut facere repellat provident occaecati excepturi optio reprehenderit\",\"body\": \"quia et suscipitsuscipit recusandae consequuntur expedita et cumreprehenderit molestiae ut ut quas otamnostrum rerum est autem sunt rem eveniet architecto\"}",
                    "httpMethod": "POST",
                    "jansEnabled": true,
                    "httpHeaders": [{
                      "key": "Content-Type",
                      "value": "application/json"
                    }],
                    "auiFeatureIds": ["jans_link_write"],
                    "baseDn": "inum=2d3fe60f-db3f-3ab8-a285-e71e935ff282,ou=auiWebhooks,ou=admin-ui,o=jans"
                  }
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookEntry'
              examples:
                Response json example:
                  description: Response json example
                  value: |
                    {
                      "dn": "inum=2d3fe60f-db3f-3ab8-a285-e71e935ff282,ou=auiWebhooks,ou=admin-ui,o=jans",
                      "inum": "2d3fe60f-db3f-3ab8-a285-e71e935ff282",
                      "displayName": "posts-webhook-1",
                      "description": "posts-webhook description",
                      "url": "https://jsonplaceholder.typicode.com/posts",
                      "httpRequestBody": "{\"userId\": 11,\"id\": 11,\"title\": \"sunt aut facere repellat provident occaecati excepturi optio reprehenderit\",\"body\": \"quia et suscipitsuscipit recusandae consequuntur expedita et cumreprehenderit molestiae ut ut quas otamnostrum rerum est autem sunt rem eveniet architecto\"}",
                      "httpMethod": "POST",
                      "jansEnabled": true,
                      "httpHeaders": [{
                        "key": "Content-Type",
                        "value": "application/json"
                      }],
                      "auiFeatureIds": ["jans_link_write"],
                      "baseDn": "inum=2d3fe60f-db3f-3ab8-a285-e71e935ff282,ou=auiWebhooks,ou=admin-ui,o=jans"
                    }
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        "401":
          description: Unauthorized
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/webhook.write
    post:
      tags:
      - Admin UI - Webhooks
      summary: Create Webhook
      description: Create Webhook
      operationId: post-webhook
      requestBody:
        description: Webhook object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookEntry'
            examples:
              Request json example:
                description: Request json example
                value: |
                  {
                    "displayName": "posts-webhook-1",
                    "description": "posts-webhook description",
                    "url": "https://reqres.in/api/users",
                    "httpRequestBody": {
                      "name": "morpheus",
                      "job": "leader"
                    },
                    "httpMethod": "POST",
                    "jansEnabled": true,
                    "httpHeaders":[{"key":"Content-Type", "value":"application/json"}],
                    "auiFeatureIds":["jans_link_write"]
                  }
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scope'
              examples:
                Response json example:
                  description: Response json example
                  value: |
                    {
                      "dn": "inum=f704922d-e97f-3097-a06a-4a90ddedb87a,ou=auiWebhooks,ou=admin-ui,o=jans",
                      "inum": "f704922d-e97f-3097-a06a-4a90ddedb87a",
                      "displayName": "posts-webhook-1",
                      "description": "posts-webhook description",
                      "url": "https://reqres.in/api/users",
                      "httpRequestBody": {
                        "name": "morpheus",
                        "job": "leader"
                      },
                      "httpMethod": "POST",
                      "jansEnabled": true,
                      "httpHeaders": [{
                        "key": "Content-Type",
                        "value": "application/json"
                      }],
                      "auiFeatureIds": ["jans_link_write"],
                      "baseDn": "inum=f704922d-e97f-3097-a06a-4a90ddedb87a,ou=auiWebhooks,ou=admin-ui,o=jans"
                    }
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        "401":
          description: Unauthorized
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/webhook.write
  /admin-ui/webhook/{webhookId}:
    delete:
      tags:
      - Admin UI - Webhooks
      summary: Delete Webhook
      description: Delete Webhook
      operationId: delete-Webhook-by-inum
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/webhook.delete
  /admin-ui/webhook/features:
    get:
      tags:
      - Admin UI - Webhooks
      summary: Gets list of Admin UI features
      description: Gets list of Admin UI features
      operationId: get-all-features
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/webhook.readonly
  /admin-ui/webhook/features/{webhookId}:
    get:
      tags:
      - Admin UI - Webhooks
      summary: Gets list of Admin UI features mapped to webhookId
      description: Gets list of Admin UI features mapped to webhookId
      operationId: get-features-by-webhook-id
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/webhook.readonly
  /admin-ui/webhook/{featureId}:
    get:
      tags:
      - Admin UI - Webhooks
      summary: Gets list of Admin UI Webhooks mapped to featureId
      description: Gets list of Admin UI Webhooks mapped to featureId
      operationId: get-webhooks-by-feature-id
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookEntry'
              examples:
                Response json example:
                  description: Response json example
                  value: |
                    [{
                      "dn": "inum=aad9e1dd-87f3-357f-a2fa-93ae8eb94998,ou=auiWebhooks,ou=admin-ui,o=jans",
                      "inum": "aad9e1dd-87f3-357f-a2fa-93ae8eb94998",
                      "displayName": "test-5",
                      "description": "test1",
                      "url": "https://jsonplaceholder.typicode.com/posts",
                      "httpRequestBody": "{\"userId\": 11,\"id\": 11,\"title\": \"sunt aut facere repellat provident occaecati excepturi optio reprehenderit\",\"body\": \"quia et suscipitsutem sunt rem eveniet architecto\"}",
                      "httpMethod": "POST",
                      "jansEnabled": true,
                      "httpHeaders": [{
                        "key": "Content-Type",
                        "value": "application/json"
                      }],
                      "baseDn": "inum=aad9e1dd-87f3-357f-a2fa-93ae8eb94998,ou=auiWebhooks,ou=admin-ui,o=jans"
                    }, {
                      "dn": "inum=d23d60e8-0187-3878-94d9-30d594c4c986,ou=auiWebhooks,ou=admin-ui,o=jans",
                      "inum": "d23d60e8-0187-3878-94d9-30d594c4c986",
                      "displayName": "test-6",
                      "description": "test1",
                      "url": "https://jsonplaceholder.typicode.com/posts",
                      "httpRequestBody": "{\"userId\": 11,\"id\": 11,\"title\": \"sunt aut facere repellat provident occaecati excepturi optio reprehenderit\",\"body\": \"quia et suscipitsutem sunt rem eveniet architecto\"}",
                      "httpMethod": "POST",
                      "jansEnabled": true,
                      "httpHeaders": [{
                        "key": "Content-Type",
                        "value": "application/json"
                      }],
                      "baseDn": "inum=d23d60e8-0187-3878-94d9-30d594c4c986,ou=auiWebhooks,ou=admin-ui,o=jans"
                    }]
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        "401":
          description: Unauthorized
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/webhook.readonly
  /admin-ui/webhook/trigger/{featureId}:
    post:
      tags:
      - Admin UI - Webhooks
      summary: Trigger webhooks mapped to featureId
      description: Trigger webhooks mapped to featureId
      operationId: trigger-webhook
      security:
      - oauth2:
        - https://jans.io/oauth/jans-auth-server/config/adminui/webhook.readonly
components:
  schemas:
    AdminPermission:
      type: object
      properties:
        tag:
          type: string
        permission:
          type: string
        description:
          type: string
        defaultPermissionInToken:
          type: boolean
    GenericResponse:
      type: object
      properties:
        success:
          type: boolean
        responseMessage:
          type: string
        responseCode:
          type: integer
          format: int32
        responseObject:
          $ref: '#/components/schemas/JsonNode'
    JsonNode:
      type: object
    RolePermissionMapping:
      type: object
      properties:
        role:
          type: string
        permissions:
          type: array
          items:
            type: string
    AdminRole:
      type: object
      properties:
        role:
          type: string
        description:
          type: string
        deletable:
          type: boolean
    AppConfigResponse:
      type: object
      properties:
        authServerHost:
          type: string
          description: Auth Server host
          readOnly: true
        authzBaseUrl:
          type: string
          description: Authorization base URL
          readOnly: true
        clientId:
          type: string
          description: OIDC Client ID
          readOnly: true
        responseType:
          type: string
          description: OIDC Client Secret
          readOnly: true
        scope:
          type: string
          description: Scope
          readOnly: true
        redirectUrl:
          type: string
          description: Redirect URL
          readOnly: true
        acrValues:
          type: string
          description: ACR Value
        frontChannelLogoutUrl:
          type: string
          description: Front Channel Logout URL
          readOnly: true
        postLogoutRedirectUri:
          type: string
          description: Post Logout Redirect URL
          readOnly: true
        endSessionEndpoint:
          type: string
          description: End Session Endpoint
          readOnly: true
        sessionTimeoutInMins:
          type: integer
          description: Admin UI Session Timeout
          format: int32
        allowSmtpKeystoreEdit:
          type: boolean
          description: Admin UI allow SMTP Keystore Edit
        additionalParameters:
          type: array
          description: Additional Authentication Parameters
          items:
            $ref: '#/components/schemas/KeyValuePair'
    KeyValuePair:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    LicenseRequest:
      type: object
      properties:
        licenseKey:
          type: string
    LicenseResponse:
      type: object
      properties:
        licenseEnabled:
          type: boolean
        productName:
          type: string
        productCode:
          type: string
        licenseType:
          type: string
        maxActivations:
          type: integer
          format: int32
        licenseKey:
          type: string
        licenseActive:
          type: boolean
        validityPeriod:
          type: string
        companyName:
          type: string
        customerEmail:
          type: string
        customerFirstName:
          type: string
        customerLastName:
          type: string
        licenseMAUThreshold:
          type: integer
          format: int64
        licenseExpired:
          type: boolean
    SSARequest:
      type: object
      properties:
        ssa:
          type: string
    WebhookEntry:
      required:
      - displayName
      - url
      type: object
      properties:
        dn:
          type: string
        inum:
          type: string
        displayName:
          maxLength: 60
          minLength: 2
          pattern: "^[a-zA-Z0-9_\\-\\:\\/\\.]+$"
          type: string
        description:
          type: string
        url:
          type: string
        httpRequestBodyString:
          type: string
        httpMethod:
          type: string
        jansEnabled:
          type: boolean
        httpHeaders:
          type: array
          items:
            $ref: '#/components/schemas/KeyValuePair'
        auiFeatureIds:
          uniqueItems: true
          type: array
          items:
            type: string
        httpRequestBody:
          type: object
          additionalProperties:
            type: object
        baseDn:
          type: string
    Scope:
      type: object
      properties:
        dn:
          type: string
        expirationDate:
          type: string
          format: date-time
        deletable:
          type: boolean
        inum:
          type: string
        displayName:
          type: string
        id:
          type: string
        iconUrl:
          type: string
        description:
          type: string
        scopeType:
          type: string
          enum:
          - openid
          - dynamic
          - uma
          - spontaneous
          - oauth
        claims:
          type: array
          items:
            type: string
        defaultScope:
          type: boolean
        groupClaims:
          type: boolean
        dynamicScopeScripts:
          type: array
          items:
            type: string
        umaAuthorizationPolicies:
          type: array
          items:
            type: string
        attributes:
          $ref: '#/components/schemas/ScopeAttributes'
        creatorId:
          type: string
        creatorType:
          type: string
          enum:
          - none
          - client
          - user
          - auto
        creationDate:
          type: string
          format: date-time
        creatorAttributes:
          type: object
          additionalProperties:
            type: string
        umaType:
          type: boolean
        baseDn:
          type: string
    ScopeAttributes:
      type: object
      properties:
        spontaneousClientScopes:
          type: array
          items:
            type: string
        showInConfigurationEndpoint:
          type: boolean
    AuiFeature:
      type: object
      properties:
        dn:
          type: string
        auiFeatureId:
          type: string
        displayName:
          type: string
        jansScope:
          type: string
        webhookIdsMapped:
          type: array
          items:
            type: string
        baseDn:
          type: string
    PagedResult:
      type: object
      properties:
        start:
          type: integer
          format: int32
        totalEntriesCount:
          type: integer
          format: int32
        entriesCount:
          type: integer
          format: int32
        entries:
          type: array
          items:
            type: object
    ShortCodeRequest:
      required:
      - webhookId
      type: object
      properties:
        webhookId:
          type: string
        shortcodeValueMap:
          type: object
          additionalProperties:
            type: object
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://{op-hostname}/.../token"
          scopes:
            https://jans.io/oauth/jans-auth-server/config/adminui/user/role.read: View
              admin user role related information
            https://jans.io/oauth/jans-auth-server/config/adminui/user/role.write: Manage
              admin user role related information
            https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.read: View
              admin permission related information
            https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.write: Manage
              admin permission related information
            https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.readonly: View
              role-permission mapping related information
            https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.write: Manage
              role-permission mapping related information
            https://jans.io/oauth/jans-auth-server/config/adminui/license.readonly: Delete
              admin-ui license related information
            https://jans.io/oauth/jans-auth-server/config/adminui/license.write: View
              admin-ui license related information
