openapi: 3.0.1
info:
  title: Jans Config API - SAML
  contact:
    name: Gluu Support
    url: https://support.gluu.org
    email: xxx@gluu.org
  license:
    name: Apache 2.0
    url: https://github.com/JanssenProject/jans/blob/main/LICENSE
  version: OAS Version
servers:
- url: https://jans.io/
  description: The Jans server
tags:
- name: SAML - Configuration
- name: SAML - Trust Relationship
- name: SAML - Identity Broker
paths:
  /kc/saml/idp/upload:
    put:
      tags:
      - SAML - Identity Broker
      summary: Update SAML Identity Provider
      description: Update SAML Identity Provider
      operationId: put-saml-identity-provider
      security:
      - oauth2:
        - https://jans.io/idp/saml.write
    post:
      tags:
      - SAML - Identity Broker
      summary: Create SAML Identity Provider
      description: Create SAML Identity Provider
      operationId: post-saml-identity-provider
      security:
      - oauth2:
        - https://jans.io/idp/saml.write
  /kc/saml/idp/{inum}:
    get:
      tags:
      - SAML - Identity Broker
      summary: Get SAML Identity Provider by Inum
      description: Get SAML Identity Provider by Inum
      operationId: get-saml-identity-provider-by-inum
      security:
      - oauth2:
        - https://jans.io/idp/saml.readonly
    delete:
      tags:
      - SAML - Identity Broker
      summary: Delete SAML Identity Provider
      description: Delete SAML Identity Provider
      operationId: delete-saml-identity-provider
      security:
      - oauth2:
        - https://jans.io/idp/saml.delete
  /kc/saml/idp:
    get:
      tags:
      - SAML - Identity Broker
      summary: Retrieves SAML Identity Provider
      description: Retrieves SAML Identity Provider
      operationId: get-saml-identity-provider
      security:
      - oauth2:
        - https://jans.io/idp/saml.readonly
  /kc/saml/idp/sp-metadata/{inum}:
    get:
      tags:
      - SAML - Identity Broker
      summary: Get SAML SP Metadata as Json
      description: Get SAML SP Metadata as Json
      operationId: get-saml-sp-metadata-json
      security:
      - oauth2:
        - https://jans.io/idp/saml.readonly
  /kc/saml/idp/sp-metadata-file/{inum}:
    get:
      tags:
      - SAML - Identity Broker
      summary: Get SAML SP Metadata Endpoint URL
      description: Get SAML SP Metadata Endpoint URL
      operationId: get-saml-sp-metadata-url
      security:
      - oauth2:
        - https://jans.io/idp/saml.readonly
  /kc/saml/idp/process-idp-meta-file:
    post:
      tags:
      - SAML - Identity Broker
      summary: Process unprocessed IDP metadata files
      description: Process unprocessed IDP metadata files
      operationId: post-idp-metadata-files
      security:
      - oauth2:
        - https://jans.io/idp/saml.write
  /kc/samlConfig:
    get:
      tags:
      - SAML - Configuration
      summary: Gets SAML configuration properties
      description: Gets SAML configuration properties
      operationId: get-saml-properties
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml-config.readonly
    put:
      tags:
      - SAML - Configuration
      summary: Update SAML configuration properties
      description: Update SAML configuration properties
      operationId: put-saml-properties
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml-config.write
    patch:
      tags:
      - SAML - Configuration
      summary: Partially modifies SAML configuration properties.
      description: Partially modifies SAML Configuration properties.
      operationId: patch-saml-properties
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml-config.write
  /kc/saml/trust-relationship/upload:
    put:
      tags:
      - SAML - Trust Relationship
      summary: Update TrustRelationship
      description: Update TrustRelationship
      operationId: put-trust-relationship
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.write
    post:
      tags:
      - SAML - Trust Relationship
      summary: Create Trust Relationship with Metadata File
      description: Create Trust Relationship with Metadata File
      operationId: post-trust-relationship-metadata-file
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.write
  /kc/saml/trust-relationship/{id}:
    delete:
      tags:
      - SAML - Trust Relationship
      summary: Delete TrustRelationship
      description: Delete TrustRelationship
      operationId: delete-trust-relationship
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.write
  /kc/saml/trust-relationship:
    get:
      tags:
      - SAML - Trust Relationship
      summary: Get all Trust Relationship
      description: Get all TrustRelationship.
      operationId: get-trust-relationships
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.readonly
  /kc/saml/trust-relationship/id/{id}:
    get:
      tags:
      - SAML - Trust Relationship
      summary: Get TrustRelationship by Id
      description: Get TrustRelationship by Id
      operationId: get-trust-relationship-by-id
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.readonly
  /kc/saml/trust-relationship/sp-metadata-file/{id}:
    get:
      tags:
      - SAML - Trust Relationship
      summary: Get TrustRelationship file metadata
      description: Get TrustRelationship file metadata
      operationId: get-trust-relationship-file-metadata
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.readonly
  /kc/saml/trust-relationship/process-sp-meta-file:
    post:
      tags:
      - SAML - Trust Relationship
      summary: Process unprocessed metadata files
      description: Process unprocessed metadata files
      operationId: post-metadata-files
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.write
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://{op-hostname}/.../token"
          scopes:
            https://jans.io/oauth/config/saml.readonly: View SAML related information
            https://jans.io/oauth/config/saml.write: Manage SAML related information
            https://jans.io/oauth/config/saml-config.readonly: View SAML configuration
              related information
            https://jans.io/oauth/config/saml-config.write: Manage SAML configuration
              related information
