openapi: 3.0.1
info:
  title: Jans Config API - Lock
  contact:
    name: Gluu Support
    url: https://support.gluu.org
    email: support@gluu.org
  license:
    name: Apache 2.0
    url: https://github.com/JanssenProject/jans/blob/main/LICENSE
  version: 1.0.0
servers:
- url: https://jans.io/
  description: The Jans server
tags:
- name: Lock - Configuration
- name: Lock - Audit
- name: Lock - Statistics
paths:
  /lock/audit/health/search:
    get:
      tags:
      - Lock - Audit
      summary: Rerquest health records for specific event range
      description: Rerquest health records for specific event range
      operationId: request-lock-health-records-event-range
      security:
      - oauth2:
        - https://jans.io/oauth/lock/health.readonly
      - oauth2:
        - https://jans.io/oauth/lock/health.write
      - oauth2:
        - https://jans.io/oauth/config/lock.admin
      - oauth2:
        - https://jans.io/oauth/lock/read-all
      - oauth2:
        - https://jans.io/oauth/config/read-all
  /lock/audit/log/search:
    get:
      tags:
      - Lock - Log
      summary: Rerquest log records for specific event range
      description: Rerquest log records for specific event range
      operationId: request-lock-log-records-event-range
      security:
      - oauth2:
        - https://jans.io/oauth/lock/log.readonly
      - oauth2:
        - https://jans.io/oauth/lock/log.write
      - oauth2:
        - https://jans.io/oauth/config/lock.admin
      - oauth2:
        - https://jans.io/oauth/lock/read-all
      - oauth2:
        - https://jans.io/oauth/config/read-all
  /lock/audit/telemetry/search:
    get:
      tags:
      - Lock - Audit
      summary: Request telemetry records for specific event range
      description: Rerquest telemetry records for specific event range
      operationId: request-lock-telemetry-records-event-range
      security:
      - oauth2:
        - https://jans.io/oauth/lock/telemetry.readonly
      - oauth2:
        - https://jans.io/oauth/lock/telemetry.write
      - oauth2:
        - https://jans.io/oauth/config/lock.admin
      - oauth2:
        - https://jans.io/oauth/lock/read-all
      - oauth2:
        - https://jans.io/oauth/config/read-all
  /lock/audit/health/bulk:
    post:
      tags:
      - Lock - Audit
      summary: Bulk save health data
      description: Bulk save health data
      operationId: bulk-save-health-data
      security:
      - oauth2:
        - https://jans.io/oauth/lock/health.write
      - oauth2:
        - https://jans.io/oauth/config/lock.admin
      - oauth2:
        - https://jans.io/oauth/lock/write-all
      - oauth2:
        - https://jans.io/oauth/config/write-all
  /lock/audit/log/bulk:
    post:
      tags:
      - Lock - Audit
      summary: Bulk save log data
      description: Bulk save log data
      operationId: bulk-save-log-data
      security:
      - oauth2:
        - https://jans.io/oauth/lock/log.write
      - oauth2:
        - https://jans.io/oauth/config/lock.admin
      - oauth2:
        - https://jans.io/oauth/lock/write-all
      - oauth2:
        - https://jans.io/oauth/config/write-all
  /lock/audit/telemetry/bulk:
    post:
      tags:
      - Lock - Audit
      summary: Bulk save telemetry data
      description: Bulk save telemetry data
      operationId: bulk-save-telemetry-data
      security:
      - oauth2:
        - https://jans.io/oauth/lock/telemetry.write
      - oauth2:
        - https://jans.io/oauth/config/lock.admin
      - oauth2:
        - https://jans.io/oauth/lock/write-all
      - oauth2:
        - https://jans.io/oauth/config/write-all
  /lock/audit/health:
    post:
      tags:
      - Lock - Audit
      summary: Save health data
      description: Save health data
      operationId: save-health-data
      security:
      - oauth2:
        - https://jans.io/oauth/lock/health.write
      - oauth2:
        - https://jans.io/oauth/config/lock.admin
      - oauth2:
        - https://jans.io/oauth/lock/write-all
      - oauth2:
        - https://jans.io/oauth/config/write-all
  /lock/audit/log:
    post:
      tags:
      - Lock - Audit
      summary: Save log data
      description: Save log data
      operationId: save-log-data
      security:
      - oauth2:
        - https://jans.io/oauth/lock/log.write
      - oauth2:
        - https://jans.io/oauth/config/lock.admin
      - oauth2:
        - https://jans.io/oauth/lock/write-all
      - oauth2:
        - https://jans.io/oauth/config/write-all
  /lock/audit/telemetry:
    post:
      tags:
      - Lock - Audit
      summary: Save telemetry data
      description: Save telemetry data
      operationId: save-telemetry-data
      security:
      - oauth2:
        - https://jans.io/oauth/lock/telemetry.write
      - oauth2:
        - https://jans.io/oauth/config/lock.admin
      - oauth2:
        - https://jans.io/oauth/lock/write-all
      - oauth2:
        - https://jans.io/oauth/config/write-all
  /lock/lockConfig:
    get:
      tags:
      - Lock - Configuration
      summary: Gets Lock configuration properties
      description: Gets Lock configuration properties
      operationId: get-lock-properties
      security:
      - oauth2:
        - https://jans.io/oauth/lock-config.readonly
      - oauth2:
        - https://jans.io/oauth/lock-config.write
      - oauth2:
        - https://jans.io/oauth/config/lock.admin
      - oauth2:
        - https://jans.io/oauth/lock/read-all
      - oauth2:
        - https://jans.io/oauth/config/read-all
      - oauth2:
        - https://jans.io/oauth/config/write-all
    put:
      tags:
      - Lock - Configuration
      summary: Update Lock configuration properties
      description: Update Lock configuration properties
      operationId: put-lock-properties
      security:
      - oauth2:
        - https://jans.io/oauth/lock-config.write
      - oauth2:
        - https://jans.io/oauth/config/lock.admin
      - oauth2:
        - https://jans.io/oauth/lock/write-all
      - oauth2:
        - https://jans.io/oauth/config/write-all
    patch:
      tags:
      - Lock - Configuration
      summary: Partially modifies Lock configuration properties.
      description: Partially modifies Lock configuration properties.
      operationId: patch-lock-properties
      security:
      - oauth2:
        - https://jans.io/oauth/lock-config.write
      - oauth2:
        - https://jans.io/oauth/config/lock.admin
      - oauth2:
        - https://jans.io/oauth/lock/write-all
      - oauth2:
        - https://jans.io/oauth/config/write-all
  /lock/lockStat:
    get:
      tags:
      - Statistics
      summary: Provides basic statistic
      description: Provides basic statistic
      operationId: get-lock-stat
      security:
      - oauth2:
        - https://jans.io/oauth/lock/read-all
        - jans_stat
      - oauth2:
        - https://jans.io/oauth/config/lock.admin
      - oauth2:
        - https://jans.io/oauth/config/read-all
      - oauth2:
        - https://jans.io/oauth/config/write-all
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://{op-hostname}/.../token"
          scopes:
            https://jans.io/oauth/lock/read-all: View Lock related information
            https://jans.io/oauth/lock/write-all: View Lock related information
            https://jans.io/oauth/lock-config.readonly: View Lock configuration related
              information
            https://jans.io/oauth/lock-config.write: Manage Lock configuration related
              information
            https://jans.io/oauth/lock/audit.readonly: View Lock audit related information
            https://jans.io/oauth/lock/audit.write: View Lock audit related information
            https://jans.io/oauth/lock/health.readonly: View Lock health related information
            https://jans.io/oauth/lock/health.write: Manage Lock health related information
            https://jans.io/oauth/lock/log.readonly: View Lock log related information
            https://jans.io/oauth/lock/log.write: Manage Lock log health related information
            https://jans.io/oauth/lock/telemetry.readonly: View Lock telemetry related
              information
            https://jans.io/oauth/lock/telemetry.write: Manage Lock telemetry related
              information
            https://jans.io/oauth/config/lock.admin: Lock Admin access to manage all
              Lock configuration related information
            https://jans.io/oauth/config/read-all: Super admin read access to all
              configuration resources
            https://jans.io/oauth/config/write-all: Super admin write access to all
              configuration resources
            https://jans.io/oauth/config/delete-all: Super admin delete access to
              all configuration resources
            jans_stat: Auth Server Stats Authorization Scope
