openapi: 3.0.1
info:
  title: Jans Config API - SAML
  contact:
    name: Gluu Support
    url: https://support.gluu.org
    email: xxx@gluu.org
  license:
    name: Apache 2.0
    url: https://github.com/JanssenProject/jans/blob/main/LICENSE
  version: 1.0.0
servers:
- url: https://jans.io/
  description: The Jans server
  variables: {}
tags:
- name: SAML - Configuration
- name: SAML - Trust Relationship
paths:
  /saml/samlConfig:
    get:
      tags:
      - SAML - Configuration
      summary: Gets SAML configuration properties
      description: Gets SAML configuration properties
      operationId: get-saml-properties
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml-config.readonly
    patch:
      tags:
      - SAML - Configuration
      summary: Partially modifies SAML configuration properties.
      description: Partially modifies SAML Configuration properties.
      operationId: patch-saml-properties
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml-config.write
  /saml/scope/{clientId}:
    get:
      tags:
      - SAML - Client Scope
      summary: Get Client Scope
      description: Get Client Scope
      operationId: get-saml-client-scope
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml-scope.readonly
    put:
      tags:
      - SAML - Client Scope
      summary: Update Client Scope
      description: Update Client Scope
      operationId: post-saml-client-scope_1
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml-scope.write
    post:
      operationId: addClientScope
  /saml/scope/test/{clientId}:
    post:
      tags:
      - SAML - Client Scope
      summary: Add new Client Scope
      description: Add new Client Scope
      operationId: post-saml-client-scope
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml-scope.write
  /saml/trust-relationship:
    get:
      tags:
      - SAML - Trust Relationship
      summary: Get all Trust Relationship
      description: Get all TrustRelationship.
      operationId: get-trust-relationship
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.readonly
    put:
      tags:
      - SAML - Trust Relationship
      summary: Update TrustRelationship
      description: Update TrustRelationship
      operationId: put-trust-relationship_1
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.write
    post:
      tags:
      - SAML - Trust Relationship
      summary: Create Trust Relationship without File
      description: Create Trust Relationship without File
      operationId: post-trust-relationship
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.write
  /saml/trust-relationship/upload:
    post:
      tags:
      - SAML - Trust Relationship
      summary: Create Trust Relationship with File
      description: Create Trust Relationship with File
      operationId: post-trust-relationship-file
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.write
  /saml/trust-relationship/{id}:
    delete:
      tags:
      - SAML - Trust Relationship
      summary: Delete TrustRelationship
      description: Delete TrustRelationship
      operationId: put-trust-relationship
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.write
  /saml/trust-relationship/id/{id}:
    get:
      tags:
      - SAML - Trust Relationship
      summary: Get TrustRelationship by Id
      description: Get TrustRelationship by Id
      operationId: get-trust-relationship-by-id
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.readonly
  /saml/trust-relationship/{clientId}:
    get:
      tags:
      - SAML - Trust Relationship
      summary: Get TrustRelationship by name
      description: Get TrustRelationship by name
      operationId: get-trust-relationship-by-name
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.readonly
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://{op-hostname}/.../token"
          scopes:
            https://jans.io/oauth/config/saml.readonly: View SAML related information
            https://jans.io/oauth/config/saml.write: Manage SAML related information
            https://jans.io/oauth/config/saml-config.readonly: View SAML configuration
              related information
            https://jans.io/oauth/config/saml-config.write: Manage SAML configuration
              related information
