openapi: 3.0.1
info:
  title: Jans Config API - SAML
  contact:
    name: Gluu Support
    url: https://support.gluu.org
    email: xxx@gluu.org
  license:
    name: Apache 2.0
    url: https://github.com/JanssenProject/jans/blob/main/LICENSE
  version: 1.0.0
servers:
- url: https://jans.io/
  description: The Jans server
  variables: {}
tags:
- name: SAML - Configuration
- name: SAML - Trust Relationship
paths:
  /saml/samlClient:
    get:
      tags:
      - SAML - Client
      summary: Get all Clients
      description: Get all Clients.
      operationId: get-saml-client
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.readonly
    put:
      tags:
      - SAML - Client
      summary: Update client
      description: Update client
      operationId: put-client_1
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.write
    post:
      tags:
      - SAML - Client
      summary: Create Client
      description: Create Client
      operationId: post-client
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.write
  /saml/samlClient/{id}:
    delete:
      tags:
      - SAML - Client
      summary: Delete client
      description: Delete client
      operationId: put-client
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.write
  /saml/samlClient/user:
    get:
      tags:
      - SAML - User
      summary: Get all users
      description: Get all users
      operationId: get-saml-user
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.readonly
  /saml/samlClient/{clientId}:
    get:
      tags:
      - SAML - Client
      summary: Get client by clientId
      description: Get client by clientId
      operationId: get-saml-client-by-clientId
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.readonly
  /saml/samlClient/id/{id}:
    get:
      tags:
      - SAML - Client
      summary: Get client by Id
      description: Get client by Id
      operationId: get-saml-client-by-id
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml.readonly
  /saml/samlConfig:
    get:
      tags:
      - SAML - Configuration
      summary: Gets Jans SAML configuration properties
      description: Gets Jans SAML configuration properties
      operationId: get-properties-saml
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml-config.readonly
  /saml/clientScope/{clientId}:
    get:
      tags:
      - SAML - Client Scope
      summary: Get Client Scope
      description: Get Client Scope
      operationId: get-saml-client-scope
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml-client-scope.readonly
    put:
      tags:
      - SAML - Client Scope
      summary: Update Client Scope
      description: Update Client Scope
      operationId: post-saml-client-scope_1
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml-client-scope.write
    post:
      operationId: addClientScope
  /saml/clientScope/test/{clientId}:
    post:
      tags:
      - SAML - Client Scope
      summary: Add new Client Scope
      description: Add new Client Scope
      operationId: post-saml-client-scope
      security:
      - oauth2:
        - https://jans.io/oauth/config/saml-client-scope.write
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://{op-hostname}/.../token"
          scopes:
            https://jans.io/oauth/config/saml.readonly: View SAML related information
            https://jans.io/oauth/config/saml.write: Manage SAML related information
            https://jans.io/oauth/config/saml-config.readonly: View SAML configuration
              related information
            https://jans.io/oauth/config/saml-config.write: Manage SAML configuration
              related information
