openapi: 3.0.1
info:
  title: Jans Config API - Shibboleth IDP
  contact:
    name: Gluu Support
    url: https://support.gluu.org
    email: support@gluu.org
  license:
    name: Apache 2.0
    url: https://github.com/JanssenProject/jans/blob/main/LICENSE
  version: 1.0.0
servers:
- url: https://jans.io/
  description: The Jans server
tags:
- name: Shibboleth - Plugin Configuration
- name: Shibboleth - Trust Relationship
paths:
  /shibboleth/shibboleth-plugin-config:
    get:
      tags:
      - Shibboleth - Plugin Configuration
      summary: Get Shibboleth Plugin configuration properties
      description: Gets Shibboleth Plugin configuration properties
      operationId: get-shibboleth-plugin-config
      security:
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/config.readonly
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/config.write
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/config.admin
      - oauth2:
        - https://jans.io/oauth/config/shibboleth.readonly
      - oauth2:
        - https://jans.io/oauth/config/read-all
    put:
      tags:
      - Shibboleth - Plugin Configuration
      summary: Update Shibboleth Plugin properties
      description: Update Shibboleth Plugin properties
      operationId: update-shibboleth-plugin-config
      security:
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/config.write
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/config.admin
    patch:
      tags:
      - Shibboleth - Plugin Configuration
      summary: Partially modifies Shibboleth Plugin configuration properties.
      description: Partially modifies Shibboleth Plugin Configuration properties.
      operationId: patch-shibboleth-plugin-config
      security:
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/config.write
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/config.admin
  /shibboleth/trust-relationship:
    get:
      tags:
      - Shibboleth - Trust Relationship
      summary: Gets trusted service providers
      description: Gets list of trusted service providers
      operationId: get-shibboleth-trust
      security:
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.readonly
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.write
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.admin
    put:
      tags:
      - Shibboleth - Trust Relationship
      summary: Update Trust Relationship details
      description: Update Trust Relationship details
      operationId: put-shibboleth-trust
      security:
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.write
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.admin
    post:
      tags:
      - Shibboleth - Trust Relationship
      summary: Adds trusted service provider
      description: Adds a new trusted service provider
      operationId: post-shibboleth-trust
      security:
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.write
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.admin
  /shibboleth/trust-relationship/{inum}:
    get:
      tags:
      - Shibboleth - Trust Relationship
      summary: Gets trusted service provider by unique identifier
      description: shibbolethService
      operationId: get-shibboleth-trust-by-inum
      security:
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.readonly
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.write
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.admin
    delete:
      tags:
      - OAuth - OpenID Connect - Clients
      summary: Marks Trust Relationship for deletion
      description: Marks Trust Relationship for deletion
      operationId: delete-shibboleth-trust-by-inum
      security:
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.delete
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.admin
  /shibboleth/trust-relationship/{fed-id}/discovery/entities:
    get:
      tags:
      - Shibboleth - Trust Relationship
      summary: Gets list of federation entity ID based on federation ID
      description: Gets list of federation entity ID based on federation ID
      operationId: get-entities-by-fed-id
      security:
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.readonly
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.write
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.admin
  /shibboleth/trust-relationship/{inum}release-policyeffective:
    get:
      tags:
      - Shibboleth - Trust Relaattributetionship
      summary: Get  list Trust Relationship
      description: Get attribute list Trust Relationship
      operationId: get-shibboleth-trust-attribute-list
      security:
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.readonly
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.write
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.admin
  /shibboleth/trust-relationship/{inum}saml-profiles:
    get:
      tags:
      - Shibboleth - Trust Relationship
      summary: Gets configured SAML profiles for a trust relationship
      description: Gets configured SAML profiles for a trust relationship
      operationId: get-shibboleth-trust-saml-profiles
      security:
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.readonly
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.write
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.admin
    put:
      tags:
      - Shibboleth - Trust Relationship
      summary: Updates configured SAML profiles for a trust relationship
      description: Updates configured SAML profiles for a trust relationship
      operationId: post-shibboleth-trust_1
      security:
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.write
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.admin
  /shibboleth/trust-relationship/{name}:
    get:
      tags:
      - Shibboleth - Trust Relationship
      summary: Gets trusted service providers by name.
      description: Gets list of trusted service providers by name
      operationId: get-shibboleth-trust-by-name
      security:
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.readonly
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.write
      - oauth2:
        - https://jans.io/oauth/config/shibboleth/trust.admin
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://{op-hostname}/.../token"
          scopes:
            https://jans.io/oauth/config/shibboleth.readonly: View Shibboleth related
              information
            https://jans.io/oauth/config/shibboleth.write: Manage Shibboleth related
              information
            https://jans.io/oauth/config/shibboleth.admin: Admin to manage Shibboleth
              related information
            https://jans.io/oauth/config/shibboleth/config.readonly: View Shibboleth
              config related information
            https://jans.io/oauth/config/shibboleth/config.write: Manage Shibboleth
              config related information
            https://jans.io/oauth/config/shibboleth/config.admin: Admin to manage
              Shibboleth config related information
            https://jans.io/oauth/config/shibboleth/trust.readonly: View Shibboleth
              trust relationship related information
            https://jans.io/oauth/config/shibboleth/trust.write: Manage Shibboleth
              trust relationship related information
            https://jans.io/oauth/config/shibboleth/trust.delete: Manage Shibboleth
              trust relationship related information
            https://jans.io/oauth/config/shibboleth/trust.admin: Admin to manage Shibboleth
              trust relationship related information
            https://jans.io/oauth/config/read-all: Super admin for viewing application
              resource information
            https://jans.io/oauth/config/write-all: Super admin for updating application
              resource information
            https://jans.io/oauth/config/delete-all: Super admin for deleting application
              resource information
