<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <title>Club Survey</title>
</head>
<body>
    <div class="container p-4">
        <div class="row">
        
            <div class="col-2"> </div>
            <div class="col-8">
                <h3 class="text-center">Thanks for participating. Your feedback is highly valued!</h3>
                <div class="text-center p-3">
                    <form method="post" enctype="application/x-www-form-urlencoded">
                        <button type="submit" class="btn btn-primary">Done</button>
                        </form>
                </div>
            </div>
            <div class="col-2"> </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>
</html>
