# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in cedarling.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rake-compiler"
gem "rb_sys", "~> 0.9.63"

gem "rspec", "~> 3.0"

gem 'pry'
