/*
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.2
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * GetClientTokenParams
 */


public class GetClientTokenParams {
  @SerializedName("op_configuration_endpoint")
  private String opConfigurationEndpoint = null;

  @SerializedName("op_host")
  private String opHost = null;

  @SerializedName("op_discovery_path")
  private String opDiscoveryPath = null;

  @SerializedName("scope")
  private List<String> scope = null;

  @SerializedName("client_id")
  private String clientId = null;

  @SerializedName("client_secret")
  private String clientSecret = null;

  @SerializedName("authentication_method")
  private String authenticationMethod = null;

  @SerializedName("algorithm")
  private String algorithm = null;

  @SerializedName("key_id")
  private String keyId = null;

  public GetClientTokenParams opConfigurationEndpoint(String opConfigurationEndpoint) {
    this.opConfigurationEndpoint = opConfigurationEndpoint;
    return this;
  }

   /**
   * The openid configuration endpoint URL. If missing, then &#x60;op_host&#x60; must be defined.
   * @return opConfigurationEndpoint
  **/
  @Schema(example = "https://op.example.com/acme/.well-known/openid-configuration", required = true, description = "The openid configuration endpoint URL. If missing, then `op_host` must be defined.")
  public String getOpConfigurationEndpoint() {
    return opConfigurationEndpoint;
  }

  public void setOpConfigurationEndpoint(String opConfigurationEndpoint) {
    this.opConfigurationEndpoint = opConfigurationEndpoint;
  }

  public GetClientTokenParams opHost(String opHost) {
    this.opHost = opHost;
    return this;
  }

   /**
   * Deprecated in favor of &#x60;op_configuration_endpoint&#x60;. It will be removed in future version(s). Provide the URL of OpenID Provider (OP) in this field. If missing, then &#x60;op_configuration_endpoint&#x60; must be defined.
   * @return opHost
  **/
  @Schema(example = "https://<ophostname>", description = "Deprecated in favor of `op_configuration_endpoint`. It will be removed in future version(s). Provide the URL of OpenID Provider (OP) in this field. If missing, then `op_configuration_endpoint` must be defined.")
  public String getOpHost() {
    return opHost;
  }

  public void setOpHost(String opHost) {
    this.opHost = opHost;
  }

  public GetClientTokenParams opDiscoveryPath(String opDiscoveryPath) {
    this.opDiscoveryPath = opDiscoveryPath;
    return this;
  }

   /**
   * Deprecated in favor of &#x60;op_configuration_endpoint&#x60;. It will be removed in future version(s). Provide path to the OpenID Connect Provider&#x27;s discovery document in this field. For example, if it is &#x27;https://example.com/.well-known/openid-configuration&#x27; then the path is blank. But if it is &#x27;https://example.com/oxauth/.well-known/openid-configuration&#x27; then the path is &#x27;/oxauth&#x27;
   * @return opDiscoveryPath
  **/
  @Schema(example = "/oxauth", description = "Deprecated in favor of `op_configuration_endpoint`. It will be removed in future version(s). Provide path to the OpenID Connect Provider's discovery document in this field. For example, if it is 'https://example.com/.well-known/openid-configuration' then the path is blank. But if it is 'https://example.com/oxauth/.well-known/openid-configuration' then the path is '/oxauth'")
  public String getOpDiscoveryPath() {
    return opDiscoveryPath;
  }

  public void setOpDiscoveryPath(String opDiscoveryPath) {
    this.opDiscoveryPath = opDiscoveryPath;
  }

  public GetClientTokenParams scope(List<String> scope) {
    this.scope = scope;
    return this;
  }

  public GetClientTokenParams addScopeItem(String scopeItem) {
    if (this.scope == null) {
      this.scope = new ArrayList<String>();
    }
    this.scope.add(scopeItem);
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  @Schema(example = "[\"openid\"]", description = "")
  public List<String> getScope() {
    return scope;
  }

  public void setScope(List<String> scope) {
    this.scope = scope;
  }

  public GetClientTokenParams clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @Schema(example = "@!1736.179E.AA60.16B2!0001!8F7C.B9AB!0008!A2BB.9AE6.5F14.B387", required = true, description = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public GetClientTokenParams clientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
    return this;
  }

   /**
   * Get clientSecret
   * @return clientSecret
  **/
  @Schema(example = "f436b936-03fc-433f-9772-53c2bc9e1c74", required = true, description = "")
  public String getClientSecret() {
    return clientSecret;
  }

  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }

  public GetClientTokenParams authenticationMethod(String authenticationMethod) {
    this.authenticationMethod = authenticationMethod;
    return this;
  }

   /**
   * if value is missed then basic authentication is used. Otherwise it&#x27;s possible to set &#x60;private_key_jwt&#x60; value for Private Key authentication.
   * @return authenticationMethod
  **/
  @Schema(description = "if value is missed then basic authentication is used. Otherwise it's possible to set `private_key_jwt` value for Private Key authentication.")
  public String getAuthenticationMethod() {
    return authenticationMethod;
  }

  public void setAuthenticationMethod(String authenticationMethod) {
    this.authenticationMethod = authenticationMethod;
  }

  public GetClientTokenParams algorithm(String algorithm) {
    this.algorithm = algorithm;
    return this;
  }

   /**
   * optional but is required if authentication_method&#x3D;private_key_jwt. Valid values are none, HS256, HS384, HS512, RS256, RS384, RS512, ES256, ES384, ES512
   * @return algorithm
  **/
  @Schema(description = "optional but is required if authentication_method=private_key_jwt. Valid values are none, HS256, HS384, HS512, RS256, RS384, RS512, ES256, ES384, ES512")
  public String getAlgorithm() {
    return algorithm;
  }

  public void setAlgorithm(String algorithm) {
    this.algorithm = algorithm;
  }

  public GetClientTokenParams keyId(String keyId) {
    this.keyId = keyId;
    return this;
  }

   /**
   * optional but is required if authentication_method&#x3D;private_key_jwt. It has to be valid key id from key store.
   * @return keyId
  **/
  @Schema(description = "optional but is required if authentication_method=private_key_jwt. It has to be valid key id from key store.")
  public String getKeyId() {
    return keyId;
  }

  public void setKeyId(String keyId) {
    this.keyId = keyId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetClientTokenParams getClientTokenParams = (GetClientTokenParams) o;
    return Objects.equals(this.opConfigurationEndpoint, getClientTokenParams.opConfigurationEndpoint) &&
        Objects.equals(this.opHost, getClientTokenParams.opHost) &&
        Objects.equals(this.opDiscoveryPath, getClientTokenParams.opDiscoveryPath) &&
        Objects.equals(this.scope, getClientTokenParams.scope) &&
        Objects.equals(this.clientId, getClientTokenParams.clientId) &&
        Objects.equals(this.clientSecret, getClientTokenParams.clientSecret) &&
        Objects.equals(this.authenticationMethod, getClientTokenParams.authenticationMethod) &&
        Objects.equals(this.algorithm, getClientTokenParams.algorithm) &&
        Objects.equals(this.keyId, getClientTokenParams.keyId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(opConfigurationEndpoint, opHost, opDiscoveryPath, scope, clientId, clientSecret, authenticationMethod, algorithm, keyId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetClientTokenParams {\n");
    
    sb.append("    opConfigurationEndpoint: ").append(toIndentedString(opConfigurationEndpoint)).append("\n");
    sb.append("    opHost: ").append(toIndentedString(opHost)).append("\n");
    sb.append("    opDiscoveryPath: ").append(toIndentedString(opDiscoveryPath)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    authenticationMethod: ").append(toIndentedString(authenticationMethod)).append("\n");
    sb.append("    algorithm: ").append(toIndentedString(algorithm)).append("\n");
    sb.append("    keyId: ").append(toIndentedString(keyId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
