**

!demos/
!demos/cedarling-js-examples/
!demos/cedarling-js-examples/**

demos/cedarling-js-examples/compose.yaml
demos/cedarling-js-examples/docker
demos/cedarling-js-examples/README.md
demos/cedarling-js-examples/**/README.md

!jans-cedarling/
!jans-cedarling/**

.git
**/.git
**/node_modules
**/target
**/dist
**/pkg
**/build
**/*.tgz
**/.next*
**/.wrangler*
**/.erb/dll
**/release
**/.vite
**/.cache
**/coverage
**/playwright-report
**/test-results
**/*.log
**/.env
**/.env.*
!**/.env.example
