export default {
    appIcon: require("../assets/images/appicon.png"),
    passCodeIcon: require("../assets/images/passcodeIcon.png"),
    homeScreenIcon: require("../assets/images/menu.png"),
    homeScreenScanImage: require("../assets/images/qr-code.png"),
    appIconWhite: require("../assets/images/app-icon-small.png"),
    leftIconWhite: require("../assets/images/angle-left.png"),
    rightIconGrey: require("../assets/images/angle-right-grey.png"),
    keyDrawerIcon: require("../assets/images/key.png"),
    logsDrawerIcon: require("../assets/images/logs.png"),
    passcodeDrawerIcon: require("../assets/images/passcode.png"),
    trustDrawerIcon: require("../assets/images/trust.png"),
    keyHeaderImage: require("../assets/images/icon_keys_large.png"),
    keyRowImage: require("../assets/images/icon_keys_large_green.png"),
    logHeaderImage: require("../assets/images/file.png"),
    logRowImage: require("../assets/images/icon_gluu_logo_log_details.png"),
    toggleOff: require("../assets/images/toggle-off.png"),
    toggleOn: require("../assets/images/toggle-on.png"),
    deleteIcon: require("../assets/images/delete-icon.png"),
    userIcon: require("../assets/images/user.png"),
    locationIcon: require("../assets/images/location.png"),
    clockIcon: require("../assets/images/clock.png"),
    linkIcon: require("../assets/images/link.png"),

}