export default {
    LANDING_PAGE: "Landing_Page",
    DRAWER_STACK: "DRAWER_STACK",
    LOGS: "LOGS",
    KEY: "KEYS",
    PASSCODE:"PASSCODE",
    TRUST_SSL:"TRUST_SSL",
    LOG_DETAILS: "LOG_DETAILS",
    KEY_DETAIL: "KEY_DETAIL",
    QR_SCAN :"QR_SCAN"
}