nameOverride: ""
fullnameOverride: ""

# -- Configuration for Gateway resource
gateway:
  # -- Enable Gateway API and create a Gateway resource (if disabled, you will have to create and manage the Gateway resource externally).
  enabled: true
  # -- Set the gatewayClassName corresponding to your installed controller.
  className: nginx
  # -- The name of the Gateway resource to be created
  name: jans-gateway
  # -- Gateway http port number
  httpPort: 80
  # -- Gateway https port number
  httpsPort: 443
  # -- Secret containing the TLS certificate for the Gateway
  tlsSecretName: tls-certificate
  # -- Attach global.lbIp to Gateway spec.addresses with IPAddress type (enable this if loadbalancer doesn't assign IP address to Gateway automatically)
  attachLbIp: false
  # -- Specific labels for the Gateway resource
  labels: {}
  # -- Specific annotations for the Gateway resource
  annotations: {}
  # -- Gateway spec.infrastructure
  infrastructure:
    # -- Specific parametersRef for the infrastructure
    # Some gateway implementation like `airlock-microgateway` may need to attach GatewayParameters to create Loadbalancer service automatically.
    parametersRef: {}
    # -- Specific labels for the infrastructure
    labels: {}
    # -- Specific annotations for the infrastructure
    annotations: {}
# -- Configuration for HTTPRoute and its related resources
routes:
  # -- Namespace where the Gateway resource resides. Set this ONLY if the Gateway is externally managed in a different namespace than this Helm release. If set, ensure the target namespace exists and your Gateway controller has the required cross-namespace RBAC permissions.
  gatewayNamespace: ""
  # -- Only set the httpSectionName and httpsSectionName if it doesn't work with the default values, according to your installed controller (e.g. some controller may require the listener name to be `default`).
  httpSectionName: http
  httpsSectionName: https
  # -- Specific labels for the HTTPRoute resource
  labels: {}
  # -- Specific annotations for the HTTPRoute resource
  annotations: {}
# -- Additional configuration for Specific Gateway API implementation
additionalConfig:
  # -- Configuration for NGINX Fabric.
  nginx:
    # -- Enable URL rewrite to proxy gRPC requests to /jans-auth.
    # Snippet support must be enabled during NGINX installation (otherwise endpoints will return HTTP status code 500).
    # See https://docs.nginx.com/nginx-gateway-fabric/traffic-management/snippets#setup
    enableGrpcRewriteSnippets: false
  # -- Configuration for Traefik.
  traefik: {}
  # -- Configuration for Istio.
  istio: {}
  # -- Configuration for kgateway.
  kgateway: {}
  # -- Configuration for Cilium.
  cilium:
    # -- Create Cilium IP pool with the specified blocks. See https://docs.cilium.io/en/stable/network/lb-ipam/ for details.
    ipPoolBlocks: []
  # -- Configuration for Airlock Microgateway
  airlock:
    # -- Create LoadBalancer service using GatewayParameters (by default airlock-microgateway doesn't create the service).
    # See https://docs.airlock.com/microgateway/latest/index/api/crds/gateway-parameters/v1alpha1/ for details.
    # The GatewayParameters will be attached to gateway.infrastructure.parametersRef only if it's empty.
    createLbService: false
  # -- Configuration for Envoy.
  envoy:
    # -- Create GatewayClass named `envoy` (by default Envoy doesn't create gatewayclass). The `envoy` name can be set as value of `gateway.className` attribute.
    createGatewayClass: false
