#!/usr/bin/python
# The MIT License (MIT)
#
# Copyright (c) 2014 Gluu
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import sys
import subprocess
import traceback

# chkconfig: 345 95 5
# description: OpenDJ LDAP init script

opendj_bin = "/opt/opendj/bin"

def run(args):
    print 'Running: %s' % ' '.join(args)
    try:
        p = subprocess.Popen(args, stdout=subprocess.PIPE)
        output, err = p.communicate()
        if output: print output
        if err: print err
    except:
        print "Error running command : %s" % " ".join(args),
        print traceback.format_exc()

cmd = sys.argv[1]
if cmd == "stop":
    run(['/bin/su', 'ldap', '-c', 'cd /opt/opendj/bin ; /opt/opendj/bin/stop-ds'])
if cmd == "start":
    run(['/bin/su', 'ldap', '-c', 'cd /opt/opendj/bin ; /opt/opendj/bin/start-ds'])
if cmd == "status":
    run(['/bin/su', 'ldap', '-c', 'cd /opt/opendj/bin ; /opt/opendj/bin/status'])
if cmd == "restart":
    run(['/bin/su', 'ldap', '-c', 'cd /opt/opendj/bin ; /opt/opendj/bin/stop-ds'])
    run(['/bin/su', 'ldap', '-c', 'cd /opt/opendj/bin ; /opt/opendj/bin/start-ds'])
