#!/usr/bin/env bash
# Startup script for jans-client-api-server under *nix systems (it works under NT/cygwin too).
# LSB Tags
### BEGIN INIT INFO
# Provides:          jans-client-api-server
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: jans-client-api-server start script.
# Description:       jans-client-api-server exposes simple, static APIs web application developers can use to implement user authentication and authorization against an OAuth 2.0 authorization server like Gluu.
### END INIT INFO


# Read config
source /etc/default/client-api

##################################################
# Set the name which is used by other variables.
# Defaults to the file name without extension.
##################################################
NAME=$(echo $(basename $0) | sed -e 's/^[SK][0-9]*//' -e 's/\.sh$//')

# To get the service to restart correctly on reboot, uncomment below (3 lines):
# ========================
# chkconfig: 3 99 99
# description: jans-client-api server
# processname: jans-client-api-server
# ========================

# Configuration files
#
# /etc/default/$NAME
#   If it exists, this is read at the start of script. It may perform any
#   sequence of shell commands, like setting relevant environment variables.
#
# $HOME/.$NAMErc (e.g. $HOME/.jans-client-api-serverrc)
#   If it exists, this is read at the start of script. It may perform any
#   sequence of shell commands, like setting relevant environment variables.
#
#   The files will be checked for existence before being passed to jans-client-api-server.
#
# Configuration variables
#
# JAVA
#   Command to invoke Java. If not set, java (from the PATH) will be used.
#
# JAVA_OPTIONS
#   Extra options to pass to the JVM
#
# JANS_CLIENT_API_HOME
#   Where jans_client_api is installed. If not set, the script will try go
#   guess it by looking at the invocation path for the script
#
# JANS_CLIENT_API_BASE
#   Where your jans-client-api server base directory is.  If not set, the value from
#   $JANS_CLIENT_API_HOME will be used.
#
# JANS_CLIENT_API_RUN
#   Where the $NAME.pid file should be stored. It defaults to the
#   first available of /var/run, /usr/var/run JANS_CLIENT_API_BASE and /tmp
#   if not set.
#
# JANS_CLIENT_API_PID_FILE
#   The jans-client-api-server PID file, defaults to $JANS_CLIENT_API_RUN/$NAME.pid
#
# JANS_CLIENT_API_ARGS
#   The default arguments to pass to jans-client-api-server.
#
# JANS_CLIENT_API_USER
#   if set, then used as a username to run the server as
#
# JANS_CLIENT_API_SHELL
#   If set, then used as the shell by su when starting the server.  Will have
#   no effect if start-stop-daemon exists.  Useful when JANS_CLIENT_API_USER does not
#   have shell access, e.g. /bin/false
#
# JANS_CLIENT_API_INIT_LOG

usage()
{
    echo "Usage: ${0##*/} [-d] {start|stop|run|restart|check|supervise} [ CONFIGS ... ] "
    exit 1
}

[ $# -gt 0 ] || usage


##################################################
# Some utility functions
##################################################
findDirectory()
{
  local L OP=$1
  shift
  for L in "$@"; do
    [ "$OP" "$L" ] || continue
    printf %s "$L"
    break
  done
}

running()
{
  if [ -f "$1" ]
  then
    local PID=$(cat "$1" 2>/dev/null) || return 1
    kill -0 "$PID" 2>/dev/null
    return
  fi
  rm -f "$1"
  return 1
}

started()
{
  # wait for 60s to see "STARTED" in PID file
  for T in 1 2 3 4 5 6 7 9 10 11 12 13 14 15
  do
    sleep 4
    [ -z "$(grep STARTED $1 2>/dev/null)" ] || return 0
    [ -z "$(grep STOPPED $1 2>/dev/null)" ] || return 1
    [ -z "$(grep FAILED $1 2>/dev/null)" ] || return 1
    local PID=$(cat "$2" 2>/dev/null) || return 1
    kill -0 "$PID" 2>/dev/null || return 1
    echo -n ". "
  done

  return 1;
}


readConfig()
{
  (( DEBUG )) && echo "Reading $1.."
  source "$1"
}



##################################################
# Get the action & configs
##################################################
CONFIGS=()
NO_START=0
DEBUG=0

while [[ $1 = -* ]]; do
  case $1 in
    -d) DEBUG=1 ;;
  esac
  shift
done
ACTION=$1
shift

##################################################
# Read any configuration files
##################################################
ETC=/etc
if [ $UID != 0 ]
then
  ETC=$HOME/etc
fi

for CONFIG in {/etc,~/etc}/default/${NAME}{,9} $HOME/.${NAME}rc; do
  if [ -f "$CONFIG" ] ; then
    readConfig "$CONFIG"
  fi
done


##################################################
# Set tmp if not already set.
##################################################
TMPDIR=${TMPDIR:-/tmp}

##################################################
# jans-client-api-server's hallmark
##################################################
JANS_CLIENT_API_INSTALL_TRACE_FILE="jans-client-api-server.jar"


##################################################
# Try to determine JANS_CLIENT_API_HOME if not set
##################################################
if [ -z "$JANS_CLIENT_API_HOME" ]
then
  JANS_CLIENT_API_SH=$0
  case "$JANS_CLIENT_API_SH" in
    /*)     JANS_CLIENT_API_HOME=${JANS_CLIENT_API_SH%/*/*} ;;
    ./*/*)  JANS_CLIENT_API_HOME=${JANS_CLIENT_API_SH%/*/*} ;;
    ./*)    JANS_CLIENT_API_HOME=.. ;;
    */*/*)  JANS_CLIENT_API_HOME=./${JANS_CLIENT_API_SH%/*/*} ;;
    */*)    JANS_CLIENT_API_HOME=. ;;
    *)      JANS_CLIENT_API_HOME=.. ;;
  esac

  if [ ! -f "$JANS_CLIENT_API_HOME/lib/$JANS_CLIENT_API_INSTALL_TRACE_FILE" ]
  then
    JANS_CLIENT_API_HOME=
  fi
fi


##################################################
# No JANS_CLIENT_API_HOME yet? We're out of luck!
##################################################
if [ -z "$JANS_CLIENT_API_HOME" ]; then
  echo "** ERROR: JANS_CLIENT_API_HOME not set, you need to set it or install in a standard location"
  exit 1
fi

cd "$JANS_CLIENT_API_HOME"
JANS_CLIENT_API_HOME=$PWD


##################################################
# Set JANS_CLIENT_API_BASE
##################################################
if [ -z "$JANS_CLIENT_API_BASE" ]; then
  JANS_CLIENT_API_BASE=$JANS_CLIENT_API_HOME
fi

cd "$JANS_CLIENT_API_BASE"
JANS_CLIENT_API_BASE=$PWD


#####################################################
# Check that jans-client-api server is where we think it is
#####################################################
if [ ! -r "$JANS_CLIENT_API_HOME/lib/$JANS_CLIENT_API_INSTALL_TRACE_FILE" ]
then
  echo "** ERROR: Oops! jans-client-api server doesn't appear to be installed in $JANS_CLIENT_API_HOME"
  echo "** ERROR:  $JANS_CLIENT_API_HOME/lib/$JANS_CLIENT_API_INSTALL_TRACE_FILE is not readable!"
  exit 1
fi

#####################################################
# Find a location for the pid file
#####################################################
if [ -z "$JANS_CLIENT_API_RUN" ]
then
  JANS_CLIENT_API_RUN=$(findDirectory -w /var/run /usr/var/run $JANS_CLIENT_API_BASE /tmp)
fi

#####################################################
# Find a pid and state file
#####################################################
if [ -z "$JANS_CLIENT_API_PID_FILE" ]
then
  JANS_CLIENT_API_PID_FILE="$JANS_CLIENT_API_RUN/${NAME}.pid"
fi

get_pid() {
        if [ -f $JANS_CLIENT_API_PID_FILE ]; then
                PID_NUM=$(cat $JANS_CLIENT_API_PID_FILE)
                echo "$PID_NUM"
        else
                PID_NUM="`ps -eaf|grep -i java|grep -v grep|grep -i 'client-api-conf.json'|awk '{print $2}'`"
                ###For one more possible bug, find and kill jans-client-api-server
                if [ "x$PID_NUM" != "x" ]; then
                        echo "$PID_NUM"
                fi
        fi
}

if [ -z "$JANS_CLIENT_API_STATE" ]
then
  JANS_CLIENT_API_STATE=$JANS_CLIENT_API_BASE/${NAME}.state
fi

case "`uname`" in
CYGWIN*) JANS_CLIENT_API_STATE="`cygpath -w $JANS_CLIENT_API_STATE`";;
esac


JANS_CLIENT_API_ARGS=(${JANS_CLIENT_API_ARGS[*]} "jans-client-api-server.state=$JANS_CLIENT_API_STATE")

##################################################
# Setup JAVA if unset
##################################################
if [ -z "$JAVA" ]
then
  JAVA=$(which java)
fi

if [ ! -f "$JAVA" ]
then
  JAVA=$(which java)
fi

if [ -z "$JAVA" ]
then
  echo "Cannot find a Java JDK. Please either set JAVA or put java (>=1.8) in your PATH." >&2
  exit 1
fi

if [[ "$JAVA" ]]; then
    version=$("$JAVA" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    response=`awk "BEGIN { print ($version < 1.8) ? \"YES\" : \"NO\" }"`
    if [[ $response = "YES" ]]; then
        echo "JAVA version is $version. Please set java (>=1.8)." >&2
        exit 1
    fi
fi

#####################################################
# See if JANS_CLIENT_API_LOGS is defined
#####################################################
if [ -z "$JANS_CLIENT_API_LOGS" ] && [ -d $JANS_CLIENT_API_BASE/logs ]
then
  JANS_CLIENT_API_LOGS=$JANS_CLIENT_API_BASE/logs
fi
if [ -z "$JANS_CLIENT_API_LOGS" ] && [ -d $JANS_CLIENT_API_HOME/logs ]
then
  JANS_CLIENT_API_LOGS=$JANS_CLIENT_API_HOME/logs
fi
if [ "$JANS_CLIENT_API_LOGS" ]
then

  case "`uname`" in
  CYGWIN*) JANS_CLIENT_API_LOGS="`cygpath -w $JANS_CLIENT_API_LOGS`";;
  esac

  #JAVA_OPTIONS=(${JAVA_OPTIONS[*]} "-Djans-client-api-server.logging.dir=$JANS_CLIENT_API_LOGS")
fi

#####################################################
# Are we running on Windows? Could be, with Cygwin/NT.
#####################################################
case "`uname`" in
CYGWIN*) PATH_SEPARATOR=";";;
*) PATH_SEPARATOR=":";;
esac


#####################################################
# Add jans-client-api server properties to Java VM options.
#####################################################

case "`uname`" in
CYGWIN*)
JANS_CLIENT_API_HOME="`cygpath -w $JANS_CLIENT_API_HOME`"
JANS_CLIENT_API_BASE="`cygpath -w $JANS_CLIENT_API_BASE`"
TMPDIR="`cygpath -w $TMPDIR`"
;;
esac

#JAVA_OPTIONS=(${JAVA_OPTIONS[*]} "-Djans-client-api-server.home=$JANS_CLIENT_API_HOME" "-DJANS_CLIENT_API.base=$JANS_CLIENT_API_BASE" "-Djava.io.tmpdir=$TMPDIR")
#####################################################
# This is how the jans-client-api server will be started
#####################################################

JANS_CLIENT_API_START="ServerLauncher"

case "`uname`" in
CYGWIN*) JANS_CLIENT_API_START="`cygpath -w $JANS_CLIENT_API_START`";;
esac

RUN_ARGS=(${JAVA_OPTIONS[@]} "$JANS_CLIENT_API_START" ${JANS_CLIENT_API_ARGS[*]})
RUN_CMD=("$JAVA" ${RUN_ARGS[@]})

#####################################################
# Comment these out after you're happy with what
# the script is doing.
#####################################################
if (( DEBUG ))
then
  echo "JANS_CLIENT_API_HOME     =  $JANS_CLIENT_API_HOME"
  echo "JANS_CLIENT_API_BASE     =  $JANS_CLIENT_API_BASE"
  echo "JANS_CLIENT_API_CONF     =  $JANS_CLIENT_API_CONF"
  echo "JANS_CLIENT_API_PID_FILE =  $JANS_CLIENT_API_PID_FILE"
  echo "JANS_CLIENT_API_START    =  $JANS_CLIENT_API_START"
  echo "JANS_CLIENT_API_ARGS     =  ${JANS_CLIENT_API_ARGS[*]}"
  echo "JAVA_OPTIONS =  ${JAVA_OPTIONS[*]}"
  echo "JAVA         =  $JAVA"
  echo "RUN_CMD      =  ${RUN_CMD[*]}"
fi
dip_in_logs() {
	if [ ! -f $JANS_CLIENT_API_INIT_LOG ]; then
		sleep 10
	fi
	echo "Checking logs for possible errors:"
	INIT_START_STATUS=`tail -n 1 $JANS_CLIENT_API_INIT_LOG`
	while true;
	do
		if [ "x$INIT_START_STATUS" != "x" ]; then
			if [ "x$PREV_START_STATUS" = "x" ]; then
				PREV_START_STATUS=$INIT_START_STATUS
				sleep 10
				INIT_START_STATUS=`tail -n 1 $JANS_CLIENT_API_INIT_LOG`
			fi
		fi
		if [ "$INIT_START_STATUS" != "$PREV_START_STATUS" ]; then
			PREV_START_STATUS=$INIT_START_STATUS	
			sleep 10
			INIT_START_STATUS=`tail -n 1 $JANS_CLIENT_API_INIT_LOG`
		else
			break;
		fi
	done	
}

do_start () {
        PID_NUM=`get_pid`
        if [ "x$PID_NUM" = "x" ]; then
                echo "Starting $SERVICE_NAME:"

    		if [ $UID -eq 0 ] && type start-stop-daemon > /dev/null 2>&1
    		then
      			unset CH_USER
      			if [ -n "$JANS_CLIENT_API_USER" ]
      			then
        			CH_USER="-c$JANS_CLIENT_API_USER"
      			fi

			start-stop-daemon --start --quiet --chuid $JANS_CLIENT_API_USER --make-pidfile --pidfile $JANS_CLIENT_API_PID_FILE --background --exec $JAVA -- ${JAVA_OPTIONS[@]} >> $JANS_CLIENT_API_LOGS/start.log 2>&1

			#dip_in_logs
			sleep 4
			for i in `seq 1 24`;
                        do
                	        START_STATUS=`tail -n 4 $JANS_CLIENT_API_INIT_LOG|grep -i 'o.e.j.s.Server -  Started'` > /dev/null 2>&1
                	        ERROR_STATUS=`tail -n 10 $JANS_CLIENT_API_INIT_LOG|egrep -i "Failed to start jans-client-api server|Error"` > /dev/null 2>&1
			        if [ "x$START_STATUS" != "x" ] || [ "x$ERROR_STATUS" != "x" ]; then
		         	        break
		         	fi
				sleep 5
                        done
                	if [ "x$START_STATUS" = "x" ]; then
                        	###If by chance log file doesn't provide necessary string, sleep another 10 seconds and check again PID of process
                        	if [ "x$ERROR_STATUS" != "x" ]; then
                                	### Since error occurred, we should remove the PID file at this point itself.
					kill -9 `cat $JANS_CLIENT_API_PID_FILE` > /dev/null 2>&1
					rm -f  $JANS_CLIENT_API_PID_FILE
                                	echo "Some errors encountered..."
                                	echo "See log below: "
                                	echo ""
                                	echo "$ERROR_STATUS"
                                	echo ""
                                	echo "For details please check $JANS_CLIENT_API_INIT_LOG ."
                                	echo "Exiting..."
                                	exit 1
				else
                                	### Since error occurred, we should remove the PID file at this point itself.
					kill -9 `cat $JANS_CLIENT_API_PID_FILE` > /dev/null 2>&1
					rm -f  $JANS_CLIENT_API_PID_FILE
                                	echo "Some errors encountered..."
                                	echo ""
                                	echo "Exiting..."
                                	exit 1				   
                        	fi
	
                	fi
        		chown "$JANS_CLIENT_API_USER" "$JANS_CLIENT_API_PID_FILE" > /dev/null 2>&1
		else
      			if [ -n "$JANS_CLIENT_API_USER" ] && [ `whoami` != "$JANS_CLIENT_API_USER" ]
      			then
        			unset SU_SHELL
        			if [ "$JANS_CLIENT_API_SHELL" ]
        			then
          				SU_SHELL="-s $JANS_CLIENT_API_SHELL"
        			fi

        			touch "$JANS_CLIENT_API_PID_FILE"
        			chown "$JANS_CLIENT_API_USER" "$JANS_CLIENT_API_PID_FILE"
        			# FIXME: Broken solution: wordsplitting, pathname expansion, arbitrary command execution, etc.
        			su - "$JANS_CLIENT_API_USER" $SU_SHELL -c "
				exec $JAVA ${JAVA_OPTIONS[@]} >> "$JANS_CLIENT_API_LOGS/start.log" 2>&1 &
          			disown \$!
          			echo \$! > '$JANS_CLIENT_API_PID_FILE'"
				#dip_in_logs
			        sleep 4
			        for i in `seq 1 24`;
                                do
                		        START_STATUS=`tail -n 4 $JANS_CLIENT_API_INIT_LOG|grep -i 'o.e.j.s.Server -  Started'` > /dev/null 2>&1
                		        ERROR_STATUS=`tail -n 10 $JANS_CLIENT_API_INIT_LOG|egrep -i "Failed to start jans-client-api server|Error"` > /dev/null 2>&1
			                if [ "x$START_STATUS" != "x" ] || [ "x$ERROR_STATUS" != "x" ]; then
		         	                break
		                 	fi
				        sleep 5
                                done					
                		if [ "x$START_STATUS" = "x" ]; then
	                        	###If by chance log file doesn't provide necessary string, sleep another 10 seconds and check again PID of process
	                        	if [ "x$ERROR_STATUS" != "x" ]; then
	                                	### Since error occurred, we should remove the PID file at this point itself.
						kill -9 `cat $JANS_CLIENT_API_PID_FILE` > /dev/null 2>&1
						rm -f  $JANS_CLIENT_API_PID_FILE
	                                	echo "Some errors encountered..."
	                                	echo "See log below: "
	                                	echo ""
	                                	echo "$ERROR_STATUS"
	                                	echo ""
	                                	echo "For details please check $JANS_CLIENT_API_INIT_LOG ."
	                                	echo "Exiting..."
	                                	exit 1
					else
	                                	### Since error occurred, we should remove the PID file at this point itself.
						kill -9 `cat $JANS_CLIENT_API_PID_FILE` > /dev/null 2>&1
						rm -f  $JANS_CLIENT_API_PID_FILE
	                                	echo "Some errors encountered..."
	                                	echo ""
	                                	echo "Exiting..."
	                                	exit 1				   
	                        	fi	
	                	fi
      			else
        			$JAVA ${JAVA_OPTIONS[@]} > /dev/null &
        			disown $!
        			echo $! > "$JANS_CLIENT_API_PID_FILE"
      			fi
               	fi 	
        	echo "PID: [`get_pid`]"
        	echo "OK `date`"
       	else
                if netstat -tulpn | grep "$PID_NUM/java"; then
                        echo "$SERVICE_NAME is already running ..."
                        echo "PID: [$PID_NUM]"
                        exit 1
                else
                        kill -9 `cat $JANS_CLIENT_API_PID_FILE` > /dev/null 2>&1
                        rm -f  $JANS_CLIENT_API_PID_FILE
                        do_start
                        exit 0
                fi
	fi
}

do_stop () {
	PID_NUM=`get_pid`
        if [ "x$PID_NUM" != "x" ]; then 
    		echo -n "Stopping $SERVICE_NAME: "
    		if [ $UID -eq 0 ] && type start-stop-daemon > /dev/null 2>&1; then
      			start-stop-daemon -K -p"$JANS_CLIENT_API_PID_FILE" -d"$JANS_CLIENT_API_HOME" -a "$JAVA" -s HUP

      			TIMEOUT=30
      			while running "$JANS_CLIENT_API_PID_FILE"; do
        			if (( TIMEOUT-- == 0 )); then
          				start-stop-daemon -K -p"$JANS_CLIENT_API_PID_FILE" -d"$JANS_CLIENT_API_HOME" -a "$JAVA" -s KILL
        			fi

        			sleep 1
      			done
    		else
      			if [ ! -f "$JANS_CLIENT_API_PID_FILE" ] ; then
        			echo "ERROR: no pid found at $JANS_CLIENT_API_PID_FILE"
        			exit 1
      			fi

      			PID=$(cat "$JANS_CLIENT_API_PID_FILE" 2>/dev/null)
      			if [ -z "$PID" ] ; then
        			echo "ERROR: no pid id found in $JANS_CLIENT_API_PID_FILE"
        			exit 1
      			fi
      			kill "$PID" 2>/dev/null

      			TIMEOUT=30
      			while running $JANS_CLIENT_API_PID_FILE; do
        			if (( TIMEOUT-- == 0 )); then
          				kill -KILL "$PID" 2>/dev/null
        			fi

        			sleep 1
      			done
    		fi

    		rm -f "$JANS_CLIENT_API_PID_FILE"
    		rm -f "$JANS_CLIENT_API_STATE"
    		echo OK
	else
                echo "$SERVICE_NAME is not running ..."     
		exit 1
	fi
}
##################################################
# Do the action
##################################################
case "$ACTION" in
  start)
	do_start
    ;;

  stop)
	do_stop
    ;;

  restart)
    JANS_CLIENT_API_SH=$0
    > "$JANS_CLIENT_API_STATE"

    "$JANS_CLIENT_API_SH" stop "$@"
    "$JANS_CLIENT_API_SH" start "$@"

    ;;

  supervise)
    #
    # Under control of daemontools supervise monitor which
    # handles restarts and shutdowns via the svc program.
    #
    exec "${RUN_CMD[@]}"

    ;;

  run|demo)
    echo "Running jans-client-api server: "

    if running "$JANS_CLIENT_API_PID_FILE"
    then
      echo Already Running $(cat "$JANS_CLIENT_API_PID_FILE")!
      exit 1
    fi

    exec "${RUN_CMD[@]}"
    ;;

  check|status)
    if running "$JANS_CLIENT_API_PID_FILE"
    then
      echo "jans-client-api server running pid=$(< "$JANS_CLIENT_API_PID_FILE")"
    else
      echo "jans-client-api server NOT running"
    fi
    echo
    echo "JANS_CLIENT_API_HOME     =  $JANS_CLIENT_API_HOME"
    echo "JANS_CLIENT_API_BASE     =  $JANS_CLIENT_API_BASE"
    echo "JANS_CLIENT_API_CONF     =  $JANS_CLIENT_API_CONF"
    echo "JANS_CLIENT_API_PID_FILE =  $JANS_CLIENT_API_PID_FILE"
    echo "JANS_CLIENT_API_START    =  $JANS_CLIENT_API_START"
    echo "JANS_CLIENT_API_LOGS     =  $JANS_CLIENT_API_LOGS"
    echo "JANS_CLIENT_API_STATE    =  $JANS_CLIENT_API_STATE"
    echo "CLASSPATH    =  $CLASSPATH"
    echo "JAVA         =  $JAVA"
    echo "JAVA_OPTIONS =  ${JAVA_OPTIONS[*]}"
    echo "JANS_CLIENT_API_ARGS     =  ${JANS_CLIENT_API_ARGS[*]}"
    echo "RUN_CMD      =  ${RUN_CMD[*]}"
    echo

    if running "$JANS_CLIENT_API_PID_FILE"
    then
      exit 0
    fi
    exit 1

    ;;

  *)
    usage

    ;;
esac

exit 0
