#!/bin/sh -e

if [ "$1" = upgrade ] || [ "$1" = install ]; then
    # Stopping oxd-server
    # This will stop jans-client-api-server before upgrade|install
    if [ -e /var/run/client-api.pid ]; then
        kill -9 `cat /var/run/client-api.pid` > /dev/null 2>&1
        rm -rf /var/run/client-api.pid > /dev/null 2>&1
    fi

fi
exit 0
