#!/bin/sh -e

# Stopping jans-client-api-server
if [ -e /var/run/client-api.pid ]; then
    kill -9 `cat /var/run/client-api.pid` > /dev/null 2>&1
    rm -rf /var/run/client-api.pid > /dev/null 2>&1
fi

if [ -e /etc/init.d/client-api ]; then
    update-rc.d client-api remove > /dev/null 2>&1
fi

if [ -e /lib/systemd/system/client-api.service ]; then
    systemctl disable client-api > /dev/null 2>&1
fi

exit 0
