# coding: utf-8

"""
    SCIM API

    Gluu SCIM 2.0 server API. Developers can think of SCIM as a REST API with endpoints exposing CRUD functionality (create, update, retrieve and delete) for identity management resources such as users, groups, and fido devices.   # noqa: E501

    OpenAPI spec version: 4.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.base_resource import BaseResource  # noqa: F401,E501

class GroupResource(BaseResource):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'display_name': 'str',
        'members': 'list[Member]'
    }
    if hasattr(BaseResource, "swagger_types"):
        swagger_types.update(BaseResource.swagger_types)

    attribute_map = {
        'display_name': 'displayName',
        'members': 'members'
    }
    if hasattr(BaseResource, "attribute_map"):
        attribute_map.update(BaseResource.attribute_map)

    def __init__(self, display_name=None, members=None, *args, **kwargs):  # noqa: E501
        """GroupResource - a model defined in Swagger"""  # noqa: E501
        self._display_name = None
        self._members = None
        self.discriminator = None
        if display_name is not None:
            self.display_name = display_name
        if members is not None:
            self.members = members
        BaseResource.__init__(self, *args, **kwargs)

    @property
    def display_name(self):
        """Gets the display_name of this GroupResource.  # noqa: E501


        :return: The display_name of this GroupResource.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this GroupResource.


        :param display_name: The display_name of this GroupResource.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def members(self):
        """Gets the members of this GroupResource.  # noqa: E501


        :return: The members of this GroupResource.  # noqa: E501
        :rtype: list[Member]
        """
        return self._members

    @members.setter
    def members(self, members):
        """Sets the members of this GroupResource.


        :param members: The members of this GroupResource.  # noqa: E501
        :type: list[Member]
        """

        self._members = members

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GroupResource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
