# coding: utf-8

"""
    SCIM API

    Gluu SCIM 2.0 server API. Developers can think of SCIM as a REST API with endpoints exposing CRUD functionality (create, update, retrieve and delete) for identity management resources such as users, groups, and fido devices.   # noqa: E501

    OpenAPI spec version: 4.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Member(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ref': 'str',
        'type': 'str',
        'display': 'str',
        'value': 'str'
    }

    attribute_map = {
        'ref': '$ref',
        'type': 'type',
        'display': 'display',
        'value': 'value'
    }

    def __init__(self, ref=None, type=None, display=None, value=None):  # noqa: E501
        """Member - a model defined in Swagger"""  # noqa: E501
        self._ref = None
        self._type = None
        self._display = None
        self._value = None
        self.discriminator = None
        if ref is not None:
            self.ref = ref
        if type is not None:
            self.type = type
        if display is not None:
            self.display = display
        if value is not None:
            self.value = value

    @property
    def ref(self):
        """Gets the ref of this Member.  # noqa: E501


        :return: The ref of this Member.  # noqa: E501
        :rtype: str
        """
        return self._ref

    @ref.setter
    def ref(self, ref):
        """Sets the ref of this Member.


        :param ref: The ref of this Member.  # noqa: E501
        :type: str
        """

        self._ref = ref

    @property
    def type(self):
        """Gets the type of this Member.  # noqa: E501


        :return: The type of this Member.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Member.


        :param type: The type of this Member.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def display(self):
        """Gets the display of this Member.  # noqa: E501


        :return: The display of this Member.  # noqa: E501
        :rtype: str
        """
        return self._display

    @display.setter
    def display(self, display):
        """Sets the display of this Member.


        :param display: The display of this Member.  # noqa: E501
        :type: str
        """

        self._display = display

    @property
    def value(self):
        """Gets the value of this Member.  # noqa: E501


        :return: The value of this Member.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Member.


        :param value: The value of this Member.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Member, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Member):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
