# coding: utf-8

# flake8: noqa
"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.error_response import ErrorResponse
from swagger_client.models.ldap_configuration import LdapConfiguration
from swagger_client.models.patch_request import PatchRequest
from swagger_client.models.scope import Scope
from swagger_client.models.scope_attributes import ScopeAttributes
