# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthenticationMethod(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'default_acr': 'str'
    }

    attribute_map = {
        'default_acr': 'defaultAcr'
    }

    def __init__(self, default_acr=None):  # noqa: E501
        """AuthenticationMethod - a model defined in Swagger"""  # noqa: E501
        self._default_acr = None
        self.discriminator = None
        if default_acr is not None:
            self.default_acr = default_acr

    @property
    def default_acr(self):
        """Gets the default_acr of this AuthenticationMethod.  # noqa: E501

        This field controls the default authentication mechanism that is presented to users from all applications that leverage Janssen Server for authentication.  # noqa: E501

        :return: The default_acr of this AuthenticationMethod.  # noqa: E501
        :rtype: str
        """
        return self._default_acr

    @default_acr.setter
    def default_acr(self, default_acr):
        """Sets the default_acr of this AuthenticationMethod.

        This field controls the default authentication mechanism that is presented to users from all applications that leverage Janssen Server for authentication.  # noqa: E501

        :param default_acr: The default_acr of this AuthenticationMethod.  # noqa: E501
        :type: str
        """

        self._default_acr = default_acr

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthenticationMethod, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthenticationMethod):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
