# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CustomAttribute(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'multi_valued': 'bool',
        'values': 'list[str]'
    }

    attribute_map = {
        'name': 'name',
        'multi_valued': 'multiValued',
        'values': 'values'
    }

    def __init__(self, name=None, multi_valued=None, values=None):  # noqa: E501
        """CustomAttribute - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._multi_valued = None
        self._values = None
        self.discriminator = None
        self.name = name
        self.multi_valued = multi_valued
        self.values = values

    @property
    def name(self):
        """Gets the name of this CustomAttribute.  # noqa: E501

        Name of the attribute.  # noqa: E501

        :return: The name of this CustomAttribute.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CustomAttribute.

        Name of the attribute.  # noqa: E501

        :param name: The name of this CustomAttribute.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def multi_valued(self):
        """Gets the multi_valued of this CustomAttribute.  # noqa: E501

        Indicates if the attribute can hold multiple values.  # noqa: E501

        :return: The multi_valued of this CustomAttribute.  # noqa: E501
        :rtype: bool
        """
        return self._multi_valued

    @multi_valued.setter
    def multi_valued(self, multi_valued):
        """Sets the multi_valued of this CustomAttribute.

        Indicates if the attribute can hold multiple values.  # noqa: E501

        :param multi_valued: The multi_valued of this CustomAttribute.  # noqa: E501
        :type: bool
        """
        if multi_valued is None:
            raise ValueError("Invalid value for `multi_valued`, must not be `None`")  # noqa: E501

        self._multi_valued = multi_valued

    @property
    def values(self):
        """Gets the values of this CustomAttribute.  # noqa: E501


        :return: The values of this CustomAttribute.  # noqa: E501
        :rtype: list[str]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this CustomAttribute.


        :param values: The values of this CustomAttribute.  # noqa: E501
        :type: list[str]
        """
        if values is None:
            raise ValueError("Invalid value for `values`, must not be `None`")  # noqa: E501

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomAttribute, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomAttribute):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
