<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head> <style> body{font-size:larger} input[type="submit"]{font-size:large;padding:0 1rem 0 1rem} </style> </head>
<body>
    <h1>You have been rejected. Try again in 10 years</h1>
    
    <h2>You have too much or no interests!</h2>
    <form method="post" enctype="application/x-www-form-urlencoded">
        <input type="submit" value="No problem">
    </form>
</body>
</html>
