#!/usr/bin/expect -f

set HOST [lindex $argv 0]
set USERNAME [lindex $argv 1]
set timeout -1
spawn $env(SHELL)
match_max 100000
expect  "$"
send -- "ssh ${USERNAME}@${HOST}"
expect -exact "${HOST}"
send -- "\r"
expect -re "(.*)\n"
send -- "curl https://raw.githubusercontent.com/JanssenProject/jans/main/jans-linux-setup/jans_setup/install.py > install.py"
expect -exact "curl https://raw.githubusercontent.com/JanssenProject/jans/main/jans-linux-setup/jans_setup/install.py > install.py"
send -- "\r"
expect -re "(.*)\n"
send -- "python3 install.py"
expect -exact "python3 install.py"
send -- "\r"

if  { $expect_out(buffer) eq  "Install now? \[Y\/n\]" }  {
send -- "y\r"
}
expect -re "(.*)\n"
#expect "Proceed anyways? \[Y\|n\] "
send -- "y\r"

expect -re "(.*)\n"
send -- "y\r"
expect -re "(.*)\n" 

send -- "\r"
expect -re "(.*)\n"

send -- "\r"
expect  -exact "\r
Enter your city or locality : "
send -- "pune"
expect  "pune"
send -- "\r"

expect -exact "Enter your state or province two letter code : "
send -- "mh\r"

expect "Enter two letter Country Code : "
send -- "91"
expect -exact "91"
send -- "\r"

expect "Enter Organization Name : "
send -- "glu\r"
expect "Enter email address for support at your organization : "
send -- "manojsurya78@gmail.com"
expect  "manojsurya78@gmail.com"
send -- "\r"
expect " : "
send -- "\r"
expect -exact "\r
Chose Backend Type:\r
  1 Local OpenDj\r
  2 Remote OpenDj\r
  3 Local MySQL\r
  4 Remote MySQL\r
  5 Remote Couchbase\r
  6 Cloud Spanner\r
Selection \[1\]: "
send -- "1\r"
expect -re "(.*)\n"
send -- "Admin@123"
expect -exact "Admin@123"
send -- "\r"
expect -re "(.*)\n"
send -- "\r"
expect -exact "\r
Install Jans Auth Config Api? \[Yes\] : "
send -- "\r"
expect -exact "\r
Install Scim Server? \[Yes\] : "
send -- "\r"
expect -exact "\r
Install Fido2 Server? \[Yes\] : "
send -- "\r"
expect -exact "\r
Install Eleven Server? \[No\] : "
send -- "\r"
expect -exact "\r
Proceed with these values \[Y|n\] "
send -- "y\r"

expect "Janssen Server installation successful\!"
send -- "\r"
expect -re "(.*)\n"

send -- "ps ax \| grep \-v grep \| grep jans \> \/dev\/null \; echo \$\?\r" 
if { $expect_out(buffer) eq "0" } {
	 puts "installation successful" }
send -- "exit\r"
expect -exact "exit"
expect eof
