# coding: utf-8

"""
    SCIM API

    Janssen SCIM 2.0 server API. Developers can think of SCIM as a REST API with endpoints exposing CRUD functionality (create, update, retrieve and delete) for identity management resources such as users, groups, and fido devices.   # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ServiceProviderConfigResponseFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'supported': 'bool',
        'max_results': 'int'
    }

    attribute_map = {
        'supported': 'supported',
        'max_results': 'maxResults'
    }

    def __init__(self, supported=None, max_results=None):  # noqa: E501
        """ServiceProviderConfigResponseFilter - a model defined in Swagger"""  # noqa: E501
        self._supported = None
        self._max_results = None
        self.discriminator = None
        if supported is not None:
            self.supported = supported
        if max_results is not None:
            self.max_results = max_results

    @property
    def supported(self):
        """Gets the supported of this ServiceProviderConfigResponseFilter.  # noqa: E501


        :return: The supported of this ServiceProviderConfigResponseFilter.  # noqa: E501
        :rtype: bool
        """
        return self._supported

    @supported.setter
    def supported(self, supported):
        """Sets the supported of this ServiceProviderConfigResponseFilter.


        :param supported: The supported of this ServiceProviderConfigResponseFilter.  # noqa: E501
        :type: bool
        """

        self._supported = supported

    @property
    def max_results(self):
        """Gets the max_results of this ServiceProviderConfigResponseFilter.  # noqa: E501


        :return: The max_results of this ServiceProviderConfigResponseFilter.  # noqa: E501
        :rtype: int
        """
        return self._max_results

    @max_results.setter
    def max_results(self, max_results):
        """Sets the max_results of this ServiceProviderConfigResponseFilter.


        :param max_results: The max_results of this ServiceProviderConfigResponseFilter.  # noqa: E501
        :type: int
        """

        self._max_results = max_results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServiceProviderConfigResponseFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServiceProviderConfigResponseFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
