# This software is available under the Apache-2.0 license.
# See https://www.apache.org/licenses/LICENSE-2.0.txt for full text.
#
# Copyright (c) 2024, Gluu, Inc.

class DataError(Exception): ...
class InvalidKey(DataError): ...
class KeyNotFound(DataError): ...
class StorageLimitExceeded(DataError): ...
class TTLExceeded(DataError): ...
class ValueTooLarge(DataError): ...
class SerializationError(DataError): ...

