# This software is available under the Apache-2.0 license.
# See https://www.apache.org/licenses/LICENSE-2.0.txt for full text.
#
# Copyright (c) 2024, Gluu, Inc.

class DataErrorCtx(Exception): ...
class InvalidKey(DataErrorCtx): ...
class KeyNotFound(DataErrorCtx): ...
class StorageLimitExceeded(DataErrorCtx): ...
class TTLExceeded(DataErrorCtx): ...
class ValueTooLarge(DataErrorCtx): ...
class SerializationError(DataErrorCtx): ...

