#!/bin/bash

#--- SETTING DEFAULT VALUES ---
export SUPPORT_GOOGLE_LOGOUT=${SUPPORT_GOOGLE_LOGOUT:=true}
export USE_CLIENT_AUTHENTICATION_FOR_PAT=${USE_CLIENT_AUTHENTICATION_FOR_PAT:=true}
export TRUST_ALL_CERTS=${TRUST_ALL_CERTS:=true}
export KEYSTORE_VALIDATE_CERT=${KEYSTORE_VALIDATE_CERT:=false}
export TRUST_STORE_PATH=${TRUST_STORE_PATH:=''}
export TRUST_STORE_PASSWORD=${TRUST_STORE_PASSWORD:=''}
export CRYPT_PROVIDER_KEY_STORE_PATH=${CRYPT_PROVIDER_KEY_STORE_PATH:=''}
export CRYPT_PROVIDER_KEY_STORE_PASSWORD=${CRYPT_PROVIDER_KEY_STORE_PASSWORD:=''}
export CRYPT_PROVIDER_DN_NAME=${CRYPT_PROVIDER_DN_NAME:=''}
export TRUST_STORE_PATH=${TRUST_STORE_PATH:=''}
export STATE_EXPIRATION_IN_MINUTES=${STATE_EXPIRATION_IN_MINUTES:=5}
export NONCE_EXPIRATION_IN_MINUTES=${NONCE_EXPIRATION_IN_MINUTES:=5}
export PUBLIC_OP_KEY_CACHE_EXPIRATION_IN_MINUTES=${PUBLIC_OP_KEY_CACHE_EXPIRATION_IN_MINUTES:=60}
export NONCE_EXPIRATION_IN_MINUTES=${NONCE_EXPIRATION_IN_MINUTES:=5}
export PROTECT_COMMANDS_WITH_ACCESS_TOKEN=${PROTECT_COMMANDS_WITH_ACCESS_TOKEN:=false}
export UMA2_AUTO_REGISTER_CLAIMS_GATHERING_ENDPOINT_AS_REDIRECT_URI_OF_CLIENT=${UMA2_AUTO_REGISTER_CLAIMS_GATHERING_ENDPOINT_AS_REDIRECT_URI_OF_CLIENT:=true}
export ADD_CLIENT_CREDENTIALS_GRANT_TYPE_AUTOMATICALLY_DURING_CLIENT_REGISTRATION=${ADD_CLIENT_CREDENTIALS_GRANT_TYPE_AUTOMATICALLY_DURING_CLIENT_REGISTRATION:=true}
export MIGRATION_SOURCE_FOLDER_PATH=${MIGRATION_SOURCE_FOLDER_PATH:=''}
export APPLICATION_CONNECTOR_HTTP_PORT=${APPLICATION_CONNECTOR_HTTP_PORT:=8084}
export APPLICATION_CONNECTOR_HTTPS_PORT=${APPLICATION_CONNECTOR_HTTPS_PORT:=8443}
export ADMIN_CONNECTOR_HTTPS_PORT=${ADMIN_CONNECTOR_HTTPS_PORT:=8444}
export ROOT_LOG_LEVEL=${ROOT_LOG_LEVEL:=INFO}
export GLUU_LOG_LEVEL=${GLUU_LOG_LEVEL:=INFO}
export XDI_LOG_LEVEL=${XDI_LOG_LEVEL:=INFO}


envsubst < /config_template.yml > /config.yml
java -jar /oxd-server.jar server /config.yml