/*
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.2
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * GetIssuerParams
 */


public class GetIssuerParams {
  @SerializedName("resource")
  private String resource = null;

  public GetIssuerParams resource(String resource) {
    this.resource = resource;
    return this;
  }

   /**
   * Identifier for the target End-User that is the subject of the discovery request.
   * @return resource
  **/
  @Schema(example = "admin@jenkins-ldap.gluu.org", required = true, description = "Identifier for the target End-User that is the subject of the discovery request.")
  public String getResource() {
    return resource;
  }

  public void setResource(String resource) {
    this.resource = resource;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetIssuerParams getIssuerParams = (GetIssuerParams) o;
    return Objects.equals(this.resource, getIssuerParams.resource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resource);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetIssuerParams {\n");
    
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
