/*
 * oxd-server
 * oxd-server
 *
 * OpenAPI spec version: 4.0
 * Contact: yuriyz@gluu.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * JsonWebKey
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-15T09:55:53.588Z")
public class JsonWebKey {
  @SerializedName("kid")
  private String kid = null;

  @SerializedName("kty")
  private String kty = null;

  @SerializedName("use")
  private String use = null;

  @SerializedName("key_ops")
  private String keyOps = null;

  @SerializedName("alg")
  private String alg = null;

  @SerializedName("exp")
  private Long exp = null;

  @SerializedName("x5c")
  private List<String> x5c = new ArrayList<String>();

  @SerializedName("x5t")
  private List<String> x5t = new ArrayList<String>();

  @SerializedName("x5t#S256")
  private String x5tS256 = null;

  @SerializedName("x5u")
  private String x5u = null;

  public JsonWebKey kid(String kid) {
    this.kid = kid;
    return this;
  }

   /**
   * Get kid
   * @return kid
  **/
  @ApiModelProperty(required = true, value = "")
  public String getKid() {
    return kid;
  }

  public void setKid(String kid) {
    this.kid = kid;
  }

  public JsonWebKey kty(String kty) {
    this.kty = kty;
    return this;
  }

   /**
   * Get kty
   * @return kty
  **/
  @ApiModelProperty(required = true, value = "")
  public String getKty() {
    return kty;
  }

  public void setKty(String kty) {
    this.kty = kty;
  }

  public JsonWebKey use(String use) {
    this.use = use;
    return this;
  }

   /**
   * Get use
   * @return use
  **/
  @ApiModelProperty(required = true, value = "")
  public String getUse() {
    return use;
  }

  public void setUse(String use) {
    this.use = use;
  }

  public JsonWebKey keyOps(String keyOps) {
    this.keyOps = keyOps;
    return this;
  }

   /**
   * Get keyOps
   * @return keyOps
  **/
  @ApiModelProperty(required = true, value = "")
  public String getKeyOps() {
    return keyOps;
  }

  public void setKeyOps(String keyOps) {
    this.keyOps = keyOps;
  }

  public JsonWebKey alg(String alg) {
    this.alg = alg;
    return this;
  }

   /**
   * Get alg
   * @return alg
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAlg() {
    return alg;
  }

  public void setAlg(String alg) {
    this.alg = alg;
  }

  public JsonWebKey exp(Long exp) {
    this.exp = exp;
    return this;
  }

   /**
   * Get exp
   * @return exp
  **/
  @ApiModelProperty(example = "1563964950485", required = true, value = "")
  public Long getExp() {
    return exp;
  }

  public void setExp(Long exp) {
    this.exp = exp;
  }

  public JsonWebKey x5c(List<String> x5c) {
    this.x5c = x5c;
    return this;
  }

  public JsonWebKey addX5cItem(String x5cItem) {
    this.x5c.add(x5cItem);
    return this;
  }

   /**
   * Get x5c
   * @return x5c
  **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getX5c() {
    return x5c;
  }

  public void setX5c(List<String> x5c) {
    this.x5c = x5c;
  }

  public JsonWebKey x5t(List<String> x5t) {
    this.x5t = x5t;
    return this;
  }

  public JsonWebKey addX5tItem(String x5tItem) {
    this.x5t.add(x5tItem);
    return this;
  }

   /**
   * Get x5t
   * @return x5t
  **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getX5t() {
    return x5t;
  }

  public void setX5t(List<String> x5t) {
    this.x5t = x5t;
  }

  public JsonWebKey x5tS256(String x5tS256) {
    this.x5tS256 = x5tS256;
    return this;
  }

   /**
   * Get x5tS256
   * @return x5tS256
  **/
  @ApiModelProperty(value = "")
  public String getX5tS256() {
    return x5tS256;
  }

  public void setX5tS256(String x5tS256) {
    this.x5tS256 = x5tS256;
  }

  public JsonWebKey x5u(String x5u) {
    this.x5u = x5u;
    return this;
  }

   /**
   * Get x5u
   * @return x5u
  **/
  @ApiModelProperty(required = true, value = "")
  public String getX5u() {
    return x5u;
  }

  public void setX5u(String x5u) {
    this.x5u = x5u;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonWebKey jsonWebKey = (JsonWebKey) o;
    return Objects.equals(this.kid, jsonWebKey.kid) &&
        Objects.equals(this.kty, jsonWebKey.kty) &&
        Objects.equals(this.use, jsonWebKey.use) &&
        Objects.equals(this.keyOps, jsonWebKey.keyOps) &&
        Objects.equals(this.alg, jsonWebKey.alg) &&
        Objects.equals(this.exp, jsonWebKey.exp) &&
        Objects.equals(this.x5c, jsonWebKey.x5c) &&
        Objects.equals(this.x5t, jsonWebKey.x5t) &&
        Objects.equals(this.x5tS256, jsonWebKey.x5tS256) &&
        Objects.equals(this.x5u, jsonWebKey.x5u);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kid, kty, use, keyOps, alg, exp, x5c, x5t, x5tS256, x5u);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonWebKey {\n");
    
    sb.append("    kid: ").append(toIndentedString(kid)).append("\n");
    sb.append("    kty: ").append(toIndentedString(kty)).append("\n");
    sb.append("    use: ").append(toIndentedString(use)).append("\n");
    sb.append("    keyOps: ").append(toIndentedString(keyOps)).append("\n");
    sb.append("    alg: ").append(toIndentedString(alg)).append("\n");
    sb.append("    exp: ").append(toIndentedString(exp)).append("\n");
    sb.append("    x5c: ").append(toIndentedString(x5c)).append("\n");
    sb.append("    x5t: ").append(toIndentedString(x5t)).append("\n");
    sb.append("    x5tS256: ").append(toIndentedString(x5tS256)).append("\n");
    sb.append("    x5u: ").append(toIndentedString(x5u)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

