// This software is available under the Apache-2.0 license.
// See https://www.apache.org/licenses/LICENSE-2.0.txt for full text.
//
// Copyright (c) 2024, Gluu, Inc.

//! Per-backend authorization trace ring buffer and diagnostic SQL functions.
//!
//! `cedarling_last_trace()` / `cedarling_recent_traces(limit)` surface the rolling log of
//! engine calls so operators can inspect recent decisions without enabling verbose server logging.
//!
//! `cedarling_explain(resource_json, action)` runs a one-off unsigned authorization outside the
//! cache / counter path — useful for interactive policy debugging in `psql`.

use std::collections::VecDeque;
use std::sync::Mutex;
use std::time::{Duration, Instant};

use chrono::Utc;
use pgrx::prelude::*;
use serde_json::{json, Value};

use crate::authz::bridge as authz_bridge;
use crate::engine;
use crate::sync_mutex;
#[cfg(not(test))]
use crate::guc_config;
#[cfg(test)]
fn trace_buffer_size() -> usize {
    64
}

#[cfg(not(test))]
fn trace_buffer_size() -> usize {
    usize::try_from(guc_config::trace_buffer_size())
        .unwrap_or(0)
        .min(65_536)
}

/// A single recorded authorization event.
///
/// Resource JSON and token data are intentionally excluded to keep traces safe for server logs.
#[derive(Debug, Clone)]
pub(crate) struct AuthorizationTrace {
    /// RFC 3339 timestamp of when the authorization was initiated.
    pub timestamp: String,
    /// Cedar action UID (e.g. `Jans::Action::"Read"`).
    pub action: String,
    /// Elapsed time for the Cedarling engine call in milliseconds.
    pub duration_ms: u64,
    /// Raw Cedarling decision before mode / fail-mode adjustment; `None` on engine error.
    pub decision: Option<bool>,
    /// Error category from [`crate::error::CedarlingError::category`]; `None` on success.
    pub error_category: Option<&'static str>,
    /// Request ID generated by Cedarling for this authorization call.
    pub request_id: String,
    /// Cedar entity type extracted from `cedar_entity_mapping.entity_type` in the resource JSON.
    pub resource_type: String,
    /// Cedar entity ID extracted from `cedar_entity_mapping.id` in the resource JSON.
    pub resource_id: String,
    /// Principal entity ID, if known (currently always `None`).
    pub principal_id: Option<String>,
    /// `true` when running in shadow mode.
    pub shadow: bool,
    /// `true` when the decision was served from cache (bypassing the engine).
    pub cache_hit: bool,
    /// Policy IDs that contributed to the decision (`response.diagnostics().reason()`).
    pub policy_hits: Vec<String>,
    /// Diagnostic errors from Cedar (`response.diagnostics().errors()`).
    pub diag_errors: Vec<String>,
    /// `true` when `cedarling.strategy = mask` converted a deny into a masked-row allow.
    pub masked: bool,
    /// `cedarling.policy_version` at evaluation time (if set).
    pub policy_version: Option<String>,
}

static RING: Mutex<VecDeque<AuthorizationTrace>> = Mutex::new(VecDeque::new());

/// Convert a `Duration` into whole milliseconds for trace records.
///
/// A backend process whose individual authorization call exceeds `u64::MAX`
/// milliseconds (~584 million years) is not a configuration we need to model;
/// saturating instead of panicking keeps the trace path infallible.
#[inline]
pub(crate) fn duration_millis(d: Duration) -> u64 {
    u64::try_from(d.as_millis()).unwrap_or(u64::MAX)
}

/// Push a trace into the ring buffer. Oldest entry is silently dropped when the buffer is full.
pub(crate) fn push_trace(mut trace: AuthorizationTrace) {
    if trace.policy_version.is_none() {
        trace.policy_version = policy_version_for_trace();
    }
    let max_traces = trace_buffer_size();
    if max_traces == 0 {
        return;
    }
    if let Ok(mut buf) = sync_mutex::lock(&RING) {
        while buf.len() >= max_traces {
            buf.pop_front();
        }
        buf.push_back(trace);
    }
}

/// Record a non-authorization marker when policy is swapped or rolled back.
pub(crate) fn push_policy_swap_trace(operation: &str, detail: &str) {
    push_trace(AuthorizationTrace {
        timestamp: Utc::now().to_rfc3339(),
        action: format!("cedarling.policy.{operation}"),
        duration_ms: 0,
        decision: None,
        error_category: Some("configuration"),
        request_id: String::new(),
        resource_type: String::new(),
        resource_id: detail.to_string(),
        principal_id: None,
        shadow: false,
        cache_hit: false,
        policy_hits: vec![],
        diag_errors: vec![format!("policy {operation}: {detail}")],
        masked: false,
        policy_version: policy_version_for_trace(),
    });
}

/// Extract `(entity_type, id)` from the `cedar_entity_mapping` block inside resource JSON.
///
/// Returns `("", "")` when the JSON cannot be parsed or the mapping block is absent.
pub(crate) fn extract_entity_info(resource_json: &str) -> (String, String) {
    let Ok(v) = serde_json::from_str::<serde_json::Value>(resource_json) else {
        return (String::new(), String::new());
    };
    let Some(m) = v.get("cedar_entity_mapping") else {
        return (String::new(), String::new());
    };
    let entity_type = m
        .get("entity_type")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();
    let id = m
        .get("id")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();
    (entity_type, id)
}

fn trace_to_value(t: &AuthorizationTrace) -> Value {
    let decision_str: Value = match t.decision {
        Some(true) => json!("allow"),
        Some(false) => json!("deny"),
        None => Value::Null,
    };
    let mut obj = json!({
        "timestamp":    t.timestamp,
        "action":       t.action,
        "duration_ms":  t.duration_ms,
        "decision":     decision_str,
        "request_id":   t.request_id,
        "resource_type": t.resource_type,
        "resource_id":  t.resource_id,
        "shadow":       t.shadow,
        "cache_hit":    t.cache_hit,
        "policy_hits":  t.policy_hits,
        "diag_errors":  t.diag_errors,
    });
    if let Some(cat) = t.error_category {
        obj["error_category"] = json!(cat);
    }
    if let Some(pid) = &t.principal_id {
        obj["principal_id"] = json!(pid);
    }
    if t.masked {
        obj["masked"] = json!(true);
    }
    if let Some(pv) = &t.policy_version {
        obj["policy_version"] = json!(pv);
    }
    obj
}

#[cfg(not(test))]
fn policy_version_for_trace() -> Option<String> {
    crate::guc_config::policy_version_utf8()
}

#[cfg(test)]
fn policy_version_for_trace() -> Option<String> {
    None
}

/// Returns the most recent authorization trace recorded in this backend process, or `NULL` if none.
///
/// Traces are per-backend-process and reset on backend reconnect. Resource JSON and token data
/// are never included — only action, decision, duration, and optional error category.
#[pg_extern(stable)]
pub fn cedarling_last_trace() -> Option<pgrx::datum::JsonB> {
    sync_mutex::lock(&RING)
        .ok()
        .and_then(|buf| buf.back().map(|t| pgrx::datum::JsonB(trace_to_value(t))))
}

/// Returns the most recent `limit` authorization traces as a JSONB array (newest first).
///
/// `limit` defaults to 10 when `NULL`; clamped to `0..=cedarling.trace_buffer_size`.
/// Traces are per-backend-process.
#[pg_extern(stable)]
pub fn cedarling_recent_traces(limit: Option<i32>) -> pgrx::datum::JsonB {
    let max_traces = trace_buffer_size();
    if max_traces == 0 {
        return pgrx::datum::JsonB(json!([]));
    }
    let count = usize::try_from(limit.unwrap_or(10).max(0))
        .unwrap_or(0)
        .min(max_traces);
    let arr: Vec<Value> = sync_mutex::lock(&RING)
        .map(|buf| buf.iter().rev().take(count).map(trace_to_value).collect())
        .unwrap_or_default();
    pgrx::datum::JsonB(json!(arr))
}

/// Runs a one-off unsigned Cedar authorization and returns a diagnostic JSONB trace.
///
/// **Bypasses the decision cache** and **does not increment `cedarling_status()` counters** —
/// safe to call repeatedly for interactive debugging.
///
/// `resource_json`: `EntityData` JSON (must contain `cedar_entity_mapping`).
/// `action`: full Cedar action UID (e.g. `Jans::Action::"Read"`).
///
/// The returned object always contains `timestamp`, `action`, `duration_ms`, and `decision`
/// (`"allow"` | `"deny"` | `null`). An `error` field is added on failure. On success,
/// `request_id`, `policy_hits`, `diag_errors`, and `policies` are also included.
#[pg_extern(volatile, parallel_restricted)]
pub fn cedarling_explain(resource_json: &str, action: &str) -> pgrx::datum::JsonB {
    // Not STRICT: SQL callers may pass empty strings and receive the documented error envelope.
    let start = Instant::now();
    let timestamp = Utc::now().to_rfc3339();
    let action_trimmed = action.trim();
    let resource_trimmed = resource_json.trim();

    let elapsed_ms = || duration_millis(start.elapsed());

    if action_trimmed.is_empty() {
        return pgrx::datum::JsonB(json!({
            "timestamp":   timestamp,
            "action":      action_trimmed,
            "duration_ms": elapsed_ms(),
            "decision":    Value::Null,
            "error":       "empty action",
        }));
    }
    if resource_trimmed.is_empty() {
        return pgrx::datum::JsonB(json!({
            "timestamp":   timestamp,
            "action":      action_trimmed,
            "duration_ms": elapsed_ms(),
            "decision":    Value::Null,
            "error":       "empty resource JSON",
        }));
    }

    let engine = match engine::global_cedarling() {
        Ok(e) => e,
        Err(e) => {
            return pgrx::datum::JsonB(json!({
                "timestamp":        timestamp,
                "action":           action_trimmed,
                "duration_ms":      elapsed_ms(),
                "decision":         Value::Null,
                "error":            format!("engine unavailable: {e}"),
                "engine_available": false,
            }));
        },
    };

    // Parse resource to EntityData for both the request and the policy lookup.
    let resource_data = match crate::resource::resource_entity_data_from_json_str(resource_trimmed) {
        Ok(d) => d,
        Err(e) => {
            return pgrx::datum::JsonB(json!({
                "timestamp":        timestamp,
                "action":           action_trimmed,
                "duration_ms":      elapsed_ms(),
                "decision":         Value::Null,
                "error":            e.to_string(),
                "engine_available": true,
            }));
        },
    };

    let request = cedarling::RequestUnsigned {
        principal: None,
        resource: resource_data.clone(),
        action: action_trimmed.to_string(),
        context: serde_json::json!({}),
    };

    match authz_bridge::authorize_unsigned_outcome_for_request(engine.as_ref(), request) {
        Ok(outcome) => {
            // Fetch matching policy metadata and filter to only those that contributed to the decision.
            let policies: Vec<Value> = engine
                .get_matching_policies_unsigned(
                    None,
                    &[action_trimmed.to_string()],
                    &[resource_data],
                )
                .unwrap_or_default()
                .into_iter()
                .filter(|p| outcome.policy_hits.contains(&p.id))
                .map(|p| {
                    json!({
                        "id":     p.id,
                        "effect": format!("{:?}", p.effect).to_lowercase(),
                        "source": p.source,
                    })
                })
                .collect();

            pgrx::datum::JsonB(json!({
                "timestamp":        timestamp,
                "action":           action_trimmed,
                "duration_ms":      elapsed_ms(),
                "decision":         if outcome.decision { "allow" } else { "deny" },
                "engine_available": true,
                "request_id":       outcome.request_id,
                "policy_hits":      outcome.policy_hits,
                "diag_errors":      outcome.diag_errors,
                "policies":         policies,
            }))
        },
        Err(e) => pgrx::datum::JsonB(json!({
            "timestamp":        timestamp,
            "action":           action_trimmed,
            "duration_ms":      elapsed_ms(),
            "decision":         Value::Null,
            "error":            e.to_string(),
            "engine_available": true,
        })),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_trace(decision: Option<bool>, err_cat: Option<&'static str>) -> AuthorizationTrace {
        AuthorizationTrace {
            timestamp: "2026-04-27T00:00:00Z".into(),
            action: "T::Action::\"Read\"".into(),
            duration_ms: 1,
            decision,
            error_category: err_cat,
            request_id: "test-req-id".into(),
            resource_type: "Test::Resource".into(),
            resource_id: "res-1".into(),
            principal_id: None,
            shadow: false,
            cache_hit: false,
            policy_hits: vec![],
            diag_errors: vec![],
            masked: false,
            policy_version: None,
        }
    }

    #[test]
    fn push_then_last_trace_returns_some() {
        push_trace(make_trace(Some(true), None));
        assert!(
            cedarling_last_trace().is_some(),
            "ring should have at least one trace after push"
        );
        let v = cedarling_last_trace().unwrap().0;
        assert_eq!(v["action"], "T::Action::\"Read\"");
        assert_eq!(v["duration_ms"], 1u64);
    }

    #[test]
    fn allow_and_deny_serialize_correctly() {
        let allow_v = trace_to_value(&make_trace(Some(true), None));
        assert_eq!(allow_v["decision"], "allow");

        let deny_v = trace_to_value(&make_trace(Some(false), None));
        assert_eq!(deny_v["decision"], "deny");

        let err_v = trace_to_value(&make_trace(None, Some("engine")));
        assert!(err_v["decision"].is_null());
        assert_eq!(err_v["error_category"], "engine");
    }

    #[test]
    fn trace_without_error_omits_error_category_field() {
        let v = trace_to_value(&make_trace(Some(true), None));
        assert!(
            v.get("error_category").is_none(),
            "error_category should not be present on success"
        );
    }

    #[test]
    fn trace_without_principal_omits_principal_id_field() {
        let v = trace_to_value(&make_trace(Some(true), None));
        assert!(
            v.get("principal_id").is_none(),
            "principal_id should not be present when None"
        );
    }

    #[test]
    fn trace_with_principal_includes_principal_id_field() {
        let mut t = make_trace(Some(true), None);
        t.principal_id = Some("User::\"alice\"".to_string());
        let v = trace_to_value(&t);
        assert_eq!(v["principal_id"], "User::\"alice\"");
    }

    #[test]
    fn ring_does_not_exceed_max_traces() {
        let max_traces = trace_buffer_size().max(1);
        for i in 0..max_traces + 5 {
            push_trace(AuthorizationTrace {
                timestamp: "2026-01-01T00:00:00Z".into(),
                action: format!("T::A::\"{i}\""),
                duration_ms: i as u64,
                decision: Some(true),
                error_category: None,
                request_id: format!("req-{i}"),
                resource_type: "T::Resource".into(),
                resource_id: format!("r-{i}"),
                principal_id: None,
                shadow: false,
                cache_hit: false,
                policy_hits: vec![],
                diag_errors: vec![],
                masked: false,
                policy_version: None,
            });
        }
        let buf = sync_mutex::lock(&RING).expect("lock");
        assert!(
            buf.len() <= max_traces,
            "ring buffer must never exceed configured trace_buffer_size"
        );
    }

    #[test]
    fn recent_traces_limit_zero_returns_empty_array() {
        push_trace(make_trace(Some(true), None));
        let result = cedarling_recent_traces(Some(0));
        let arr = result.0.as_array().expect("should be array");
        assert!(arr.is_empty(), "limit=0 should return empty array");
    }

    #[test]
    fn recent_traces_null_limit_defaults_to_ten() {
        let result = cedarling_recent_traces(None);
        let arr = result.0.as_array().expect("should be array");
        assert!(arr.len() <= 10, "null limit should default to 10 entries");
    }

    #[test]
    fn extract_entity_info_parses_cedar_entity_mapping() {
        let json = r#"{"cedar_entity_mapping":{"entity_type":"Jans::Resource","id":"abc123"},"extra":"field"}"#;
        let (et, id) = extract_entity_info(json);
        assert_eq!(et, "Jans::Resource");
        assert_eq!(id, "abc123");
    }

    #[test]
    fn extract_entity_info_returns_empty_on_missing_mapping() {
        let (et, id) = extract_entity_info(r#"{"foo":"bar"}"#);
        assert_eq!(et, "");
        assert_eq!(id, "");
    }

    #[test]
    fn extract_entity_info_returns_empty_on_invalid_json() {
        let (et, id) = extract_entity_info("not json");
        assert_eq!(et, "");
        assert_eq!(id, "");
    }

    #[test]
    fn explain_empty_action_returns_error_without_decision() {
        let result = cedarling_explain(
            r#"{"cedar_entity_mapping":{"entity_type":"T","id":"x"}}"#,
            "",
        );
        let v = &result.0;
        assert_eq!(v["error"], "empty action");
        assert!(v["decision"].is_null());
        assert!(v.get("timestamp").is_some());
        assert!(v.get("duration_ms").is_some());
    }

    #[test]
    fn explain_empty_resource_returns_error_without_decision() {
        let result = cedarling_explain("", "T::Action::\"Read\"");
        let v = &result.0;
        assert_eq!(v["error"], "empty resource JSON");
        assert!(v["decision"].is_null());
    }
}
