#!/bin/bash

if [ -e /etc/default/oxd-server ]; then
    chown root:root /etc/default/oxd-server > /dev/null 2>&1
    chmod 644 /etc/default/oxd-server > /dev/null 2>&1
fi

if [ -e /etc/init.d/oxd-server ]; then
    chown root:root /etc/init.d/oxd-server > /dev/null 2>&1
    chmod 755 /etc/init.d/oxd-server > /dev/null 2>&1
    update-rc.d oxd-server defaults > /dev/null 2>&1
fi

if [ -e /lib/systemd/system/oxd-server.service ]; then
    chown root:root /lib/systemd/system/oxd-server.service > /dev/null 2>&1 
    chmod 755 /lib/systemd/system/oxd-server.service > /dev/null 2>&1 
    chmod 755 /opt/oxd-server/bin/oxd-server.sh  > /dev/null 2>&1
    systemctl enable oxd-server > /dev/null 2>&1 
fi

getent passwd jetty > /dev/null 2>&1
if [ $? -ne 0 ]; then
    /usr/sbin/useradd --system --create-home --user-group --shell /bin/bash --home-dir /home/jetty jetty
fi
getent group gluu > /dev/null 2>&1
if [ $? -ne 0 ]; then
    /usr/sbin/groupadd gluu
    /usr/sbin/usermod -a -G gluu jetty
fi

chown jetty:jetty -R /opt/oxd-server > /dev/null 2>&1
mkdir -p /var/log/oxd-server > /dev/null 2>&1
touch /var/log/oxd-server/oxd-server.log > /dev/null 2>&1
chown -R jetty:jetty /var/log/oxd-server > /dev/null 2>&1
exit 0
