#!/bin/bash

if [ -x /etc/init.d/oxd-server ]; then
    /etc/init.d/oxd-server stop > /dev/null 2>&1 
fi

if [ -x /lib/systemd/system/oxd-server.service ]; then
    systemctl stop oxd-server > /dev/null 2>&1 
fi

getent passwd jetty > /dev/null 2>&1
if [ $? -ne 0 ]; then
    /usr/sbin/useradd --system --create-home --user-group --shell /bin/bash --home-dir /home/jetty jetty
fi
getent group gluu > /dev/null 2>&1
if [ $? -ne 0 ]; then
    /usr/sbin/groupadd gluu
    /usr/sbin/usermod -a -G gluu jetty
fi

if [ -e /etc/default/oxd-server ]; then
    chown root:root /etc/default/oxd-server 2>&1
    chmod 644 /etc/default/oxd-server 2>&1
fi

chown jetty:jetty -R /opt/oxd-server 2>&1
mkdir -p /var/log/oxd-server 2>&1
touch /var/log/oxd-server/oxd-server.log 2>&1
chown -R jetty:jetty /var/log/oxd-server 2>&1
exit 0
