#!/bin/sh -e

# Stopping oxd-server
if [ -x /etc/init.d/oxd-server ]; then
service oxd-server stop > /dev/null 2>&1
fi

# Stopping oxd-https-extension
if [ -x /etc/init.d/oxd-https-extension ]; then
service oxd-https-extension stop > /dev/null 2>&1
fi

exit 0
