#!/bin/sh -e

# Stopping oxd-server-4.0.0
if [ -x /etc/init.d/oxd-server-4.0.0 ]; then
/etc/init.d/oxd-server-4.0.0 stop > /dev/null 2>&1
fi

# Stopping oxd-https-extension
if [ -x /etc/init.d/oxd-https-extension ]; then
/etc/init.d/oxd-https-extension stop > /dev/null 2>&1
fi

exit 0
