FROM alpine:3.21@sha256:ce64758a109eb420d874a118f87920e625e12d3634e03b4a5573fd9f6e5d3507

RUN apk add --no-cache bash curl jq

WORKDIR /demo
COPY tf_authz.sh .
COPY demo-runner.sh .
RUN chmod +x tf_authz.sh demo-runner.sh

ENV TERRAFORM_BIN=echo

CMD ["/demo/demo-runner.sh"]
