[ "https://www.gluu.org",
    "http://localhost:80/oxauth-rp/home.seam",
    "https://localhost:8443/oxauth-rp/home.seam",
    "https://%(hostname)s/oxauth-rp/home.seam",
    "https://client.example.org/callback",
    "https://client.example.org/callback2",
    "https://client.other_company.example.net/callback",
    "https://client.example.com/cb",
    "https://client.example.com/cb1",
    "https://client.example.com/cb2" ]
