package io.jans.shibboleth.trust.config.util;

public enum OperationType {
    
    NONE,
    ACTIVATE,
    CANCEL_ACTIVATION,
    DEACTIVATE,
    FINALIZE_ACTIVATION,
    INCORPORATE_DISCOVERED_ENTITY_IDS,
    UPDATE_METADATA_SOURCE,

    UPDATE_SHIBBOLETH_SSO_PROFILE_CONFIGURATION,
    UPDATE_SAML2_ARTIFACT_RESOLUTION_PROFILE_CONFIGURATION,
    UPDATE_SAML2_ATTRIBUTE_QUERY_PROFILE_CONFIGURATION,
    UPDATE_SAML2_ECP_PROFILE_CONFIGURATION,
    UPDATE_SAML2_SSO_PROFILE_CONFIGURATION,
    UPDATE_SAML2_LOGOUT_PROFILE_CONFIGURATION,

    UPDATE_RELEASED_ATTRIBUTES
}
