openapi: 3.0.1
info:
  title: jans-config-api
  description: jans-config-api - Authorization services
  contact:
    email: xxx@gluu.org
  license:
    name: License
    url: 'https://github.com/JanssenProject/blob/master/LICENSE'
  version: '1.0.0'
servers:
  - url: 'https://jans.io/'
tags:
  - name: developers
    description: jans-config-api enables access to the features available via the existing Jans Authorization Server API.
  - name: Attribute
  - name: Default Authentication Method
  - name: Cache Configuration
  - name: Cache Configuration – Memcached
  - name: Cache Configuration – Redis
  - name: Cache Configuration – in-Memory
  - name: Cache Configuration – Native-Persistence
  - name: Configuration – Properties
  - name: Configuration – Fido2
  - name: Configuration – SMTP
  - name: Configuration – Logging
  - name: Configuration – JWK - JSON Web Key (JWK)
  - name: Custom Scripts
  - name: Database - LDAP configuration
  - name: OAuth - OpenID Connect - Clients
  - name: OAuth - OpenID Connect - Sector Identifiers
  - name: OAuth - UMA Resources
  - name: OAuth - Scopes
paths:
  /jans-config-api/api/v1/jans-auth-server/config:
    get:
      summary: Gets all Jans authorization server configuration properties.
      description: Gets all Jans authorization server configuration properties.
      operationId: get-properties
      security:
        - jans-auth: [https://jans.io/oauth/jans-auth-server/config/properties.readonly]
      tags:
        - Configuration – Properties
    patch:
      summary: Partially modifies Jans authorization server Application configuration properties.
      description: Partially modifies Jans authorization server AppConfiguration properties.
      operationId: patch-properties
      security:
        - jans-auth: [https://jans.io/oauth/jans-auth-server/config/properties.write]
      tags:
        - Configuration – Properties
  /jans-config-api/api/v1/fido2/config:
    get:
      summary: Gets Jans Authorization Server Fido2 configuration properties.
      description: Gets Jans Authorization Server Fido2 configuration properties.
      operationId: get-properties-fido2
      tags:
        - Configuration – Fido2
      security:
        - jans-auth: [https://jans.io/oauth/config/fido2.readonly]
    put:
      summary: Updates Fido2 configuration properties.
      description: Updates Fido2 configuration properties.
      operationId: put-properties-fido2
      tags:
        - Configuration – Fido2
      security:
        - jans-auth: [https://jans.io/oauth/config/fido2.write]
  /jans-config-api/api/v1/attributes:
    get:
      summary: Gets a list of Gluu attributes.
      description: 'Gets all attributes. Optionally max-size of the result, attribute status and pattern can be provided.'
      operationId: get-attributes
      tags:
        - Attribute
      security:
        - jans-auth: [https://jans.io/oauth/config/attributes.readonly]
    post:
      summary: Adds a new attribute.
      description: Adds a new attribute.
      operationId: post-attributes
      tags:
        - Attribute
      security:
        - jans-auth: [https://jans.io/oauth/config/attributes.write]
    put:
      summary: Updates an existing attribute.
      description: Updates an existing attribute.
      operationId: put-attributes
      tags:
        - Attribute
      security:
        - jans-auth: [https://jans.io/oauth/config/attributes.write]
  '/jans-config-api/api/v1/attributes/{inum}':
    get:
      summary: Gets an attribute based on inum.
      description: Gets an attribute based on inum.
      operationId: get-attributes-by-inum
      tags:
        - Attribute
      security:
        - jans-auth: [https://jans.io/oauth/config/attributes.readonly]
    delete:
      summary: Deletes an attribute based on inum.
      description: Deletes an attribute based on inum.
      operationId: delete-attributes-by-inum
      tags:
        - Attribute
      security:
        - jans-auth: [https://jans.io/oauth/config/attributes.write]
    patch:
      summary: Partially modify a GluuAttribute.
      description: Partially modify a GluuAttribute.
      operationId: patch-attributes-by-inum
      security:
        - jans-auth: [https://jans.io/oauth/config/attributes.write]
      tags:
        - Attribute
  /jans-config-api/api/v1/acrs:
    get:
      summary: Gets default authentication method.
      description: Gets default authentication method.
      operationId: get-acrs
      tags:
        - Default Authentication Method
      security:
        - jans-auth: [https://jans.io/oauth/config/acrs.readonly]
    put:
      summary: Updates default authentication method.
      description: Updates default authentication method.
      operationId: put-acrs
      tags:
        - Default Authentication Method
      security:
        - jans-auth: [https://jans.io/oauth/config/acrs.write]
  /jans-config-api/api/v1/config/database/ldap:
    get:
      summary: Gets list of existing LDAP configurations.
      description: Gets list of existing LDAP configurations. 
      operationId: get-config-database-ldap
      tags:
        - Database - LDAP configuration
      security:
        - jans-auth: [https://jans.io/oauth/config/database/ldap.readonly]
    post:
      summary: Adds a new LDAP configuration.
      description: Adds a new LDAP configuration.
      operationId: post-config-database-ldap
      tags:
        - Database - LDAP configuration
      security:
        - jans-auth: [https://jans.io/oauth/config/database/ldap.write]
    put:
      summary: Updates LDAP configuration.
      description: Updates LDAP configuration.
      operationId: put-config-database-ldap
      tags:
        - Database - LDAP configuration
      security:
        - jans-auth: [https://jans.io/oauth/config/database/ldap.write]
  '/jans-config-api/api/v1/config/database/ldap/{name}':
    get:
      summary: Gets an LDAP configuration by name.
      description: Gets an LDAP configuration by name.
      operationId: get-config-database-ldap-by-name
      tags:
        - Database - LDAP configuration
      security:
        - jans-auth: [https://jans.io/oauth/config/database/ldap.readonly]
    delete:
      summary: Deletes an LDAP configuration.
      description: Deletes an LDAP configuration.
      operationId: delete-config-database-ldap-by-name
      tags:
        - Database - LDAP configuration
      security:
        - jans-auth: [https://jans.io/oauth/config/database/ldap.write]
    patch:
      summary: Partially modify an LDAP configuration.
      description: Partially modify an LDAP configuration.
      operationId: patch-config-database-ldap-by-name
      security:
        - jans-auth: [https://jans.io/oauth/config/database/ldap.write]
      tags:
        - Database - LDAP configuration
  /jans-config-api/api/v1/config/database/ldap/test:
    post:
      summary: Tests a LDAP configurations by name.
      description: Tests a LDAP configurations by name.
      operationId: post-config-database-ldap-test
      tags:
        - Database - LDAP configuration
      security:
        - jans-auth: [https://jans.io/oauth/config/database/ldap.readonly]
  /jans-config-api/api/v1/config/database/couchbase:
    get:
      summary: Gets list of existing Couchbase configurations.
      description: Gets list of existing Couchbase configurations. 
      operationId: get-config-database-couchbase
      tags:
        - Database - Couchbase configuration
      security:
        - jans-auth: [https://jans.io/oauth/config/database/couchbase.readonly]
    post:
      summary: Adds a new Couchbase configuration.
      description: Adds a new Couchbase configuration.
      operationId: post-config-database-couchbase
      tags:
        - Database - Couchbase configuration
      security:
        - jans-auth: [https://jans.io/oauth/config/database/couchbase.write]
    put:
      summary: Updates Couchbase configuration.
      description: Updates Couchbase configuration.
      operationId: put-config-database-couchbase
      tags:
        - Database - Couchbase configuration
      security:
        - jans-auth: [https://jans.io/oauth/config/database/couchbase.write]
  /jans-config-api/api/v1/config/database/couchbase/{name}:
    get:
      summary: Gets a Couchbase configurations by name.
      description: Gets a Couchbase configurations by name.
      operationId: get-config-database-couchbase-by-name
      tags:
        - Database - Couchbase configuration
      security:
        - jans-auth: [https://jans.io/oauth/config/database/couchbase.readonly]
    patch:
      summary: Partially modify an Couchbase configuration.
      description: Partially modify an Couchbase configuration.
      operationId: patch-config-database-couchbase-by-name
      tags:
        - Database - Couchbase configuration
      security:
        - jans-auth: [https://jans.io/oauth/config/database/couchbase.write]
    delete:
      summary: Deletes a Couchbase configurations by name.
      description: Deletes a Couchbase configurations by name.
      operationId: delete-config-database-couchbase-by-name
      tags:
        - Database - Couchbase configuration
      security:
        - jans-auth: [https://jans.io/oauth/config/database/couchbase.write]
  /jans-config-api/api/v1/config/database/couchbase/test:
    post:
      summary: Tests a Couchbase configurations by name.
      description: Tests a Couchbase configurations by name.
      operationId: post-config-database-couchbase-test
      tags:
        - Database - Couchbase configuration
      security:
        - jans-auth: [https://jans.io/oauth/config/database/couchbase.readonly]
  /jans-config-api/api/v1/config/scripts:
    get:
      summary: Gets a list of custom scripts.
      description: Gets a list of custom scripts.
      operationId: get-config-scripts
      tags:
        - Custom Scripts
      security:
        - jans-auth: [https://jans.io/oauth/config/scripts.readonly]
    post:
      summary: Adds a new custom script.
      description: Adds a new custom script.
      operationId: post-config-scripts
      tags:
        - Custom Scripts
      security:
        - jans-auth: [https://jans.io/oauth/config/scripts.write]
    put:
      summary: Updates a custom script.
      description: Updates a custom script.
      operationId: put-config-scripts
      tags:
        - Custom Scripts
      security:
        - jans-auth: [https://jans.io/oauth/config/scripts.write]
  /jans-config-api/api/v1/config/scripts/type/{type}:
    get:
      summary: Gets list of scripts by type.
      description: Gets list of scripts by type.
      operationId: get-config-scripts-by-type
      tags:
        - Custom Scripts
      security:
        - jans-auth: [https://jans.io/oauth/config/scripts.readonly]
  /jans-config-api/api/v1/config/scripts/inum/{inum}:
    get:
      summary: Gets a script by Inum.
      description: Gets a script by Inum.
      operationId: get-config-scripts-by-inum
      tags:
        - Custom Scripts
      security:
        - jans-auth: [https://jans.io/oauth/config/scripts.readonly]
  /jans-config-api/api/v1/config/scripts/{inum}:
    delete:
      summary: Deletes a custom script.
      description: Deletes a custom script.
      operationId: delete-config-scripts-by-inum
      tags:
        - Custom Scripts
      security:
        - jans-auth: [https://jans.io/oauth/config/scripts.write]
  /jans-config-api/api/v1/config/cache:
    get:
      summary: Returns cache configuration.
      description: Returns cache configuration.
      operationId: get-config-cache
      tags:
        - Cache Configuration
      security:
        - jans-auth: [https://jans.io/oauth/config/cache.readonly]
    patch:
      summary: Partially modifies cache configuration.
      description: Partially modifies cache configuration.
      operationId: patch-config-cache
      tags:
        - Cache Configuration
      security:
        - jans-auth: [https://jans.io/oauth/config/cache.write]
  /jans-config-api/api/v1/config/cache/memcached:
    get:
      summary: Returns Memcached cache configuration.
      description: Returns Memcached cache configuration.
      operationId: get-config-cache-memcached
      tags:
        - Cache Configuration – Memcached
      security:
        - jans-auth: [https://jans.io/oauth/config/cache.readonly]
    put:
      summary: Updates Memcached cache configuration.
      description: Updates Memcached cache configuration.
      operationId: put-config-cache-memcached
      tags:
        - Cache Configuration – Memcached
      security:
        - jans-auth: [https://jans.io/oauth/config/cache.write]
  /jans-config-api/api/v1/config/cache/redis:
    get:
      summary: Returns Redis cache configuration.
      description: Returns Redis cache configuration.
      operationId: get-config-cache-redis
      tags:
        - Cache Configuration – Redis
      security:
        - jans-auth: [https://jans.io/oauth/config/cache.readonly]
    put:
      summary: Updates Redis cache configuration.
      description: Updates Redis cache configuration.
      operationId: put-config-cache-redis
      tags:
        - Cache Configuration – Redis
      security:
        - jans-auth: [https://jans.io/oauth/config/cache.write]
  /jans-config-api/api/v1/config/cache/in-memory:
    get:
      summary: Returns in-Memory cache configuration.
      description: Returns in-Memory cache configuration.
      operationId: get-config-cache-in-memory
      tags:
        - Cache Configuration – in-Memory
      security:
        - jans-auth: [https://jans.io/oauth/config/cache.readonly]
    put:
      summary: Updates in-Memory cache configuration.
      description: Updates in-Memory cache configuration.
      operationId: put-config-cache-in-memory
      tags:
        - Cache Configuration – in-Memory
      security:
        - jans-auth: [https://jans.io/oauth/config/cache.write]
  /jans-config-api/api/v1/config/cache/native-persistence:
    get:
      summary: Returns native persistence cache configuration.
      description: Returns native persistence cache configuration.
      operationId: get-config-cache-native-persistence
      tags:
        - Cache Configuration – Native-Persistence
      security:
        - jans-auth: [https://jans.io/oauth/config/cache.readonly]
    put:
      summary: Updates native persistence cache configuration.
      description: Updates native persistence cache configuration.
      operationId: put-config-cache-native-persistence
      tags:
        - Cache Configuration – Native-Persistence
      security:
        - jans-auth: [https://jans.io/oauth/config/cache.write]
  /jans-config-api/api/v1/config/smtp:
    get:
      summary: Returns SMTP server configuration.
      description: Returns SMTP server configuration.
      operationId: get-config-smtp
      tags:
        - Configuration – SMTP
      security:
        - jans-auth: [https://jans.io/oauth/config/smtp.readonly]
    post:
      summary: Adds SMTP server configuration.
      description: Adds SMTP server configuration.
      operationId: post-config-smtp
      tags:
        - Configuration – SMTP
      security:
        - jans-auth: [https://jans.io/oauth/config/smtp.write]
    put:
      summary: Updates SMTP server configuration.
      description: Updates SMTP server configuration.
      operationId: put-config-smtp
      tags:
        - Configuration – SMTP
      security:
        - jans-auth: [https://jans.io/oauth/config/smtp.write]
    delete:
      summary: Deletes SMTP server configuration.
      description: Deletes SMTP server configuration.
      operationId: delete-config-smtp
      tags:
        - Configuration – SMTP
      security:
        - jans-auth: [https://jans.io/oauth/config/smtp.write]
  /jans-config-api/api/v1/config/smtp/test:
    get:
      summary: Test SMTP server configuration.
      description: Test SMTP server configuration.
      operationId: test-config-smtp
      tags:
        - Configuration – SMTP
      security:
        - jans-auth: [https://jans.io/oauth/config/smtp.readonly]
  /jans-config-api/api/v1/logging:
    get:
      tags:
        - Configuration – Logging
      summary: Returns Jans Authorization Server logging settings.
      description: Returns Jans Authorization Server logging settings.
      operationId: get-config-logging
      security:
        - jans-auth: [https://jans.io/oauth/config/logging.readonly]
    put:
      tags:
        - Configuration – Logging
      summary: Updates Jans Authorization Server logging settings.
      description: Updates Jans Authorization Server logging settings.
      operationId: put-config-logging
      security:
        - jans-auth: [https://jans.io/oauth/config/logging.write]
  /jans-config-api/api/v1/config/jwks:
    get:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Gets list of JSON Web Key (JWK) used by server.
      description: 'Gets list of JSON Web Key (JWK) used by server. JWK is a JSON data structure that represents a set of public keys as a JSON object [RFC4627].'
      operationId: get-config-jwks
      security:
        - jans-auth: [https://jans.io/oauth/config/jwks.readonly]
    put:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Puts/replaces JWKS
      description: Puts/replaces JSON Web Keys (JWKS).
      operationId: put-config-jwks
      security:
        - jans-auth: [https://jans.io/oauth/config/jwks.write]
    patch:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Patch JWKS
      description: Patch JSON Web Keys (JWKS).
      operationId: patch-config-jwks
      security:
        - jans-auth: [https://jans.io/oauth/config/jwks.write]
  /jans-config-api/api/v1/openid/clients:
    get:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Gets list of OpenID Connect clients
      description: Gets list of OpenID Connect clients
      operationId: get-oauth-openid-clients
      security:
        - jans-auth: [https://jans.io/oauth/config/openid/clients.readonly]
    post:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Create new OpenId connect client
      description: Create new OpenId connect client
      operationId: post-oauth-openid-clients
      security:
        - jans-auth: [https://jans.io/oauth/config/openid/clients.write]
    put:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Update OpenId Connect client.
      description: Update OpenId Connect client.
      operationId: put-oauth-openid-clients
      security:
        - jans-auth: [https://jans.io/oauth/config/openid/clients.write]
  '/jans-config-api/api/v1/openid/clients/{inum}':
    get:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Get OpenId Connect Client by Inum
      description: Get OpenId Connect Client by Inum.
      operationId: get-oauth-openid-clients-by-inum
      security:
        - jans-auth: [https://jans.io/oauth/config/openid/clients.readonly]
    delete:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Delete OpenId Connect client.
      description: Delete OpenId Connect client.
      operationId: delete-oauth-openid-clients-by-inum
      security:
        - jans-auth: [https://jans.io/oauth/config/openid/clients.write]
    patch:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Update modified properties of OpenId Connect client by Inum.
      description: Update modified properties of OpenId Connect client by Inum.
      operationId: patch-oauth-openid-clients-by-inum
      security:
        - jans-auth: [https://jans.io/oauth/config/openid/clients.write]
  /jans-config-api/api/v1/openid/sectoridentifiers:
    get:
      tags:
        - OAuth - OpenID Connect - Sector Identifiers
      summary: Gets list of OpenID Connect Sectors.
      description: Gets list of OpenID Connect Sectors.
      operationId: get-oauth-openid-sectors
      security:
        - jans-auth: [https://jans.io/oauth/config/openid/sectoridentifiers.readonly]
    post:
      tags:
        - OAuth - OpenID Connect - Sector Identifiers
      summary: Create new OpenID Connect Sector.
      description: Create new OpenID Connect Sector.
      operationId: post-oauth-openid-sectors
      security:
        - jans-auth: [https://jans.io/oauth/config/openid/sectoridentifiers.write]
    put:
      tags:
        - OAuth - OpenID Connect - Sector Identifiers
      summary: Update OpenId Connect Sector.
      description: Update OpenId Connect Sector.
      operationId: put-oauth-openid-sectors
      security:
        - jans-auth: [https://jans.io/oauth/config/openid/sectoridentifiers.write]
  /jans-config-api/api/v1/openid/sectoridentifiers/{inum}:
    get:
      tags:
        - OAuth - OpenID Connect - Sector Identifiers
      summary: Get OpenID Connect Sector by Inum.
      description: Get OpenID Connect Sector by Inum.
      operationId: get-oauth-openid-sectors-by-id
      security:
        - jans-auth: [https://jans.io/oauth/config/openid/sectoridentifiers.readonly]
    delete:
      tags:
        - OAuth - OpenID Connect - Sector Identifiers
      summary: Delete OpenID Connect Sector.
      description: Delete OpenID Connect Sector.
      operationId: delete-oauth-openid-sectors-by-id
      security:
        - jans-auth: [https://jans.io/oauth/config/openid/sectoridentifiers.write]
    patch:
      tags:
        - OAuth - OpenID Connect - Sector Identifiers
      summary: Partially update OpenId Connect Sector by Inum.
      description: Partially update OpenId Connect Sector by Inum.
      operationId: patch-oauth-openid-sectors-by-id
      security:
        - jans-auth: [https://jans.io/oauth/config/openid/sectoridentifiers.write]
  /jans-config-api/api/v1/uma/resources:
    get:
      tags:
        - OAuth - UMA Resources
      summary: Gets list of UMA resources.
      description: Gets list of UMA resources.
      operationId: get-oauth-uma-resources
      security:
        - jans-auth: [https://jans.io/oauth/config/uma/resources.readonly]
    post:
      tags:
        - OAuth - UMA Resources
      summary: Creates an UMA resource.
      description: Creates an UMA resource.
      operationId: post-oauth-uma-resources
      security:
        - jans-auth: [https://jans.io/oauth/config/uma/resources.write]
    put:
      tags:
        - OAuth - UMA Resources
      summary: Updates an UMA resource.
      description: Updates an UMA resource.
      operationId: put-oauth-uma-resources
      security:
        - jans-auth: [https://jans.io/oauth/config/uma/resources.write]
  '/jans-config-api/api/v1/uma/resources/{id}':
    get:
      tags:
        - OAuth - UMA Resources
      summary: Gets an UMA resource by ID.
      description: Gets an UMA resource by ID.  
      operationId: get-oauth-uma-resources-by-id
      security:
        - jans-auth: [https://jans.io/oauth/config/uma/resources.readonly]
    delete:
      tags:
        - OAuth - UMA Resources
      summary: Deletes an UMA resource.
      description: Deletes an UMA resource.
      operationId: delete-oauth-uma-resources-by-id
      security:
        - jans-auth: [https://jans.io/oauth/config/uma/resources.write]
    patch:
      tags:
        - OAuth - UMA Resources
      summary: Partially updates an UMA resource by Inum.
      description: Partially updates an UMA resource by Inum.
      operationId: patch-oauth-uma-resources-by-id
      security:
        - jans-auth: [https://jans.io/oauth/config/uma/resources.write]
  /jans-config-api/api/v1/scopes:
    get:
      tags:
        - OAuth - Scopes
      summary: Gets list of Scopes.
      description: Gets list of Scopes. Optionally type to filter the scope, max-size of the result and pattern can be provided.
      operationId: get-oauth-scopes
      security:
        - jans-auth: [https://jans.io/oauth/config/scopes.readonly]
    post:
      tags:
        - OAuth - Scopes
      summary: Create Scope.
      description: Create Scope.
      operationId: post-oauth-scopes
      security:
        - jans-auth: [https://jans.io/oauth/config/scopes.write]
    put:
      tags:
        - OAuth - Scopes
      summary: Updates existing Scope.
      description: Updates existing Scope.
      operationId: put-oauth-scopes
      security:
        - jans-auth: [https://jans.io/oauth/config/scopes.write]
  /jans-config-api/api/v1/scopes/{inum}:
    get:
      tags:
        - OAuth - Scopes
      summary: Get Scope by Inum
      description: Get Scope by Inum
      operationId: get-oauth-scopes-by-inum
      security:
        - jans-auth: ['https://jans.io/oauth/config/scopes.readonly']
    delete:
      tags:
        - OAuth - Scopes
      summary: Delete Scope.
      description: Delete Scope.
      operationId: delete-oauth-scopes-by-id
      security:
        - jans-auth: [https://jans.io/oauth/config/scopes.write]
    patch:
      tags:
        - OAuth - Scopes
      summary: Update modified attributes of existing Scope by Inum.
      description: Update modified attributes of existing Scope by Inum.
      operationId: patch-oauth-scopes-by-id
      security:
        - jans-auth: [https://jans.io/oauth/config/scopes.write]
components:
  securitySchemes:
    jans-auth:
      type: oauth2
      description: Authorization
      flows:
        clientCredentials:
          tokenUrl: 'https://{op-hostname}/.../token'
          scopes: 
            https://jans.io/oauth/jans-auth-server/config/properties.readonly: View Auth Server properties related information
            https://jans.io/oauth/jans-auth-server/config/properties.write: View and manage Auth Server properties related information
            https://jans.io/oauth/config/fido2.readonly: View FIDO2 related information
            https://jans.io/oauth/config/fido2.write: View and manage FIDO2 related information
            https://jans.io/oauth/config/attributes.readonly: View attribute related information
            https://jans.io/oauth/config/attributes.write: View and manage attribute related information
            https://jans.io/oauth/config/acrs.readonly: View ACRS related information
            https://jans.io/oauth/config/acrs.write: View and manage ACRS related information
            https://jans.io/oauth/config/database/ldap.readonly: View LDAP database related information
            https://jans.io/oauth/config/database/ldap.write: View and manage LDAP database related information
            https://jans.io/oauth/config/database/couchbase.readonly: View Couchbase database information
            https://jans.io/oauth/config/database/couchbase.write: View and manage Couchbase database related information
            https://jans.io/oauth/config/scripts.readonly: View cache scripts information
            https://jans.io/oauth/config/scripts.write: View and manage scripts related information
            https://jans.io/oauth/config/cache.readonly: View cache related information
            https://jans.io/oauth/config/cache.write: View and manage cache related information
            https://jans.io/oauth/config/smtp.readonly: View SMTP related information	
            https://jans.io/oauth/config/smtp.write: View and manage SMTP related information
            https://jans.io/oauth/config/logging.readonly: View logging related information	
            https://jans.io/oauth/config/logging.write: View and manage logging related information
            https://jans.io/oauth/config/jwks.readonly: View JWKS related information	
            https://jans.io/oauth/config/jwks.write: View and manage JWKS related information	
            https://jans.io/oauth/config/openid/clients.readonly: View clients related information
            https://jans.io/oauth/config/openid/clients.write: View and manage clients related information	
            https://jans.io/oauth/config/openid/sectoridentifiers.readonly: View sector related information
            https://jans.io/oauth/config/openid/sectoridentifiers.write: View and manage sector related information		
            https://jans.io/oauth/config/scopes.readonly: View scope related information
            https://jans.io/oauth/config/scopes.write: View and manage scope related information
            https://jans.io/oauth/config/uma/resources.readonly: View UMA Resource related information
            https://jans.io/oauth/config/uma/resources.write: View and manage UMA Resource related information