name: release
on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  release-mega-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
      id: release-please
      with:
         release-type: simple
         token: ${{ secrets.MOAUTO_WORKFLOW_TOKEN }}
