name: Delete old workflow runs
on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  del_runs:
    permissions:
      actions: write  # to delete old workflow runs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@b3018382ca039b53d238908238bd35d1fb14f8ee # v2.1.0
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 2
