<#macro main>

    <h3 class="text-center">In your opinion, how frequent should meetings be?</h3>
    
    <div>
        <input type="radio" name="option" id="1" value="biweekly" checked>
        <label for="1">Twice a week</label>
    </div>
    <div>
        <input type="radio" name="option" id="2" value="weekly">
        <label for="2">Once a week</label>
    </div>
    <div>
        <input type="radio" name="option" id="3" value="monthly">
        <label for="3">Once a month</label>
    </div>
    <div>
        <input type="radio" name="option" id="4" value="quarterly">
        <label for="4">Quarterly</label>
    </div>

</#macro>
