<#macro main>

    <h3 class="text-center">Are there any new topics meetings should focus on? Check as many as you like</h3>
    
    <div>
        <input type="checkbox" name="option" id="1" value="crypto">
        <label for="1">Cryptocurrencies and neobanks</label>
    </div>
    <div>
        <input type="checkbox" name="option" id="2" value="occultism">
        <label for="2">Occultism</label>
    </div>
    <div>
        <input type="checkbox" name="option" id="3" value="disorders">
        <label for="3">Mental disorders</label>
    </div>
    <div>
        <input type="checkbox" name="option" id="4" value="superclusters">
        <label for="4">Colliding superclusters</label>
    </div>
    
</#macro>
