<#macro main>

    <h3 class="text-center">To cope with our increasing costs of operation, would you be OK with paying more for your membership?</h3>
    
    <div>
        <input type="radio" name="option" id="1" value="yes" checked>
        <label for="1">Sure</label>
    </div>
    <div>
        <input type="radio" name="option" id="2" value="no">
        <label for="2">Nay</label>
    </div>
    <div class="p-2">
        <p>Add any comment or suggestion in this regard:</p>
        <textarea name="text" rows="5" cols="40"></textarea>
    </div>

</#macro>
