<#macro main>

    <h3 class="text-center">Would you recommend your friends or family join the Club?</h3>
    
    <div>
        <input type="radio" name="option" id="1" value="yes" checked>
        <label for="1">Yes, of course</label>
    </div>
    <div>
        <input type="radio" name="option" id="2" value="likely">
        <label for="2">Likely</label>
    </div>
    <div>
        <input type="radio" name="option" id="3" value="notsure">
        <label for="3">I'm not sure</label>
    </div>
    <div>
        <input type="radio" name="option" id="4" value="no">
        <label for="4">I don't think so</label>
    </div>

</#macro>
